### ISSUE TITLE
Graph returns "Preservation Hold library" as OneDrive drive resource for some Business accounts

### ISSUE THREAD

**Issue by 23W** [microsoftgraph/msgraph-sdk-dotnet#1062]
**Describe the bug**
For some Microsoft Business accounts  (work or school account) request [`GET /me/drives`](https://docs.microsoft.com/en-us/graph/api/drive-list?view=graph-rest-1.0&tabs=http#list-the-current-users-drives) returns collection of user's drives with "Preservation Hold library" among them. 
Drive resource doesn't contain any information that allows detect this library so as to skip in further processing.

**To Reproduce**
1. Get access token by MSAL with scopes Files.ReadWrite.All, User.ReadBasic.All, User.Read and account with Preservation Hold Library.
2. Execute request ` var drives = await graphClient.Me.Drives.Request().GetAsync();` that should return drives collection of OneDrive for Business.

**Actual behavior**
Collection of drives contains "Preservation Hold Library"

**Expected behavior**
Preservation Hold library must be skipped by the API graph and is not returned to the client.
Another variant is the drive resource should contain some field for detecting and skipping this library on the client side.

**Screenshot**
![image](https://user-images.githubusercontent.com/11534020/125663750-ed8ab46b-f152-41d1-afad-c5a249b0f899.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1

**Additional information:**
https://stackoverflow.com/questions/68380957/msgraph-onedrive-and-preservation-hold-library
 
[AB#10216](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10216)

**Comment by andrueastman** [comment]
Hey @23W,
Thanks for raising this issue. Unfortunately, this repository is only intended for issues that are related to the client library. 

To get further clarification on what is actually expected from the API side, I have raised the question at the link below and the API owners should get back to us with further clarification.

https://docs.microsoft.com/en-us/answers/questions/487059/graph-returns-34preservation-hold-library34-as-one.html

Closing this for now so that this may be followed up there.
