### ISSUE TITLE
Discard checkout!

### ISSUE THREAD

**Issue by 23W** [microsoftgraph/msgraph-sdk-dotnet#1076]
**Is your feature request related to a problem? Please describe.**
Checkout and Checkin operations have been implemented in v1.0 API, but important operation "discard checkout" is still absent there. When will it be implemented?
Give us workaround while it is absent.

**Describe the solution you'd like**
It would be very nice to have "discard checkout" operation for DriveItem.
 
[AB#10405](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10405)

**Comment by andrueastman** [comment]
Hey @23W,

Thanks for raising this. This repository is mainly for client library issues and the request raised is related to a request on the API side. 

We have submitted your request at the link below so that the request may reach the relevant API team. (Don't forget to upvote on it so that it may also gain more visibility).

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/discard-checkout/idi-p/2603284#M238

Closing this for now so that it may be followed up there.
