### ISSUE TITLE
List/Search for all pictures on User's OneDrive

### ISSUE THREAD

**Issue by NightOwlCoder** [microsoftgraph/msgraph-sdk-dotnet#1078]
Hey there guys, I was tasked with an app to read and display all pictures on a User's OneDrive.

The app is supposed to support search and order by, also having a scrollviewer with all pictures found (much like the OneDrive website does today with user's pictures).

I have searched high and low and I'm still not sure how to implement this.
I know I can get the root drive and after paginating through all the driveitems on it, download only the "pictures" ones.
This seems counter-productive, as anytime I run the app I would need to do it again?

I was trying to find an API that could provide me all pictures since a certain date, so I could always keep an up to date list of available pictures.

Is there anything like this or do I need to resort to the brute force method of listing everything in a drive?
And if I do, I'm not sure how to get the new last pictures since 3 days ago, for instance.

Thank you for any help,
.Sergio

 
[AB#10433](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10433)

**Comment by andrueastman** [comment]
Hey @NightOwlCoder,

Thanks for raising this issue. In order to achieve what you desire, I would suggest to start looking at the way to track changes of drive as shown in the documentation [here](https://docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&tabs=http). 

Please note also that this repository is ideally meant for issues with the client library itself. To get help with api related issues/queries, you can always post a question at the link below. 

https://docs.microsoft.com/en-us/answers/products/graph
