### ISSUE TITLE
App install context in not exposed in Graph SDK and also not returned in the Graph Explorer.

### ISSUE THREAD

**Issue by SangameshGouriFlexera** [microsoftgraph/msgraph-sdk-dotnet#1092]
App install Execution context property is not exposed to be set from the Microsoft Graph SDK client(Version : 3.19.0.0) for msi packages WindowsMobileMSI class. Is there any specific reason for not exposing it from Graph SDK ?

Thanks,
Sangamesh 
[AB#10598](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10598)

**Comment by andrueastman** [comment]
Hey @SangameshGouriFlexera,

The SDK is generated from the metadata that is available [here](https://graph.microsoft.com/v1.0/$metadata) and the property mentioned is not present at the moment.

![image](https://user-images.githubusercontent.com/6464005/128990405-5ca53683-cc66-4d90-b4ab-93cb4535fba5.png)

Any chance you could provide more information on whether/how the property can indeed be set/retrieved?

**Comment by SangameshGouriFlexera** [comment]
Hi @andrueastman Thanks for the quick reply. Property App install context is not available as part of metadata as shown in UI below. I wanted to know the reason why this property is not exposed as part of metadata of winsdowsMobileMSI.
![image](https://user-images.githubusercontent.com/57989521/128992128-065fe18d-37e9-4577-b048-b03136ec31e1.png)

**Comment by andrueastman** [comment]
Thanks for the extra information @SangameshGouriFlexera.

As this repository specifically deals with client library related issues, we may not be in a position to know if this is a bug or something unsupported.

Please raise the same question at the link below with the appropriate tag and the relevant API owner should be able to give us more information on the status of this. (It would be great if you would also add the link to the question in this issue so that future users may find the information as well)

https://docs.microsoft.com/en-us/answers/products/graph

Closing this for now so that it may be followed up there.
