### ISSUE TITLE
statusCode no longer returned in contact additionalData

### ISSUE THREAD

**Issue by under3415** [microsoftgraph/msgraph-sdk-dotnet#1096]
**Describe the bug**
UWP project
In Graph v3.x, I was able to get statusCode after creating a contact. This is no longer available in graph version 4.1

**To Reproduce**

````  //create contact
Contact resp = await graphClient.Me.Contacts.Request().AddAsync(o);
                            
//get response
Dictionary<string, object> dict = (Dictionary<string, object>)resp.AdditionalData;
if(dict.TryGetValue("statusCode", out object statusObject))
{
 statusCode = statusObject.ToString();
}
````

**Expected behavior**
Get status code such as "Created"

**Desktop (please complete the following information):**
 - OS: Windows 10 H2
 - Browser N/A UWP

**Additional context**
UWP project
 
[AB#10628](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10628)

**Comment by andrueastman** [comment]
Hey @under3415,

Thanks for raising this issue.

This is the expected behaviour and is covered in the upgrade guide to v4 of the sdk [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v4.md#http-status-code-and-headers-are-not-placed-into-the-additionaldata).

If you want to obtain the response headers, you can refer to the upgrade guide and should be able to do so with the following code.

```cs
GraphResponse<Contact> response = await graphServiceClient.Me.Contacts.Request().AddResponseAsync(o);
HttpHeaders responseHeaders = response.HttpHeaders; // get the headers
HttpStatusCode statusCode = response.StatusCode; // get the status code
```
