### ISSUE TITLE
Retrieving People without specifying an explicit $top parameter value leads to an invalid NextPageRequest

### ISSUE THREAD

**Issue by edoust** [microsoftgraph/msgraph-sdk-dotnet#1102]
**Steps to repro**

Do the following request to the graph api, this will return the default number of items (currently 10):
`GET https://graph.microsoft.com/v1.0/me/people?$filter=personType/class%20eq%20'Person'`

Use the `NextPageRequest` property from .NET SDK (or the value of `@odata.nextLink`) to make a request to retrieve further people from the graph api, this will lead to the following request being made:
`GET https://graph.microsoft.com/v1.0/me/people?%24filter=personType%2fclass+eq+%27Person%27&%24skip=0`

The value in the `$skip` parameter should now be `10`, but it actually is `0`

**Workaround**
Explicitly specify a value for `$top`, then the `$skip` value of the `NextPageRequest` is set correctly 
[AB#10689](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10689)

**Comment by andrueastman** [comment]
Hey @edoust, 
Thanks for raising this. 

This seems to be an issue with the API as the @odata.nextLink property returned used for paging is incorrect. See below result from graph explorer.

![image](https://user-images.githubusercontent.com/6464005/129517988-9d2ec8e1-e345-4baa-8ed2-fc9bd948c5dd.png)

I have raised the same issue at the link below so that we may get feedback/resolution from the relevant API owners.

https://docs.microsoft.com/en-us/answers/questions/514816/retrieving-people-without-specifying-an-explicit-t.html

Closing this for now so that we may follow it up there.
