### ISSUE TITLE
[Client bug]: Possible Injection

### ISSUE THREAD

**Issue by eluchsinger** [microsoftgraph/msgraph-sdk-dotnet#1113]
**Describe the bug**
When using functionality, like `Filter`, it could be possible to inject an attack via the query. This was already talked about in a previous issue (https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/626), that was closed without taking care of the issue. The problem **is** that the SDK is a pass-through to the service.

**To Reproduce**

First write this query:

```csharp
await graphClient.Users
                .Request()
                .Filter($"identities/any(c:c/issuerAssignedId eq '{username}' and c/issuer eq '{issuer}')")
                .GetAsync(cancellationToken);
```

Then use the following input: `'myUsername'`

The result is the query being forwarded 1:1 to the service and the service failing with `BadRequest: Invalid filter clause`.

If I use an input like: `username1' or c/issuerAssignedId eq 'username2`, I get a `Request_UnsupportedQuery` error, which is probably because the filter clause currently can not query that.

Nonetheless, I believe the evidence shows that the query gets forwarded 1:1 to the service and can be attacked by an injection attack. 

**Expected behavior**

The SDK should escape the filter query in place and just return the same result as if the user was not found.

**Screenshots**

**Client version**
Microsoft.Graph 4.0.0

**Additional context**
 
[AB#10812](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10812)

**Comment by josteink** [comment]
This issue is also causing "regular" unmalicious requests to fail when trying to look up files:

Consider the following code-sample:

````c#
var queryResult = await _graphUserSvcClient.Sites[driveId]
    .Drives[folderId]
    .Root
    .ItemWithPath(searchLocation)
    .Children
    .Request()
    .Filter($"startsWith(name, '{fileNameWithoutExtension}')")
    .GetAsync();
````

If `fileNameWithoutExtension` contains something as simple (and common!) as a `&` character in it, this code will now crash with a 400 Bad Request-response.

This forces API consumers to manually escape the input to this function, and it's not at all obvious through the API that this should be required for correct (and secure) operation.

**Comment by josteink** [comment]
This bug is now marked complete, but it’s not entirely obvious for me *how* it was resolved, and how we should proceed write correct/secure code.  

Would it be possible to provide more details, @ddyett ?

**Comment by mvromer** [comment]
It would be good to know what resolution (if any) was done to close out this issue. As [this comment](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/626#issuecomment-589407477) in the previously referenced issue says, neither the Graph SDK nor the Graph API docs really guide people into a pit of success when it comes to writing correct and secure app code that calls the Microsoft Graph API. I tried searching Microsoft Docs, and I couldn't find anything that talked about writing secure queries.

With regards to my use case, I had a problem where a Get Users call failed because a user-provided value that was being used to construct the filter had an apostrophe in it. In my case I just received a relatively benign 400 Bad Request error from the service, but it did highlight the potential opportunity for an injection attack. I only knew how to go about fixing things after seeing that the [filter docs](https://learn.microsoft.com/en-us/graph/filter-query-parameter?tabs=http) linked out an OData specification and then searching that doc for information on any sort of escaping rules. I eventually found the relevant info [here](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_URLSyntax) a few sections above where the MS Graph docs link to.

I mention all this to say that this information is not terribly discoverable, yet it seems pretty important for anyone wanting securely use any sort of user-provided values in queries made to MS Graph. At least a callout to relevant escaping rules in the SDK docs would be good with examples. Even better, as others have mentioned, would be some form of parameterized query that can automatically handle some of these for users of the SDK so that they better guided down the path of security.
