### ISSUE TITLE
Support an ExternalId when creating OnlineMeetings OR expand CreateOrGet input options

### ISSUE THREAD

**Issue by jcmrva** [microsoftgraph/msgraph-sdk-dotnet#1121]
I'm using MSAL 4.3.0 and I'm trying to create a Teams meeting with the options available in the [OnlineMeeting ](https://docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0) type.

I'd also like to use ExternalId for several reasons. The ExternalId property doesn't say that it's read-only, so the class API seems like it will work with the Create method, but the Graph API returns an error saying it's only for use with CreateOrGet.
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/a16828a4e8d720cf76a50625d2bb4f889f238d2c/src/Microsoft.Graph/Generated/model/OnlineMeeting.cs#L87-L92

The CreateOrGet method doesn't accept an OnlineMeeting input in MSAL. The endpoint (tested in Graph Explorer) accepts one but ignores some properties. To create a meeting with an external ID, are users expected to:
1. use CreateOrGet
2. use Update to get the other values (lobbyBypassSettings, etc) added?

Just from looking through this, I'm not sure why CreateOrGet needs to exist. If Create accepted an ExternalId and was idempotent by default when it had one, CreateOrGet is redundant.
 
[AB#10964](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10964)

**Comment by andrueastman** [comment]
Hey @jcmrva,

The models for the SDK are actually autogenerated from the [metadata](https://graph.microsoft.com/v1.0/$metadata). Unfortunately, during generation, we make a few assumptions about whether model properties are read only/writeable hence the inconsistency as the information isn't available from the metadata description.

To answer your question, I believe the `CreateOrGet` will be used with the externalID as described [here](https://docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-1.0&tabs=http#request-body) then one can update the properties after and use the externalID to retrieve the updates. 
The Create method doesn't use the externalId as described [here](https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&tabs=http).

As this repository is mainly tied to the client library and issues related to it, you can always forward API related questions at the link below and a relevant API owner should be able to reach to you.

https://docs.microsoft.com/en-us/answers/products/graph

You can always create an idea request for the API as well at the link below so that the relevant API team may get around to implementing it. You could also post the link to the idea request here so that anyone in future may come across this and upvote it as well.

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform
