### ISSUE TITLE
What is the correct way to checkout/checkin a file by GraphAPI SDK

### ISSUE THREAD

**Issue by xiaomi7732** [microsoftgraph/msgraph-sdk-dotnet#1145]
When I try to use check out on a driveItem(exists), I got back:

```jsonc
{
    "error": {
        "code": "invalidRequest",
        "message": "API not found",
        "innerError": {
            "date": "2021-10-01T03:59:41",
            "request-id": "2e16cb90-b82d-4a1b-87dc-ccf91af07756",
            "client-request-id": "2e16cb90-b82d-4a1b-87dc-ccf91af07756"
        }
    }
}
```

Code of invocation:

```csharp
await graphClient.Me.Drive.Items[SelectedItem.Id].Checkout().Request().PostAsync();
```

Here's the SDK version:

```xml
Microsoft.Graph, Version=4.6.0.0
```

FWIW

1. in fiddler, the request looks weird that it ends with `/microsoft.graph.checkout` rather than `/checkout`

```shell
https://graph.microsoft.com/v1.0/me/drive/items/3C8CD58B3E131BED!112/microsoft.graph.checkout
```

2. I tried change the Uri to `/checkout`, got the same error.

3. The doc that I am following: <https://docs.microsoft.com/en-us/graph/api/driveitem-checkout?view=graph-rest-1.0&tabs=http>

4. Tried the beta endpoint in GraphExplorer and got a similar error:
![image](https://user-images.githubusercontent.com/3674549/135564405-b64586af-8cc4-4823-9e62-69816b49d113.png)

5. Also, this was me trying to use checkout on OneDrive Personal, is that supported? I can't find any docs talking about it.
  * I tried it with **OneDrive for Business** and it seems like it is working there.

Please help.

**Comment by andrueastman** [comment]
Hey @xiaomi7732,

Thanks for raising this issue.

As this seems to work with oneDrive for business and not personal (and the result is same in Graph Explorer), this looks to be something up with the API endpoint. 

As this repository is ideally meant for SDK related issues, please raise the same query at the link below and an API owner will give feedback on what needs to be done. It would be great if you could post the link to the question in this issue so that anyone in future may be able to find it as well. 

https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-files.html

Closing this for now and will reopen if anything related to the SDK is raised.

**Comment by xiaomi7732** [comment]
Post the question for future reference:
[Is checkin / checkout files supported by OneDrive Personal?
](https://docs.microsoft.com/en-us/answers/questions/574546/is-checkin-checkout-files-supported-by-onedrive-pe.html)
