### ISSUE TITLE
Online meeting by JoinWebUrl returns only the last meetings of attendance report

### ISSUE THREAD

**Issue by pandimurugan-a** [microsoftgraph/msgraph-sdk-dotnet#1146]
Hi Team,

I am using online meeting graph api endpoints to get all meetings created in an education class(teams group) and attendance report of each meeting.

I get the JoinWebUrl from the ../groups/<group-id>/events and using that url to get the meeting details and attendance report.

The attendance report of the meeting returned by 'get meeting by JoinWebUrl' give us the last meeting attendance report. 

I suspect the problem is that 'get meeting by JoinWebUrl'  returning only one entry of meeting though we created more meetings and also the attendance report is refreshed/updated with the last completed meeting.

Note: I use client credentials application scope.

Please look into this.

Reference: https://docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&tabs=http#example-3-retrieve-an-online-meeting-by-joinweburl

**Comment by andrueastman** [comment]
Hey @pandimurugan-a,

Thanks for raising this issue.

As this repository deals only with SDK related issues, please raise the same query at the link below and an API owner will give feedback on whether the API is expected to return one entry as you observe. It would be great if you could post the link to the question in this issue so that anyone in future may be able to find it as well.

https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-cloud-communications.html

Closing this for now and will reopen if anything related to the SDK is raised.

**Comment by pandimurugan-a** [comment]
Thank you, Andru.

I have raised the same here. 

https://docs.microsoft.com/en-us/answers/questions/577953/online-meeting-by-joinweburl-returns-only-the-last.html
