### ISSUE TITLE
Got Error when using $search on groups object

### ISSUE THREAD

**Issue by fhlbdvt** [microsoftgraph/msgraph-sdk-dotnet#1155]
**Got Error when using $search on groups object**
According to the document, https://docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&tabs=http, I should be able to use $search but it fails when it runs against Azure AD B2C tenant with error "$search is not supported on this tenant"

**To Reproduce**
1. In the C# app, download the Graph library, and instantiate the Graph client object
2. Run the following code
```
var requestOptions = new List<Option>
            {
                new HeaderOption("ConsistencyLevel", "eventual"),
                new QueryOption("$search", $"\"displayName:UniqueName\""),
            };

            var groupResult = await client.Groups.Request(requestOptions).GetAsync();
```
3. See error

**Expected behavior**
There should be no error and expect to see groups with matching condition

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Visual Studio 16.11

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by andrueastman** [comment]
Thanks for the tip @pschaeflein. 
I can confirm the same is documented [here](https://docs.microsoft.com/en-us/graph/known-issues#query-parameters) for search.

@fhlbdvt, I would suggest raising a request at the link below so that the relevant API team may get around to resolving this. (It would be great if you could post back the link of the created issue so that relevant users may find it and upvote it as well)

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform

**Comment by fhlbdvt** [comment]
I've added the request for feature here: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/please-add-option-to-search-for-group-in-b2c-tenant/idi-p/2910888#M425
