### ISSUE TITLE
CreateReply/CreateForward wrong timezone

### ISSUE THREAD

**Issue by Jayrag1990** [microsoftgraph/msgraph-sdk-dotnet#1174]
In our .Net MVC application, we are using Microsoft Graph to retrieve mail messages from a mailbox and then send a reply. For creating the reply, we use the `message.CreateReply()`

The sent datetime is always in the utc timezone in the mail body when we create the reply. For example, in the mail body it says:

**From**: Melissa van Dijk
**Sent**: Friday, November 12, 2021 9:51:49 AM **(wrong timestamp)**
**To**: Melissa van Dijk
**Subject**: Re:Meet for lunch?

When replying via Outlook webmail, we get a correct timestamp.

Is this a bug or do we have to correct this timestamp ourselves? Or do we need to pass the timezone with the REST call somehow?

**Comment by andrueastman** [comment]
Hey @Jayrag1990,

Thanks for raising this. 

As this repository is mainly for client library issues, we may not be the best placed to help out with issues related with API behavior. 
Are you able to raise this question at the link below so that the relevant API team will be able to give feedback on how to best handle this scenario? It would be great if you could post back the link to the question so that future users may also find helpful information about this.

https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-mail.html

Closing this for now and will re-open if any issues are raised with the client library.
