### ISSUE TITLE
Patching the mobilePhone and employeeId of a User to null does not work as expected

### ISSUE THREAD

**Issue by plamber** [microsoftgraph/msgraph-sdk-dotnet#1180]
**Describe the bug**
We are using the SDK to update a user object. I noticed that we can set many values to null and the contents are cleared properly.

This seems not to be the case for the mobilePhone and employeeId property.

**To Reproduce**
- Create a user with employeeid and mobilephone property set
- Patch the user object
```
User userProperties = new User()
{
   MobilePhone = null,
   EmployeeId = null
}
GraphClient.Users["yourUserId"].Request().UpdateAsync(userProperties);
```
- The Mobilephone and EmployeeIds have not been changed

**Expected behavior**
The Graph SDK takes care about this when setting a the mobilephone or employeId to null without using the walkaround seen below.

- Microsoft Graph 3.35.0

**Additional context**
As a workaround based on comments that I saw in #206 you it works if you perform following calls
```
User userProperties = new User()
userProperties.AdditionalData = new Dictionary<string, object>();
userProperties.AdditionalData.Add("mobilePhone", null);
userProperties.AdditionalData.Add("employeeId", null);
GraphClient.Users["yourUserId"].Request().UpdateAsync(userProperties);
```

**Comment by andrueastman** [comment]
Thanks for raising this @plamber. 

For now, you will have to use the workaround mentioned since the serializer is unable to differentiate what null values to put in the payload (Otherwise every property would be set to null).
We are working to resolve this by implementing a backing store and should be resolved in the next major update of the SDK.

Closing this for now as this is tracked via https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/264
