### ISSUE TITLE
Calling Set presence with a timeout under 5m throws an exception

### ISSUE THREAD

**Issue by chrisbardon** [microsoftgraph/msgraph-sdk-dotnet#1186]
Calling this in an application with Presence.ReadWrite.All:

```
            var availability = "Busy";
            var activity = "InACall";
            var expirationDuration = new Duration("PT4M");
            graphClient.Users[userID].Presence
                .SetPresence(availability, activity, AppId, expirationDuration)
                .Request()
                .PostAsync().GetAwaiter().GetResult();
```
Throws:
```
Microsoft.Graph.ServiceException: 'Code: InvalidArgument
Message: The provided [ExpirationDuration] is out of range.
Inner error:
	AdditionalData:
	request-id: ab560bdf-3bff-44b0-a858-1d196b2ad088
```
There is nothing in the documentation about acceptable ranges, so I would assume that any correctly formatted range should be valid.  Either shorter ranges should be accepted, or the docs should be updated to indicate that "PT5M" is the minimum duration that can be set for a presence session.

**Comment by chrisbardon** [comment]
Note that this issue happens if setting an upper limit on presence too.  It looks like the only acceptable range is 5m-240m.  This should either be removed (accept any range) or documented.

**Comment by zengin** [comment]
@chrisbardon the range is documented in the setPresence API documentation: https://docs.microsoft.com/en-us/graph/api/presence-setpresence?view=graph-rest-1.0&tabs=http#request-body

@MIchaelMainer, do you know if APIDoctor parses the documentation for function parameters, in this case for `expirationDuration`, so that we can have this information available in the SDK request builders too?

cc: @baywet and @andrueastman (this could be interesting for SDKs built with kiota too)

**Comment by chrisbardon** [comment]
@zengin I saw that the range was documented.  I was the one who submitted the PR to add it to the docs :)  Question is more whether these limits should be what they are-seems kind of arbitrary to have a 5m minimum and a 4h max-any information on why those limits are what they are?

**Comment by zengin** [comment]
@chrisbardon we really appreciate your contribution to our documentation :)

Since the question is not specific to SDKs, I raised an issue on the documentation page itself, that should get redirected to the correct service team: https://github.com/microsoftgraph/microsoft-graph-docs/issues/15185. Please follow up in that issue.
