### ISSUE TITLE
Allow whitelisting certain error codes for dependent batch requests

### ISSUE THREAD

**Issue by brijshah27** [microsoftgraph/msgraph-sdk-dotnet#1187]
**Is your feature request related to a problem? Please describe.**

We have a feature to make two graph calls add app to chat and add tab to chat.
Where [2] is dependent on [1] api call to be success, but in some use cases we are running into an issue where app is already added to chat and we are getting 409 conflict response. In this scenario, we still want to go ahead and add our app to chat[2] so having 409 conflict as a whitelisted error code for dependent request seems like a good option.

Reference: https://docs.microsoft.com/en-us/graph/sdks/batch-requests?tabs=csharp#batches-with-dependent-requests

**Describe the solution you'd like**

Have batch graph client to be configurable to pass down allowed error code for dependent request.

**Describe alternatives you've considered**

I've explored an option to not use dependent batch request but that could lead to broken functionality and we would have to manually handle valid dependent scenarios.

**Additional context**
n/a

[1] https://docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-1.0&tabs=http
[2] https://docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-1.0&tabs=http

**Comment by andrueastman** [comment]
Hey @brijshah27,

Thanks for raising this. 

Unfortunately, the batch feature implements the feature as described [here](https://docs.microsoft.com/en-us/graph/json-batching#sequencing-requests-with-the-dependson-property) and the dependency (ability to whitelist) of requests is handled on the API end and not by the client library. 

With this, you would therefore have to open up the first message and retry the request based on the response. 

You can however create a feature request for this at the link below so that the API team can look into implementing this.
https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform
