### ISSUE TITLE
User configured presence sessions never expire-app cannot toggle a user to Available from Busy

### ISSUE THREAD

**Issue by chrisbardon** [microsoftgraph/msgraph-sdk-dotnet#1188]
Testing with an application setting user presence I tried the following:
-In Teams, set my presence to Busy.  
-In my application, set my presence to available (new session) with a timeout of 4h
-Wait 4h
-My presence never changes, even when the device I set it on goes idle.  

According to the docs, user set states override application set ones, but this appears to be a case where the user set state never expires, so the application state will never be honored.  This way it appears that a user who sets themselves to Busy can never be automatically moved out of busy by application logic.  

Expected behaviour is that the user-supplied state will have a timeout, or that the application is able to force a presence state change.

**Comment by andrueastman** [comment]
Hey @chrisbardon,

Thanks for raising this. 

As this repo is mainly intended for issues related client library, we may not be the best placed to explain the behavior of certain APIs. I have therefore forwarded the question to the link below so that the relevant API owners may give us clarity on this.

https://docs.microsoft.com/en-us/answers/questions/664176/user-configured-presence-sessions-never-expire-app.html

Closing this for now so that we may follow this up from there.
