### ISSUE TITLE
The latest version of the Microsoft Graph Communications API - 1.2.0.3742 - no longer include the additionalMetadata property, which breaks the logic of a Bot which requires the Caller and Callee properties from the Call object

### ISSUE THREAD

**Issue by igorpastukh99** [microsoftgraph/msgraph-sdk-dotnet#1196]
**Describe the bug**
Parsed JSON objects retrieved via the latest version of the Microsoft Graph Communications API - 1.2.0.3742 - no longer include the "additionalMetadata" property, which breaks the logic of a Bot which requires the Caller and Callee properties from the Call object.
This was not a problem in the previously implemented API version - 1.2.0.1702

**To Reproduce**
1. External Microsoft Teams participant is calling to a participant with recording policy.
2. The call is established.
3. The call object without "additionalMetadata" property received

**Expected behavior**
We expect the "applicationMetadata" field with "caller" and "callee" details in the Call object.

**Screenshots**
Some Call details that we expect (screenshot from the 1.2.0.1702 SDK):
![image](https://user-images.githubusercontent.com/32457211/145871710-bf92478b-5379-453b-9dce-291fd30e5c7c.png)
The method in which we are trying to get the call metadata (calls().OnIncoming event handler):
![image](https://user-images.githubusercontent.com/32457211/145873096-7f24c50b-02ef-41f2-8513-1dd600f7ed9e.png)
call.Resource from the 1.2.0.1702 SDK (objectData from the code above) where we have the required metadata
[OnIncoming_1.2.0.1702.txt](https://github.com/microsoftgraph/msgraph-sdk-dotnet/files/7706234/OnIncoming_1.2.0.1702.txt)
call.Resouce from the 1.2.0.3742 SDK (objectData from the code above) where we do not have the required metadata
[OnIncoming_1.2.0.3742.txt](https://github.com/microsoftgraph/msgraph-sdk-dotnet/files/7706235/OnIncoming_1.2.0.3742.txt)

**Comment by andrueastman** [comment]
Hey @igorpastukh99,

Thanks for raising this issue.

Unfortunately, our team handles the [Microsoft Graph SDK](https://www.nuget.org/packages/Microsoft.Graph) package and a different team maintains the package you are using. 

Could you raise the same issue [here](https://github.com/microsoftgraph/microsoft-graph-comms-samples/issues) and I believe you should receive feedback about the issue. If you can, please also post the link of the issue back here so that anyone in future might be able to find the issue as well.

Closing this for now and will re-open when anything SDK related is raised.
