### ISSUE TITLE
Microsoft AuthHost hangs while acquiring token interactively

### ISSUE THREAD

**Issue by rikyuz** [microsoftgraph/msgraph-sdk-dotnet#1217]
**Describe the bug**
The login prompt window which appears when `AcquireTokenInteractive` is called hangs after entering the password for the user.

**To Reproduce**
1. Open for example the  [msgraph-training-uwp](https://github.com/microsoftgraph/msgraph-training-uwp) demo solution
2. Click the Microsoft.Toolkit.Graph.Controls.LoginButton on the top right corner of the main window
3. Enter username and password for the login window
4. After entering password the process is stuck

**Expected behavior**
The login process should complete normally and `AuthenticationResult` is returned.

**Screenshots**
![dwm_JAQY5doc9H](https://user-images.githubusercontent.com/51473445/148779137-84167409-ad04-44b4-8ffe-8a6673ee43c8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2

**Additional context**
The same issue occurs with the Microsoft.Toolkit.Graph.Controls.LoginButton as well as with utilizing `Microsoft.Identity.Client.IPublicClientApplication` by calling the `AcquireTokenInteractive` method through it.

**Comment by MIchaelMainer** [comment]
Please consider x-posting this to https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/tree/master/src/client/Microsoft.Identity.Client as you are seeing this issue across more than one scenario.

I'm curious, are you running Fiddler while this error occurs?

**Comment by rikyuz** [comment]
Today I tried to reproduce the error and this time I was able to acquire the token without issues. What changed is that this time I didn't use the software over a remote connection to the development PC. I was using Windows 10 built in Remote Desktop for the remote connection when I encountered this issue.

This is not a critical issue to me as I'm able to develop the software directly on the development PC but maybe you should look into it nevertheless.

**Comment by MIchaelMainer** [comment]
@rikyuz and @jc-martin-bc 

Please take a look at these issues, especially the one about configuration for authhost. Circle back with us if the guidance in one of these issues are helpful. Thank you.

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues?q=is%3Aissue+authhost+is%3Aclosed

**Comment by BC89** [comment]
We are also experiencing the same issue on Windows 10 store app. Frustrating because end users do not know how to resolve and spend a good deal of time waiting for control to return from the injected auth windows which never happens. This is a UWP app as well.

**Comment by jc-martin-bc** [comment]
Hi Brendan

We tried updating to latest MSAL NuGet and ConfigureAwait(false), both seemed to work temporarily , in our dev env, for around a day then the issue resurfaced.   It's a UWP app so I think we're going to try switching to WAM, as suggested on one of the threads, but probably not for a week or two.  I'll let you know if that works.


James Martin

Software Engineer, Ballard Chalmers Ltd

A Transparity Company



t. 01342 410223

e. ***@***.******@***.***>

w. ballardchalmers.com<http://www.ballardchalmers.com/>



Award-winning Microsoft Gold Partner



twitter<https://twitter.com/ballardchalmers> | linkedin<http://www.linkedin.com/company/ballard-chalmers-ltd> | subscribe to our newsletter<http://ballardchalmers.com/newsletter/>



This email is from Ballard Chalmers Ltd., registered in England and Wales. Registered office: 9 Nimrod Way, East Dorset Trade Park, Wimborne, England, BH21 7UH. Reg No.: 5644282. VAT No.: 863140343. Should you not wish to receive further emails from Ballard Chalmers Ltd, please forward this message to ***@***.***<https://amsprd0610.outlook.com/owa/redir.aspx?C=EcSixZS49kSGuO99IwJm1nTW4zi1gtAIxDZPxJXfjo673tAqjMgCJKHi4GV9U_LujJy98bYXzug.&URL=mailto%3aadmin%40ballardchalmers.com> with subject line "please remove my email details".



PLEASE NOTE: This email and any files transmitted with it are strictly confidential and intended solely for the use of the individual(s) or organisation to which they are addressed. The views expressed are not necessarily those held by Ballard Chalmers Ltd. If you are not the intended recipient or the employee or agent responsible for delivering it to the intended recipient, copying, distributing or taking any action that relies on the accuracy of the information contained is prohibited. If you have received this email in error please email ***@***.***<https://amsprd0610.outlook.com/owa/redir.aspx?C=EcSixZS49kSGuO99IwJm1nTW4zi1gtAIxDZPxJXfjo673tAqjMgCJKHi4GV9U_LujJy98bYXzug.&URL=mailto%3aadmin%40ballardchalmers.com> by return.

________________________________

**Comment by jc-martin-bc** [comment]
Switched to WAM and no further issues since, thanks for your assistance


James Martin

Software Engineer, Ballard Chalmers Ltd

A Transparity Company



t. 01342 410223

e. ***@***.******@***.***>

w. ballardchalmers.com<http://www.ballardchalmers.com/>



Award-winning Microsoft Gold Partner



twitter<https://twitter.com/ballardchalmers> | linkedin<http://www.linkedin.com/company/ballard-chalmers-ltd> | subscribe to our newsletter<http://ballardchalmers.com/newsletter/>



This email is from Ballard Chalmers Ltd., registered in England and Wales. Registered office: 9 Nimrod Way, East Dorset Trade Park, Wimborne, England, BH21 7UH. Reg No.: 5644282. VAT No.: 863140343. Should you not wish to receive further emails from Ballard Chalmers Ltd, please forward this message to ***@***.***<https://amsprd0610.outlook.com/owa/redir.aspx?C=EcSixZS49kSGuO99IwJm1nTW4zi1gtAIxDZPxJXfjo673tAqjMgCJKHi4GV9U_LujJy98bYXzug.&URL=mailto%3aadmin%40ballardchalmers.com> with subject line "please remove my email details".



PLEASE NOTE: This email and any files transmitted with it are strictly confidential and intended solely for the use of the individual(s) or organisation to which they are addressed. The views expressed are not necessarily those held by Ballard Chalmers Ltd. If you are not the intended recipient or the employee or agent responsible for delivering it to the intended recipient, copying, distributing or taking any action that relies on the accuracy of the information contained is prohibited. If you have received this email in error please email ***@***.***<https://amsprd0610.outlook.com/owa/redir.aspx?C=EcSixZS49kSGuO99IwJm1nTW4zi1gtAIxDZPxJXfjo673tAqjMgCJKHi4GV9U_LujJy98bYXzug.&URL=mailto%3aadmin%40ballardchalmers.com> by return.

________________________________

**Comment by maisarissi** [comment]
Closing this.

Please, reopen if any further assistance is needed.
