### ISSUE TITLE
Contains and EndsWith aren't implemented in filtering

### ISSUE THREAD

**Issue by aredfox** [microsoftgraph/msgraph-sdk-dotnet#1228]
**Describe the solution you'd like**
At the moment `StartsWith()` is present in the API & querying, however `Contains` and `EndsWith` are not.

**Describe alternatives you've considered**
We now have to pull in all elements/objects from the graph and then manually go over them, which is an obvious a waste of time, and cost of data over network.

**Additional context**
It seems like this isn't in the Graph API either when I try using this in the Graph Explorer with following
`https://graph.microsoft.com/beta/groups?$filter=startswith(displayName, 'a')`

**Comment by andrueastman** [comment]
Hey @aredfox.

Thanks for raising this. 

As this seems to be a feature request for the API and not the client SDK, please open a request for the same at the link below. It would be great if you could post back the link of the request as well so that anyone in future may upvote it.

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform
