### ISSUE TITLE
Snippets are missing for .NET - list managers from a user up to root

### ISSUE THREAD

**Issue by maisarissi** [microsoftgraph/msgraph-sdk-dotnet#1246]
I’m trying to get the [list of managers from a user up to root](https://docs.microsoft.com/en-us/graph/api/user-list-manager?view=graph-rest-1.0&tabs=http#example-2-get-manager-chain-up-to-the-root-level) through the Graph API using C#.
I only see documentation for using HTTP, GO, and PowerShell but not C#.

We need to investigate why we are not generating snippets for this scenario. This may be related to CSDL vs OpenAPI snippet generation.

The same situation may be seen for different APIs.

**Comment by zengin** [comment]
@maisarissi, for context, please note that snippet generation fails silently on exceptions in the generation process.

related: https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/437

**Comment by zengin** [comment]
@maisarissi, yes. It is the same for all languages. Known issues are reported here: https://github.com/microsoftgraph/microsoft-graph-devx-api/issues?q=is%3Aissue+is%3Aopen+label%3A%22Area%3Asnippet+generation%22

In order to systematically address this issue, we should create a report from the weekly snippet generation run and investigate the cases where we are not able to generate.
