### ISSUE TITLE
Cannot find type Microsoft.Graph.BaseGetMethodRequestBuilder`1 in module Microsoft.Graph.Core.dll

### ISSUE THREAD

**Issue by mjfara** [microsoftgraph/msgraph-sdk-dotnet#126]
I am unable to build my UWP application whenever I add the Microsoft.Graph package to my project.
I get the following build error, as the title states:
Cannot find type Microsoft.Graph.BaseGetMethodRequestBuilder`1 in module Microsoft.Graph.Core.dll

I've tried both the latest version (1.3) and the one before it, same issue.

Any ideas?

**Comment by MIchaelMainer** [comment]
Hello @mjfara, unfortunately we didn't intend or anticipate that you'd use those classes. BaseGetMethodRequestBuilder was renamed BaseFunctionMethodRequestBuilder since composable functions can result in other HTTP verbs instead of just GET. Change made at [028f846](https://github.com/microsoftgraph/msgraph-sdk-dotnet/commit/028f8465b08dad897097d48107e83f66132dd441). There isn't any behavior change associated with this rename, at least not yet. You'll need to rename your references.

By the way, how are you using this functionality?

**Comment by mjfara** [comment]
I'm actually not using this at all. I simply installed the nuget package and tried to build my application.

**Comment by MIchaelMainer** [comment]
Strange. I no longer find a reference to that type. 

What version of Microsoft.Graph.Core are you using? 
Are you updating your Nuget or was Microsoft.Graph already part of your solution?
Do you have the deemphasized OneDrive client library installed?

**Comment by mjfara** [comment]
I didn't actually install Microsoft.Graph.Core, only Microsoft.Graph, as it's what I seen in the same project.
I completely installed and re-installed the package.
Yes actually, I do have the OneDrive client library installed, do I have to remove it?

**Comment by MIchaelMainer** [comment]
If you no longer need the OneDrive client library, yes, do uninstall it. I suspect that you still need it for now. I believe that all of the OneDrive functionality goes into Microsoft Graph. The OneDrive client library takes a dependency on an earlier version of Microsoft.Graph.Core. I guess that when you installed Microsoft Graph, it updated the Nuget reference to a later version of Microsoft.Graph.Core. The OneDrive client library no longer has a reference to BaseFunctionMethodRequestBuilder.

**Comment by mjfara** [comment]
Got it, uninstalled OneDrive and it compiled fine. I'll have to migrate everything over to the new Graph, thanks for your help!
