### ISSUE TITLE
Graph SDK sometimes doesnt return all users with OrderBy filter

### ISSUE THREAD

**Issue by SangeethaJanakiraman** [microsoftgraph/msgraph-sdk-dotnet#1271]
On some tenants, Graph SDK does not return all users with OrderBy filter

This is the sample request we are providing to get all user. 

     IGraphServiceUsersCollectionPage pageOfUsers =
                    await graphClient.Users.Request().Select(
                        "id,objectId,displayName,userPrincipalName,mail,assignedPlans")
                        **.OrderBy("displayName")**
                        .GetAsync();
     while (null != pageOfUsers.NextPageRequest)
    {
                    pageOfUsers = await pageOfUsers.NextPageRequest.GetAsync();
    }

In some tenants, the above is returning all users.. But in few particular tenants, it stops abruptly and we dont receive all users. 
If we remove the OrderBy filter, it returns all users on those problematic tenants too. 

SdkVersion: Graph-dotnet-1.19.0

**Comment by DennisBergemann** [comment]
Hi,

i think this is not an issue with this SDK, rather with the permissions in the tennants or the endpoint itself.

What happens when you test your query with the Graph Explorer:

https://developer.microsoft.com/en-us/graph/graph-explorer

I guess you will get the same, or better the real reason for your problem.
