### ISSUE TITLE
[Client bug]: OrgContact model is missing imAddresses property

### ISSUE THREAD

**Issue by MichaMican** [microsoftgraph/msgraph-sdk-dotnet#1307]
**Describe the bug**
The OrgContact model of the graphClient misses the imAddresses property, even though the Graph API returns this information in v1:

**To Reproduce**
1. create graph client in c#
2. try to select imAddresses (`graphClient.Contacts.Request().Select(orgContact => new { orgContact.ImAddresses}) ...`)

**Expected behavior**
It is to be expected that ImAddresses is in the model class, as it is a valid property returned by the graph api v1.0

**Screenshots**
(Screenshot from a Demotenant)
![image](https://user-images.githubusercontent.com/45571948/162932431-ed57e44f-a289-4cba-887d-7b43889ce81c.png)
![image](https://user-images.githubusercontent.com/45571948/162932697-4e28fde5-70d2-4d8b-9e73-d36286aa9b6d.png)

**Client version**
4.24.0

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 100.0.4896.75

**Comment by zengin** [comment]
Hi @MichaMican,

Thanks for raising this issue. The `orgContact` doesn't have the `imAddresses` property defined. This means that the data will be served in the `AdditionalData` part of the model.

As a general rule, the server response doesn't necessarily define the model. It can contain additional properties if the type is `OpenType`.

Docs reference for defined properties: https://docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-1.0#properties
Extract from the [metadata](https://graph.microsoft.com/v1.0/$metadata):
```xml
<EntityType Name="orgContact" BaseType="graph.directoryObject" OpenType="true">
  <Property Name="addresses" Type="Collection(graph.physicalOfficeAddress)"/>
  <Property Name="companyName" Type="Edm.String"/>
  <Property Name="department" Type="Edm.String"/>
  <Property Name="displayName" Type="Edm.String"/>
  <Property Name="givenName" Type="Edm.String"/>
  <Property Name="jobTitle" Type="Edm.String"/>
  <Property Name="mail" Type="Edm.String"/>
  <Property Name="mailNickname" Type="Edm.String"/>
  <Property Name="onPremisesLastSyncDateTime" Type="Edm.DateTimeOffset"/>
  <Property Name="onPremisesProvisioningErrors" Type="Collection(graph.onPremisesProvisioningError)"/>
  <Property Name="onPremisesSyncEnabled" Type="Edm.Boolean"/>
  <Property Name="phones" Type="Collection(graph.phone)"/>
  <Property Name="proxyAddresses" Type="Collection(Edm.String)" Nullable="false"/>
  <Property Name="surname" Type="Edm.String"/>
  <NavigationProperty Name="directReports" Type="Collection(graph.directoryObject)"/>
  <NavigationProperty Name="manager" Type="graph.directoryObject"/>
  <NavigationProperty Name="memberOf" Type="Collection(graph.directoryObject)"/>
  <NavigationProperty Name="transitiveMemberOf" Type="Collection(graph.directoryObject)"/>
</EntityType>
```

Does this answer your question?

**Comment by MichaMican** [comment]
Generaly speaking: yes.
But i do not realy understand what you mean by "orgContact doesnt have the property imAdresses defined". Does this mean that it is not intended for an orgContact to have an imAddress? Why is it returned from the graph per default then in the firstplace?

Cheers 😉

**Comment by zengin** [comment]
orgContact as the JSON response may have the property, but the official orgContact definition doesn't have the property, and there could be various reasons for this. It is a service design decision based on the flexibility provided by the OData standard. More on open types: https://docs.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/odata-v4/use-open-types-in-odata-v4

The contract between SDK generation process and the service is the metadata, we cannot consume service response to an API call to determine which properties need to be part of the SDK model, because for open types the object shape may change from one call to another.

All that said, one could argue that the property is always there, and maybe should be defined as a property in the metadata. That is a matter of service design and should be redirected to the service team.

**Comment by zengin** [comment]
Closing as the client behaves as expected.
