### ISSUE TITLE
Property "phones" of orgContact on GraphAPI can't be selected

### ISSUE THREAD

**Issue by MichaMican** [microsoftgraph/msgraph-sdk-dotnet#1314]
**Describe the bug**
When trying to select the property "phones" the graph does not return anything besides the odata info

**To Reproduce**
1. Create orgContact
2. Give orgContact phone number
3. Try to select phone number of orgContact

**Expected behavior**
phones property should be returned.

**Screenshots**
![image](https://user-images.githubusercontent.com/45571948/163335173-3883ea48-14f4-4c40-9aa7-79a608ed4835.png)
<img width="633" alt="image" src="https://user-images.githubusercontent.com/45571948/163335301-f3ba7f76-4f32-4435-a9b9-541428b7cbfe.png">
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/45571948/163335350-4b36ef1e-ac4a-477e-ac8e-21c8ad49895c.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser crome
 - Version 100.0.4896.88

**Comment by andrueastman** [comment]
Hey @MichaMican,

Thanks for raising this. 

Taking a look at the docs [here](https://docs.microsoft.com/en-us/graph/api/resources/orgcontact?ranMID=46131&ranEAID=a1LgFw09t88&ranSiteID=a1LgFw09t88-WVSqLFgqsQxMHqWH38kmoA&epi=a1LgFw09t88-WVSqLFgqsQxMHqWH38kmoA&irgwc=1&OCID=AID2200057_aff_7806_1243925&tduid=(ir__kei6bxg00okf6k1d6lqdys90ln2xtqinzkottgck00)(7806)(1243925)(a1LgFw09t88-WVSqLFgqsQxMHqWH38kmoA)()&irclickid=_kei6bxg00okf6k1d6lqdys90ln2xtqinzkottgck00&view=graph-rest-1.0#properties), it is not clearly stated whether the property supports or doesn't support the select query parameter.

As this repo is intended for issues related to the SDK and the issue seems to be an issue with API, could you please post the same query at the link below so that the relevant API owners may give feedback on what should be the correct functionality? 

https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-contacts.html

It would be great if you also post back the link to the question in this issue so that in future someone else may find the information if they come across this. I will close this issue for now and will re-open in the event anything SDK related is brought up.

**Comment by MichaMican** [comment]
https://docs.microsoft.com/en-us/answers/questions/812890/property-34phones34-of-orgcontact-on-graphapi-can3.html
