### ISSUE TITLE
QuickXorHash for an older version of a OneDrive with Graph API

### ISSUE THREAD

**Issue by akutsyk** [microsoftgraph/msgraph-sdk-dotnet#1321]
Hi,
I'm interesting of getting quickXorHash value for each version of file not only for the current one.

Currently in delta request https://graph.microsoft.com/v1.0/me/drive/root/delta  you able to get 
```
"file": {
                "mimeType": "text/plain",
                "hashes": {
                    "quickXorHash": "VogBCOhQhjnQAQRkBAMdwgAAAAA="
                }

```
Which is related to latest version only.

In case of requesting list of file versions you can't get version quickXorHash .
For instance:
https://graph.microsoft.com/v1.0/me/drive/items/01BGLZ6A6YCKUSPHU5BNHJV7TYA7SHPDUI/versions
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('31d7477d-8ece-43e9-b8aa-0cd35129a36e')/drive/items('01BGLZ6A6YCKUSPHU5BNHJV7TYA7SHPDUI')/versions",
    "value": [
        {
            "id": "1.0",
            "lastModifiedDateTime": "2022-04-13T14:32:52Z",
            "size": 12,
            }
        }
    ]
}

To have version hash is very important and allows to identify unchanged content.

**Comment by andrueastman** [comment]
Hey @akutsyk,

Thanks for raising this. 

It looks like https://graph.microsoft.com/v1.0/me/drive/root/delta API will return collections of the [DriveItem ](https://docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0) resource type while https://graph.microsoft.com/v1.0/me/drive/items/01BGLZ6A6YCKUSPHU5BNHJV7TYA7SHPDUI/versions API will return instances of the [DriveItemVersion](https://docs.microsoft.com/en-us/graph/api/resources/driveitemversion?view=graph-rest-1.0) resource type.

The [DriveItemVersion](https://docs.microsoft.com/en-us/graph/api/resources/driveitemversion?view=graph-rest-1.0) resource does not contain the file property and therefore explains the scenario.

As this is an API side change/request I would suggest creating a feature request at the link below for the API owners to prioritize. It would also be great if you could post back the link to the idea request here so that any future users who come across this may upvote the request.

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform

Closing this for now and will re-open in the event any SDK related issue comes up.
