### ISSUE TITLE
How to work with ProfilePhoto

### ISSUE THREAD

**Issue by fridobobo** [microsoftgraph/msgraph-sdk-dotnet#1357]
I am currently working with the latest preview. So far everything is working just fine, but I don't know how to set the profile photo of a contact. There is a property called photo in the Contact class, which is also settable. Unfortunally the ProfilePhoto-class has no non emtpy constructor so I don't know how can i get my jpeg inside of that property.

Any help will be greatly appreciated.

**Comment by andrueastman** [comment]
Hey @fridobobo,

Thanks for trying out the new preview.

In the event of setting the profile photo of a contact, do you have any luck doing something similar to below?

```cs
        using var stream = new System.IO.MemoryStream(Encoding.UTF8.GetBytes(@"Binary data for the image"));

        await graphServiceClient.Me.Contacts["contact-id"].Photo.Content
            .PutAsync(stream);
        
        // Another alternative
        // await graphServiceClient.Users["user-id"].Contacts["contact-id"].Photo.Content
        //    .PutAsync(stream);
```

**Comment by andrueastman** [comment]
Hey @fridobobo,

The `photo` property is a `NavigationProperty` of the larger `Contact` model as defined in the API schema (thus it is not really a structural part but a link).

![image](https://user-images.githubusercontent.com/6464005/169987880-284e2ae3-3813-4a6e-8de3-07b536cffc53.png)

Due to this, to directly manipulate the `photo` object, you would need to use the URL path.
