### ISSUE TITLE
Enumerate sites with a filter error

### ISSUE THREAD

**Issue by agonzalezm** [microsoftgraph/msgraph-sdk-dotnet#1371]
I am trying to get sites with a filter as documented here: https://docs.microsoft.com/en-us/graph/api/site-list?view=graph-rest-beta&tabs=csharp

But i always get an error if I apply a filter:

await graphClient.Sites.GetAsync(f=> { f.Filter = "contains(webUrl, 'sites')"; f.Select = new[] { "webUrl", "displayName" }; });

Error: "the request is not supported by the system." or "cannot enumerate sites"

**Comment by andrueastman** [comment]
Hey @agonzalezm,

Thanks for raising this.

According to the documentation, the filter query is not supported by the API at the moment.

![image](https://user-images.githubusercontent.com/6464005/172110915-ee8251dd-5839-4d2c-8c8d-de5130a04ab3.png)

For now, we would suggest raising a feature request at the link below for the API team to add support for more filter parameters. If you can, please post the link to the idea so that in future anyone who comes across this may find it and upvote it as well. 

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform

Closing this for now and will re-open if anything SDK related is raised.
