### ISSUE TITLE
Graph Beta-Api return to many contacts

### ISSUE THREAD

**Issue by fridobobo** [microsoftgraph/msgraph-sdk-dotnet#1384]
Since my original ticket was closed but my problem still exists I am going to open up a new one. Please see the original here: 
_Originally posted by @fridobobo in https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1359#issuecomment-1153984496_

With the normal endpoint I get 1 result (which is correct), with the beta endpoint the same requests gives me more then 3000 results. Some of them seems to be people i have been in contact with, while some other I don't even know. I also tried out finding out which folder are they coming from, but I have only 2 folders in my account and none of them has a corresponding id.

So this is really confusing and while some of the features at the beta endpoint really look helpfull to me I am affraid in using this endpoint if I don't understand what is going on. Therefore I would really like to know:

- What is going on here? Where are those contacts coming from?
- How can I make sure to get only the contacts which are actualy in my Outlook?
- What is this beta-endpoint about? Why are there features being planned for a few years but not yet rolled out to production? Is it a trustfull endpoint for my application?

**Comment by andrueastman** [comment]
Hey @fridobobo,

Thanks for following up on this.

As this repository is mainly intended for issues related to the functionality of the client library, we may not be the best placed to answer some queries that are tied to the functionality of the API.

https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-contacts.html

Any chance you can post the same query at link below so that we may be able to get clarity from the API owners? It would be great if you could post back the link here so that anyone in future may also be able to find the information on the same.

**Comment by fridobobo** [comment]
Update: I also posted my question in the suggested forum: https://docs.microsoft.com/en-us/answers/questions/895572/beta-endpoint-returns-to-many-contacts.html

**Comment by andrueastman** [comment]
Thanks @fridobobo,

We should be able to get feedback from the API team from there. For now, we'll close this issue and re-open in the event anything SDK related is raised,
