### ISSUE TITLE
OneNote.SectionGroups returns all directories in a site. 

### ISSUE THREAD

**Issue by kloetje** [microsoftgraph/msgraph-sdk-dotnet#1387]
**Describe the bug**
When you execute the OneNote.SectionGroups I query on a Sharepoint site you also get all the normal directories in your response.

**To Reproduce**
1. Create a OneNote with some Sections and save them into the Documents of a Site.
2. Also put some random directories into the Documents of the site. 
3. Query the site via the GraphAPI with Onenote.SectionGroups 
4. You get all the normal Directories as a result. 

**Expected behavior**
Should only return the SectionGroups from the all the OneNotes in the Site **and NOT the normal directories of the site.**

According to the [documentation](https://docs.microsoft.com/en-us/graph/api/resources/sectiongroup?view=graph-rest-1.0): 
_A section group in a OneNote notebook. Section groups can contain sections and section groups._

**Extra information*
 - Via NuGet 
 - Same bug with normal rest calls via the Graph Explorer

**Comment by andrueastman** [comment]
Hey @kloetje,

Thanks for raising this.

As this behavior seems to be a service issue since it's replicable on Graph Explorer as well, I believe we can follow up with the API owners at the already created query at the link below. 

https://docs.microsoft.com/en-us/answers/questions/896393/microsoft-graph-onenotesectiongroups-returns-all-d.html

For now, we'll close this and re-open in the event anything SDK related is raised.
