### ISSUE TITLE
msgraph-sdk Mail/Outlook 365 - Porting from EWS:  What's the equivalent of EWS EventType.Moved for Subscritions and/or DeltaRequests?

### ISSUE THREAD

**Issue by tradem** [microsoftgraph/msgraph-sdk-dotnet#1411]
Hi folks,

we currently porting EWS connections in our application (EWS support fo Office/Outlook 365 will be outdated soon/this fall) for all our customers using Outlook as port of Office 365. 

EWS offered `EventType.Moved` for subscritions in order to deteced mails which has been **moved** to observerd mail forder. Some of our uses cases are based heavily on this feature. 

So we are wondering what's the equivalent of  `EventType.Moved`  is in msgraph.

 [subscription](https://docs.microsoft.com/de-de/graph/api/resources/subscription?view=graph-rest-1.0) resource does only offer the following: `changeType`-s `created`, `updated` and/or  `deleted` . 

**How should we map/port  `EventType.Moved`  from EWS to msgraph?**

[Delta requests](https://docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&tabs=http)  cannot be filtered for moved mails either or this there a hidden feature or a neat trick in order to detect if a mail has been moved into an folder?

Any hints for this porting issue would be really great!

Thx

**Comment by andrueastman** [comment]
Thanks for raising this @tradem 

As this repository is mainly intended for issues related to the dotnet client library, we may not be the best placed to give answers to some API related questions. 
Any chance you could also post this question at the link below to get feedback from the relevant API owners? (It would also be great if you could post back the link to the question created back in this issue so that anyone who comes across this may also follow it and learn from it as well)

https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-mail.html

**Comment by tradem** [comment]
Hi @andrueastman  Thx for your hint. 

I've cross posted my questiong recarding API here: https://docs.microsoft.com/en-us/answers/questions/928009/mailoutlook-365-porting-from-ews-to-msgraph-what39.html
