### ISSUE TITLE
Delta API response does not differentiate moved vs modified files.

### ISSUE THREAD

**Issue by SangeethaJanakiraman** [microsoftgraph/msgraph-sdk-dotnet#1414]
When a file is moved from one folder to another or if the file is modified in the same location, delta API response just sends the moved folder and file in  the response. 
From the response, we are not able to find out the reason for the file change. We want to differentiate between file moves vs file modified.  

It would be better if we get some tag in the file response to indicate that the file is moved.

**Comment by andrueastman** [comment]
Hey @SangeethaJanakiraman,

Thanks for raising this. 

As this is an API side feature request and this repo is mainly intended for issues related to the client library, any chance you could create the feature request at the link below for the API owners to follow it up? (It would also be great if you could post back the link to the request created back in this issue so that anyone who comes across this may also follow it and possibly upvote it as well) 

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform

**Comment by andrueastman** [comment]
Thanks @SangeethaJanakiraman. We'll close this for now so that we can follow it from there.
