### ISSUE TITLE
[Todo] How to remove the dueDateTime of a todo task?

### ISSUE THREAD

**Issue by 1357310795** [microsoftgraph/msgraph-sdk-dotnet#1418]
**Describe the bug**
https://docs.microsoft.com/en-us/graph/api/todotask-update?view=graph-rest-1.0&tabs=http

I can make a http request with body
```
{
    "dueDateTime": null
}
```
to remove the dueDateTime of a Todo task.

But the SDK ignores null values when serializing the model
```
task.DueDateTime = null;
            var todoTask = client.Me.Todo.Lists[$"{tasklistid}"].Tasks[$"{taskid}"]
                 .Request()
                 .UpdateAsync(task).Result;
```
![image](https://user-images.githubusercontent.com/35869804/179354364-fe071dcd-2586-42f1-96b6-05e021902ccf.png)

**To Reproduce**
1. Create a todo task with dueDateTime.
2. Make a `UpdateAsync` request using the SDK
3. See if the dueDateTime is removed

**Comment by andrueastman** [comment]
Thanks for raising this @1357310795 

Due to the way the serializer works, null values are not emitted by default. To send out null values, you can take advantage of the using the additionalData bag as in the example below.

```cs
task.AdditionalData["dueDateTime"] = null;
var todoTask = client.Me.Todo.Lists[$"{tasklistid}"].Tasks[$"{taskid}"]
                 .Request()
                 .UpdateAsync(task).Result;
```

We are also working on a new version of the SDK that is in preview that should resolve this issue by use of a backing store. This is outlined at the link below. If you're willing to try it out, you can find out more here. 

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md#new-features
