### ISSUE TITLE
Some errors are missing in GraphErrorCode file

### ISSUE THREAD

**Issue by zsybupt** [microsoftgraph/msgraph-sdk-dotnet#145]
Some errors returned by Graph API are not found in GraphErrorCode enum, such as InvalidAuthenticationToken, the sdk version is latest 1.4.0.0.
Thanks

**Comment by MIchaelMainer** [comment]
@zsybupt thank you for bringing this to our attention. Due to the different potential combinations of errors provided by the underlying services, and since this client library is a light and leaky abstraction of the REST API, I'm inclined to pass through the errors without mapping to GraphErrorCode. Would the lack of mapping to GraphErrorCode cause you any issues? I'd like to hear your thoughts.
