### ISSUE TITLE
Update null or empty strings for mobilePhone/otherEmails or any other attribute using Graph API C#

### ISSUE THREAD

**Issue by sakthi-7699** [microsoftgraph/msgraph-sdk-dotnet#1453]
Hi Team, 

When we try to remove the user's mobilePhone or otherMails by passing an empty string, we are getting the below errors.

Message: The mobilePhone should be between 1 and 64 characters.
Message: The otherMails should be between 1 and 256 characters.

Even passing null value doesn't replace the existing values and I don't want to save " " in the mobilePhone or email. 

I had already raised a question here https://docs.microsoft.com/en-us/answers/questions/964298/not-able-to-update-mobilephone-and-othermails-with.html

Can you please guide on how to resolve this issue. Thanks

**Comment by andrueastman** [comment]
Thanks for raising this @sakthi-7699 

Due to the way the serializer currently works, null values are not emitted by default in the SDK. To send out null values, you can take advantage of the using the additionalData bag as in the example below.

```cs
task.AdditionalData["dueDateTime"] = null;
var todoTask = await client.Me.Todo.Lists[$"{tasklistid}"].Tasks[$"{taskid}"]
                 .Request()
                 .UpdateAsync(task);
```

We are also working on a new version of the SDK that is in preview that should resolve this issue by use of a backing store. This is outlined at the link below. If you're willing to try it out, you can find out more here. 

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md#new-features

**Comment by sakthi-7699** [comment]
Thank you. Using additionalData resolved the issue.

**Comment by andrueastman** [comment]
:
