### ISSUE TITLE
Delta query fails with different error if user doesnt have onedrive enabled

### ISSUE THREAD

**Issue by SangeethaJanakiraman** [microsoftgraph/msgraph-sdk-dotnet#1463]
We are using query "drive/root/delta" to get the delta changes for the user. 

Sometimes , this query returns "User's mysite was not found" 
Other times, this query returns "Call was made to the default drive, which is not supported for apponly tokens"

Why the same query would return 2 different results randomly. Also is it safe to assume that user doesn't have onedrive enabled if either of the above error is returned

**Comment by andrueastman** [comment]
Thanks for raising this @SangeethaJanakiraman 

As this seems to be an issue raised by the API and this repo is intended for issues related to the .NET client library, any chance you can also post the same question at the link below so that we may get accurate feedback from the API owners? 
It would also be great if you could post back the link in this issue so that anyone who comes across it may benefit from it.

https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-files.html
