### ISSUE TITLE
Tenant Change Request

### ISSUE THREAD

**Issue by allw1994** [microsoftgraph/msgraph-sdk-dotnet#1466]
**Is your feature request related to a problem? Please describe.**
Ability to change between tenants, using delegated admin access to partner delegated tenants.
Want to be able to do something like the following:
```
    Private Scopes = New String() {"Scope.Permissions"}
    Private ClientId As String = "AppId"
    Private TenantId As String = "MspTenantId"
    Private Options As New InteractiveBrowserCredentialOptions With {
            .TenantId = TenantId,
            .ClientId = ClientId,
            .AuthorityHost = AzureAuthorityHosts.AzurePublicCloud,
            .RedirectUri = New Uri("http://localhost")
        }
    Private InteractiveCredential = New InteractiveBrowserCredential(Options)
    Private GraphClient As GraphServiceClient = New GraphServiceClient(InteractiveCredential, Scopes)
    //do some stuff
    GraphClient.ChangeTenant("CustomerTenantId")
   //do more stuff in a different tenant
```
Currently you can remake the graphserviceclient every time you want to change tenants but this also forces another user login. Ideally only one prompt for username and password would take place, the rest would use the same credentials as before. Is this even possible? (or otherwise adding a method to change the tenant without prompting constant login).

**Describe the solution you'd like**
Once a graphserviceclient has been intialised, the tenant can be changed. Or the client can be reinitialised with the same user credentials but attached to a different tenant.

**Describe alternatives you've considered**
Have considered using App based login, but user credentials would be useful so we can audit who has done what. Additionally having at least one login prompt means we could limit the app to people in a certain 365 group etc.

(Fully accepting there may not be a way to do this except something like storing credentials in some textboxes and using the username/password provider listed here: https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=CS but it is does not support MFA which is required for CSP accounts)

**Comment by andrueastman** [comment]
Thanks for raising this @allw1994 

The `tenantId` set during the construction of the `InteractiveBrowserCredential` is tied to the instance and used during the initialization of the same. This therefore means that the authentication done by one Tenant may need reauthentication with a new instance of the `InteractiveBrowserCredential` would be needed.

To avoid multiple authentication prompts, you can try to make the user login at least once in the relevant tenants and cache the tokens with the guidance given here, https://docs.microsoft.com/en-us/dotnet/api/azure.identity.tokencachepersistenceoptions?view=azure-dotnet#examples

This means that you can create two `InteractiveBrowserCredential` instances and use them to create multiple AuthProviders.

```cs
            var authProvider = new TokenCredentialAuthProvider(interactiveBrowserCredential1,scopes);
            var authProvider2 = new TokenCredentialAuthProvider(interactiveBrowserCredential2, scopes);
```

Then you can initialize the client with a `PerRequestAuthProvider` as below

```cs
            Func<IAuthenticationProvider> perRequestAuthProvider = () => 
            {
                return tenantID.Equals("XXXX",StringComparison.CurrentCultureIgnoreCase) ? authProvider : authProvider2;
            };
            var graphClient = new GraphServiceClient(interactiveBrowserCredential, scopes)
            {
                PerRequestAuthProvider = perRequestAuthProvider
            };
```
then execute the request as below so that the client will choose the relevant AuthProvider based on the `PerRequestAuthProvider` which chooses based on the tenantId.

```cs
             var user = await graphClient.Me.Request().WithPerRequestAuthProvider().GetAsync();
```

Let us know if this is helpful.
