### ISSUE TITLE
numberofOccurance is always zero

### ISSUE THREAD

**Issue by ultimosparc** [microsoftgraph/msgraph-sdk-dotnet#1471]
**Describe the bug**
I create a series event with 5 instances (daily). The numberofOccurance is always zero. 

**Expected behavior**
numberofOccurance  is 5

![image](https://user-images.githubusercontent.com/15387251/188082550-9d4d3ae3-85f3-40db-9350-fa8461c6f198.png)

**Comment by andrueastman** [comment]
Thanks for raising this @ultimosparc 

As this seems to be API related, any chance you can post the same the issue with details of the API request at the link below so as to get feedback from the relevant API owners? If you can, please post back the link to this issue so that future users may benefit from the answers.

https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-calendar.html

**Comment by ultimosparc** [comment]
https://docs.microsoft.com/en-us/answers/questions/991407/numberofoccurrences-is-zero.html

**Comment by andrueastman** [comment]
Thanks @ultimosparc 

We'll close this for now and re-open in the event anything SDK related is raised.
