### ISSUE TITLE
Batch request for non-GET API must manually set HTTP verb and also content

### ISSUE THREAD

**Issue by liang2zhu1** [microsoftgraph/msgraph-sdk-dotnet#1483]
**Describe the bug**
Using Microsoft Graph .NET client `Batch` request , for individual request that HTTP verb is not GET we can't use the `.Request()` from builder directly but instead must use the request message generated from there and then manually set HTTP verb. 

**To Reproduce**
Public documentation already hinted that, reverse engineering looking into the library it just never handles the VERB but defaulting to GET 
https://docs.microsoft.com/en-us/graph/sdks/batch-requests?tabs=csharp#batches-with-dependent-requests
```cs
// POST requests are handled a bit differently
// The SDK request builders generate GET requests, so
// you must get the HttpRequestMessage and convert to a POST
var jsonEvent = graphClient.HttpProvider.Serializer.SerializeAsJsonContent(newEvent);

var addEventRequest = graphClient.Me.Events.Request().GetHttpRequestMessage();
addEventRequest.Method = HttpMethod.Post;
addEventRequest.Content = jsonEvent;
```
**Expected behavior**
My reading on the public doc hint this is a limitation we probably don't intend to fix but would like to confirm. 
I'd speculate there's an issue already but can't find one so I'm creating this - please help dup it if I missed the existing one. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A 

**Additional context**
N/A

**Comment by andrueastman** [comment]
Thanks for raising this @liang2zhu1 

This is a limitation that was tracked via https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/276 and https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1038. 
Due to the nature of the changes required, this has been fixed in the upcoming major version upgrade of the SDK which are now in preview. 

If you're willing to try it out, you can check out the upgrade guide [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md#batch-requests).

Closing this one for now.
