### ISSUE TITLE
Delta Queries access to @removed {Changed | Deleted}

### ISSUE THREAD

**Issue by eeegs** [microsoftgraph/msgraph-sdk-dotnet#1491]
**Is your feature request related to a problem? Please describe.**

When trying to use the Delta Queries results @removed may be returned in an item as a property to indicate it was deleted.
I see no way to access this via the library.

**Describe the solution you'd like**
Maybe at the DirectoryObject level a deleted status indicator.

`enum DeletedStatus { Active, Changed, Deleted }
`
```
class DirectoryObject
{
...
public DeletedStatus Status { get; set; }
...
}
```

**Describe alternatives you've considered**
Unless I'm missing something, I may have to drop the C# library as I need this feature.

**Additional context**

**Comment by andrueastman** [comment]
Thanks for raising this @eeegs 

As the property comes back in the response, you may be able to check for its presence in the additionalData bag using code similar to this.

```
if (directoryObject.AdditionalData.TryGetValue("@removed", out var removed))
{
    var reasonString = ((JsonElement)removed).TryGetProperty("reason", out var reason) ? reason.GetString() : string.Empty;
}
```

**Comment by eeegs** [comment]
Thanks, I'll give it a go, but given the support for delta queries, I still think it might be better to have first class support for it.

**Comment by eeegs** [comment]
@andrueastman Hi, I don't know what extra feedback to give you.

**Comment by andrueastman** [comment]
Hey @eeegs,

I was looking forward to the feedback from trying out the suggestion with fetching the property from the AdditionalData. 

For context, due to the SDK being automatically generated, the shape of model classes takes a dependency of the API metadata which is found at https://graph.microsoft.com/v1.0/$metadata. As the metadata specifies that the delta will return a collection of `DirectoryObject` the metadata ideally needs also to also specify the `@changed` property or some other signal. 
Some extra work would need to be done on that front to update/transform the metadata for this to be added.

**Comment by andrueastman** [comment]
Gentle ping @eeegs
