### ISSUE TITLE
[Client bug]: Publication property of a DriveItem is always NULL

### ISSUE THREAD

**Issue by SergiyStoyan** [microsoftgraph/msgraph-sdk-dotnet#1534]
**Describe the bug**
The doc states that the Publication property is not is not returned by default.
But then 
`Client.Me.Drive.Items[i.Id].Request().Select("id, publication, permissions, name").GetAsync();`
does not return it either. The same for Permissions.

**To Reproduce**
run this
`var i = await Client.Me.Drive.Items[i.Id].Request().Select("id, publication, permissions, name").GetAsync();`

and check `i.Publication` or `i.Permissions`.

**Expected behavior**
I expect to get Publication or other non-default property somehow.
OK, I can get permissions by running `Client.Me.Drive.Items[i.Id].Permissions.Request().GetAsync();`
but there is no such way for Publication.
How can it be obtained?

**Client version**
Microsoft.Graph 4.45.0
I cannot run the version 5 because of other bugs in it.
The code is .NET Standard 2.0

**Desktop (please complete the following information):**
Windows 10

**Comment by andrueastman** [comment]
Thanks for raising this @SergiyStoyan,

According to the documentation, at the link below, it seems that the property will exist if the item exists in a location that supports actions such as checkin/checkout.

https://learn.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0

![image](https://user-images.githubusercontent.com/6464005/198958930-3c6bf573-4698-44af-84a1-899223dea1cc.png)

Any chance you can confirm from your end that the document is present in such a location? According to this, this may not work with[ OneDrive personal](https://learn.microsoft.com/en-us/answers/questions/574546/is-checkin-checkout-files-supported-by-onedrive-pe.html).

**Comment by SergiyStoyan** [comment]
Thank you for the clarification. It makes sense.

> Any chance you can confirm from your end that the document is present in such a location?

I'm trying to get Publication on a personal OneDrive which, as you suppose, is not supported. 
Putting aside the ridiculous vagueness of the Graph documentation, why not throw an error 'not supported' on calling instead of making one guess what happens there?

Nevertheless, reasoning from this logic, Permissions, if it is supported, must be returned by this:

`var i = await Client.Me.Drive.Items[i.Id].Request().Select("id, publication, permissions, name").GetAsync();`

And it is not, which implies it is not supported. Correct? Then, if it is not, why is it returned by this: 

`Client.Me.Drive.Items[i.Id].Permissions.Request().GetAsync();`

? So, is Permissions supported or not? If it is, then why is it not returned by `Select`?

**Comment by andrueastman** [comment]
Hey @SergiyStoyan,

From the documentation of `driveItem` [here](https://learn.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0#relationships), we see that `Permissions` is not in the properties table but it is in the relationships table.

![image](https://user-images.githubusercontent.com/6464005/199662351-f2b6cfbb-a28b-41e0-9275-7901cd3f3f23.png)

The `select` query parameter is ideally used for properties. As permissions is relationship, you would need to place it in the `expand` clause so that you may receive it in the same response.

```cs
var driveItem = await graphClient.Me.Drive.Items["item-id"]
	.Request()
	.Expand("permissions")
	.Select("id,publication,name")
	.GetAsync();
```

**Comment by SergiyStoyan** [comment]
`Client.Me.Drive.Items[itemId].Request().Expand("permissions").GetAsync();`

gives the Microsoft.Graph.ServiceException: The query specified in the URI is not valid. The property 'permissions' cannot be used in the $expand query option.

**Comment by andrueastman** [comment]
Apologies for this @SergiyStoyan 

Any chance you can confirm if you are testing with personal account? 
From my end it looks like the expand fails when I use a personal account but works for an enterprise one pointing to different support for different account types. 

If you have the same experience, any chance you can raise a request at the link below (and post back the link here so others may find it) so that the relevant API owners may get around to adding support for the publication/permissions queries? 

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform

**Comment by SergiyStoyan** [comment]
@andrueastman 
Yes, I'm using a personal account. So, the Graph lib appears to be oriented to enterprise accounts while the personal accounts are neglected: something works, something does not with no clarification.

Could you please give a hint for `Microsoft.Graph.Permission` object's property `GrantedTo`? It is marked as deprecated and `GrantedToV2` is suggested to be used instead. But an object returned by `Client.Me.Drive.Items[itemId].Permissions.Request().GetAsync();` has `GrantedToV2` empty (while `GrantedTo` is set). How do I get `GrantedToV2`?

Thank you.

**Comment by andrueastman** [comment]
I've posted the query at the link below so that we may get feedback from the API owners on whether this is a known difference between the personal/organizational accounts as this is a query for the API side of things. 

https://learn.microsoft.com/en-us/answers/questions/1079737/inconsistency-between-grantedtov2-and-grantedto-re.html

**Comment by SergiyStoyan** [comment]
Got the answer there:
>grantedToV2 is specific to OneDrive for Business and SharePoint.

Thank you.
(This part of Microsoft production looks very disappointing. Comparing to Google.Apis and its documentation, it is simply a junk.)
