### ISSUE TITLE
Enhancement to Recipient resource type

### ISSUE THREAD

**Issue by LiamWarnes** [microsoftgraph/msgraph-sdk-dotnet#1572]
Hi Graph Team,

This is a request for an enhancement to the Recipient resource type.

https://learn.microsoft.com/en-us/graph/api/resources/recipient?view=graph-rest-1.0

I am currently working on upgrading a service that uses EWS and expands known groups out into the individual recipients within that group, then performs an operation for each individual recipient. With an upcoming deprecation of EWS API, we want to switch all operations to the Graph API.

If possible, **I would like a property added to recipient that indicates whether it is an individual, or a distribution list (i.e. a group)**. Knowing if a recipient is an individual or a group, will allow me to identify which group recipients I need to expand out into individual recipients to perform the operation on.

Thanks

Liam

**Comment by andrueastman** [comment]
Thanks for raising this @LiamWarnes,

As this issue is an API enhancement request and this repository is intended for client library issues, any chance you can post the request at the link below so that the API owners may look into this?

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform

**Comment by LiamWarnes** [comment]
yeah thanks @andrueastman . I wasn't sure where the best location to make such requests was but ill get to requesting over there
