### ISSUE TITLE
[Client bug]: + character is invalid in OrderBy, Filter, etc. starting with version 4.0.0

### ISSUE THREAD

**Issue by g2petter** [microsoftgraph/msgraph-sdk-dotnet#1605]
**Describe the bug**
First of all I want to say that I don't know if this constitutes a bug or a valid breaking change, but it's caused some problems for us and I thought it to be worth raising the issue.

In previous versions of the `Microsoft.Graph` package, up to and including 3.35.0 which is the last version before moving to 4.x, the use of the `+` sign in `OrderBy` and `Filter` similar to what's done when testing in the Graph Explorer was valid. In all versions after 4.0.0 this is no longer the case.

A call with for example `OrderBy("LastModifiedDateTime+desc")` will now result in a `Microsoft.Graph.ServiceException` with the `BadRequest` code and the following message: 

"Syntax error: character '+' is not valid at position 20 in 'LastModifiedDateTime+desc'"

**To Reproduce**
The following simplified example worked in version 3.35.0:

```
var gsc = new GraphServiceClient();
var request = gsc.Me.Messages
    .Request()
    .OrderBy("LastModifiedDateTime+desc")
    .Select("LastModifiedDateTime,Subject");
var response = await request.GetAsync();
```

In 4.0.0 and up the same code will result in the exception described above and shown in the following screenshot: 

![image](https://user-images.githubusercontent.com/5946832/210751966-f3ff6572-1a31-4724-8349-77e324102451.png)

**Expected behavior**
The expected behavior is that this should work as in previous versions.

This is supported by the behavior of the Graph Explorer, where both the following queries are treated the same:
`https://graph.microsoft.com/v1.0/me/messages?$orderby=receivedDateTime+desc`
`https://graph.microsoft.com/v1.0/me/messages?$orderby=receivedDateTime desc`

If you use the Graph Explorer or desktop clients such as Postman to test your queries before implementing them using the SDK, it's easy to copy the query string including the plus into the code, which is how we ended up in the situation where we now have code that needs fixing before upgrading to the most recent package.

I understand if this falls in the "works as intended, won't fix" category, but I thought it was worth raising nonetheless.

**Client version**
4.x

**Comment by andrueastman** [comment]
Thanks for raising this @g2petter,

We won't be making a change for this as this was a [breaking change](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v4.md#query-options-are-now-encoded-by-default) in version 4 due to the unwanted errors caused by other scenarios where characters like `+` could be meaningful in the url query as opposed to being a space character.

Failing to encode characters in the query options would end up blocking scenarios such as https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/700 and https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/914
