### ISSUE TITLE
search via msgraph using custom search schema from a specific sitecollection

### ISSUE THREAD

**Issue by mdissel** [microsoftgraph/msgraph-sdk-dotnet#1640]
How can I specify the site collection that should be used when doing an msgraph search using the custom search schema from a sitecollection

When using the Sharepoint API, you just use /sites/sitecollection1/_api/search, but I can't find a setting how to force the msgraph to use the search schema from a specific site collection.

**Comment by andrueastman** [comment]
Thanks for raising this @mdissel 

As this is an API related question, and this repo is mainly intended for the .NET sdk related issues, any chance you can post your query at the link below to get feedback from the API team?

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph

If you can please post the link of the question as a comment here so that it can be found by anyone else who comes across the same question. Closing this for now and will re-open for any SDK related issue.

**Comment by mdissel** [comment]
Already reported to the API team, but no correct answer yet.
https://learn.microsoft.com/en-us/answers/questions/1168060/search-via-msgraph-using-custom-search-schema-from?page=1
