### ISSUE TITLE
MS Graph Tenant enumeration, subscription enumeration

### ISSUE THREAD

**Issue by xpandax76** [microsoftgraph/msgraph-sdk-dotnet#1644]
Hi,
I am learning Azure and Azure Graph API and have a few questions? 
1. If an organization has multiple Azure AD tenants, is there any ways to enumerate all tenants and return it in Graph API? Or is there any API I should be looking into 
2. Subscriptions from different tenants can be viewed in portal for cost/billing analysis (it might be tied together under the same service agreement?). Is there any way to return this data using Graph API? 

Thank you!

**Comment by andrueastman** [comment]
Thanks for raising this @xpandax76 

As this is an API related question, and this repo is mainly intended for the .NET SDK related issues, any chance you can post your query at the link below to get better guidance from the relevant API teams?

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph

If you can please post the link of the question as a comment here so that it can be found by anyone else who comes across the same question. Closing this for now and will re-open for any SDK related issue.
