### ISSUE TITLE
[Client bug]: v5.4.0 send mail fails for null mail recipients

### ISSUE THREAD

**Issue by matthiasbucher** [microsoftgraph/msgraph-sdk-dotnet#1808]
If the recipients property of a Message is set to null, the send-mail-request will fail.

**Steps to reproduce**
Using the example from the [documentation](https://learn.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=csharp), but setting the CcRecipients property to `null`

```
var requestBody = new SendMailPostRequestBody
{
    Message = new Message
    {
        Subject = "Meet for lunch?",
        Body = new ItemBody
        {
            ContentType = BodyType.Text,
            Content = "The new cafeteria is open.",
        },
        ToRecipients = new List<Recipient>
        {
            new Recipient
            {
                EmailAddress = new EmailAddress
                {
                    Address = "matthias.bucher@zuehlke.com",
                },
            },
        },
        CcRecipients = null
    },
    SaveToSentItems = false,
};
```
This request will consequently fail with a bad request (not all recipients valid)
`await client.Users[_userId].SendMail.PostAsync(requestBody);`

The reason is that in that case `null` gets serialized into the request, which the API rejects.
Workaround: do not call the CcRecipients-setter when not having any cc-recipients.

**Expected behavior**
The request should succeed, when initializing the Recipients properties with null.

**Client version**
5.4.0

**Comment by andrueastman** [comment]
Thanks for raising this @matthiasbucher 

As mentioned, setting a property to null is a supported scenario as there are scenarios where setting a property to null and have the property sent over the wire is valid  due to the working of the [backing store](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#backing-store).

- https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1180 
- https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/264

This mean that if one need not send the property over the wire as null, it shouldn't be explicitly set to null and left to its default. Hopefully this clears things up.
