### ISSUE TITLE
What is the right way to implement a schema extension with Backingstore support?

### ISSUE THREAD

**Issue by plamber** [microsoftgraph/msgraph-sdk-dotnet#1812]
**Is your feature request related to a problem? Please describe.**
We are using schema extensions to extend our AAD objects (https://learn.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-1.0). We are looking for a way to achieve these goals:

- Extend the AAD object with our schema extension and BackingStore. e.g.
```
public class MyAADUser: User
{
    public MyUserExtension? Schema
    {
        get { return BackingStore?.Get<MyUserExtension?>("myUserExtension"); }
        set { BackingStore?.Set("myUserExtension", value); }
    }
}

public class MyUserExtension {
    [JsonPropertyName("property1")]
    public String? Property1 { get; set; }
}
```
- Use the get, post, patch operations to interact with this object
How do I cast the object properly to work with get, post, and patch?

Thank you,
Patrick

**Comment by andrueastman** [comment]
Thanks for raising this @plamber 

To do this, you would ideally need to have your custom model implement the three interfaces.

- IParsable - this is the most important and requires you to define two functions in your model for serialization [GetFieldDeserializers](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/35219edc55a60ba072c314a3fea95f915938d457/src/Microsoft.Graph/Generated/Models/Identity.cs#L91) and [Serialize](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/35219edc55a60ba072c314a3fea95f915938d457/src/Microsoft.Graph/Generated/Models/Identity.cs#L102). You can take a look at [this model](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/35219edc55a60ba072c314a3fea95f915938d457/src/Microsoft.Graph/Generated/Models/Identity.cs#L8) for example. If you are deriving from another model class, remember to call the base method( e.g `base. Serialize()`) in the implementation so that the base properties are also serialized/deserialized.  
- IAdditionalDataHolder - This would be optional if you are sure of the properties that you will use and enables you to work with extra properties that may not be defined during serialization/deserialization.
- IBackedModel - This is also optional and enables the backing Store support. To use this, you would need to have a backing store property and initialize it on model creation (example [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/src/Microsoft.Graph/Generated/Models/Identity.cs#L62)), your properties would then be accessed from the backing store as opposed to them being defined themselves. 

With this, you should be able to use the custom model as needed.

**Comment by andrueastman** [comment]
Hey @plamber 

As the model will be defined, you would also need to add a factory method to your custom class (like [this](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/b7887dce8cebd7c6f658d83e5705b2634d6d1ac2/src/Microsoft.Graph/Generated/Models/User.cs#L1572)) to include your custom model in deserialization.

```cs
        public static new MyAADUser CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new MyAADUser();
        }
```

As you will be receiving a collection of users, you can define a model like [this](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/b7887dce8cebd7c6f658d83e5705b2634d6d1ac2/src/Microsoft.Graph/Generated/Models/UserCollectionResponse.cs#L35) where you will pass your factory method.

Fetching users will therefore be done as below

```cs
        var requestInformation = graphClient.Users.ToGetRequestInformation();
        var userCollection = await graphClient.RequestAdapter.SendAsync<CustomUserCollection>(requestInformation);
```

**Comment by plamber** [comment]
Hi @andrueastman,
I came to this implementation. I might still require some help from your end.

Extended user object
```
public class ExtendedUser : User, IParsable
{
    public ExtendedUser() : base()
    {
        OdataType = "#microsoft.graph.user";
    }

    [JsonPropertyName("schema_extension")]
    public UserSchemaExtension? SchemaExtension
    {
        get { return BackingStore?.Get<UserSchemaExtension?>("schema_extension"); }
        set { BackingStore?.Set("schema_extension", value); }
    }

    public static new ExtendedUser CreateFromDiscriminatorValue(IParseNode parseNode)
    {
        _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
        return new ExtendedUser();
    }

    public new IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
    {
        return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers()) {
            {"schema_extension", n => { SchemaExtension = n.GetObjectValue(UserSchemaExtension.CreateFromDiscriminatorValue); } },
        };
    }

    public new void Serialize(ISerializationWriter writer)
    {
        _ = writer ?? throw new ArgumentNullException(nameof(writer));
        base.Serialize(writer);
        writer.WriteObjectValue("schema_extension", SchemaExtension);
    }
}
```

Schema Extension
```
public class UserSchemaExtension : Entity, IParsable
{
    public string? Filter1
    {
        get { return BackingStore?.Get<string?>("filter1"); }
        set { BackingStore?.Set("filter1", value); }
    }

    /// <summary>
    /// Creates a new instance of the appropriate class based on discriminator value
    /// </summary>
    /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
    public static new UserSchemaExtension CreateFromDiscriminatorValue(IParseNode parseNode)
    {
        _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
        return new UserSchemaExtension();
    }

    /// <summary>
    /// The deserialization information for the current model
    /// </summary>
    public new IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
    {
        return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers()) {
            {"filter1", n => { Filter1 = n.GetStringValue(); } },
        };
    }

    /// <summary>
    /// Serializes information the current object
    /// </summary>
    /// <param name="writer">Serialization writer to use to serialize this model</param>
    public new void Serialize(ISerializationWriter writer)
    {
        _ = writer ?? throw new ArgumentNullException(nameof(writer));
        base.Serialize(writer);
        writer.WriteStringValue("filter1", Filter1);
    }
}
```

Retrieving a single user:
```
var errorMapping = new Dictionary<string, ParsableFactory<IParsable>> {
        {"4XX", ODataError.CreateFromDiscriminatorValue},
        {"5XX", ODataError.CreateFromDiscriminatorValue},
    };
  var requestInformation = graphClient.Users[userId].ToGetRequestInformation(requestConfiguration =>
  {
      requestConfiguration.QueryParameters.Select = "id,schema_extension";
      requestConfiguration.QueryParameters.Expand = new string[] { "extensions($filter=id eq 'schema_extension')" };
  });

return await graphClient.RequestAdapter.SendAsync<ExtendedUser>(requestInformation, EasyLifeUser.CreateFromDiscriminatorValue, errorMapping);
```

I haven't tried the get list yet. But I think I can figure it out.

Could you suggest me how to create a patch operation for the above schema?

Thank you for your help

**Comment by plamber** [comment]
Thank you @andrueastman.

Not sure why I missed that. 

I was able to perform crud operations.

Thank you for your help
