### ISSUE TITLE
Question: Wait for a request to be actually completed in Azure AD

### ISSUE THREAD

**Issue by chassq** [microsoftgraph/msgraph-sdk-dotnet#1824]
**Describe the Question**
Is there a way to wait for a Group to be actually created before moving on to create a next group, for example?

**Example**
```
var newGroup = new Group
{
   DisplayName = "GroupName",
   Description = "GroupDescription",
   MailEnabled = false,
   MailNickname = "GroupMailNickname",
   SecurityEnabled = true,
};

var graphClient = GetServiceClient(); //Helper Method to get GraphClient

var result = await graphClient.Groups
                               .PostAsync(newGroup, cancellationToken: cancellationToken)
```

Is there to tell the request to wait until the Group has been added into Azure AD so it can be queried. What we see is if we add Groups quickly and then get a list of the groups some of them are not in the list. Any docs on this anywhere?

**Comment by andrueastman** [comment]
Thanks for raising this @chassq 

As this is an API related question and not fully dependent on the working of the SDK(and this repo is mainly intended for SDK related issues), any chance you can post the same query at the link below for the relevant API owners to follow up?
It would be great if you could post back the link here as well so that anyone else who comes across this may also find it. 

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph

**Comment by chassq** [comment]
Thanks! Here is the question link as requested:

https://learn.microsoft.com/en-us/answers/questions/1244296/question-wait-for-a-request-to-be-actually-complet?sharingId=9BBBD256505BD542

**Comment by andrueastman** [comment]
Thanks @chassq 

We'll close this for now and follow up in case anything SDK related is raised.
