### ISSUE TITLE
OneNote API missing @odata.nextLink

### ISSUE THREAD

**Issue by mrvogiacu** [microsoftgraph/msgraph-sdk-dotnet#1841]
As the screenshot below, the @odata.nextLink. I have a total of 3 notebooks, and I use $top = 2. This is changed by the plan or a bug.
![image](https://user-images.githubusercontent.com/14990781/233107699-dd03bfdb-8d1b-4f16-a6bf-49ee06940a96.png)

**Comment by andrueastman** [comment]
Thanks for raising this @mrvogiacu 

As this is an API related query and this repo is meant for SDK realted issues, any chance you can post the query at the link below to get confirmation at the link below that this is expected API behaviour. If you can, please post the link of the query back in this issue so that in future others may also find the response. 

https://learn.microsoft.com/en-us/answers/tags/239/microsoft-graph-notes-api

**Comment by andrueastman** [comment]
Thanks for this @mrvogiacu.
Any reason we should keep this open with the response from the API side?
