### ISSUE TITLE
Teams group chat creation randomly drops some members

### ISSUE THREAD

**Issue by andrekiba** [microsoftgraph/msgraph-sdk-dotnet#1849]
**Describe the bug**
Using [this](https://learn.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-1.0&tabs=csharp#request-1) to create a Teams group chat, what happens is that "randomly" some (1 or more) users are dropped. The chat is always created without errors but with missing users. I don't think that the problem is the set of users because with the same set sometimes it works, sometimes someone is dropped.

**To Reproduce**
Try to create a group chat with some members (3-4 or more), all users are present in Azure AD (not guests) and they are added as owners.

**Expected behavior**
The group chat must be created with all members.

**Client version**
Tested with 4.34.0 and 5.7.0

**Additional context**
Seems that this error started to appear more or less one/two weeks ago

**Comment by andrueastman** [comment]
Thanks for raising this @andrekiba 

Just to confirm, does the API endpoint returns an error in these cases?

**Comment by andrekiba** [comment]
@andrueastman as said no errors, but I'm not sure to understand your request: do you mean trying to call directly the rest graph api with a plain http call?

**Comment by andrueastman** [comment]
@andrekiba I meant if the API throws an error and returns an API error response. 

To validate this, any chance you able to replicate this using the [Graph explorer](https://aka.ms/ge)?
When this occurs are able to share the list of response headers(2 tab at the bottom) so that we may forward to the API team for investigation?

**Comment by andrekiba** [comment]
@andrueastman there are no errors, always 201 created.
Yesterday I shared a Fiddler trance that reproduces the problem with @gabrielnovoa (support escalation engineer for the support ticket we have opened with Microsoft).
Can you please try to coordinate to solve this problem?
Thanks.

**Comment by anto88git** [comment]
Dear All,
In our company, we are facing the same problem. We use .net 6, and Microsoft.Graph 4.54.0 SDK.

We build an enterprise application for our customer. But sometimes when they try to open a group chat with 3 to 5 members, not all the members are added. Anyway the response don't return any error, and the chat is successfully created. 
The problem is not related to the involved users, because the same users are correctly added in further created chats.

Below the code used to create the chat:
`public override async Task<string> CreateChat(string[] members, string topic)
        {
            if (this.graphServiceClient == null)
                throw new Exception("GraphServiceClient not initialized!");


            try
            {
                this.logger.LogInformation($"CreateChat start, topic: {topic}...");

                var chat = new Chat();
                chat.ChatType = ChatType.Group;
                chat.Topic = topic;

                var roles = new List<String>();
                roles.Add("owner");

                var chatMembers = new ChatMembersCollectionPage();
                var chatOwner = new AadUserConversationMember();
                chatOwner.Roles = roles;
                chatOwner.AdditionalData = new Dictionary<string, object>()
                                            {
                                                {"user@odata.bind", "https://graph.microsoft.com/v1.0/users('" + this.Settings.UserEmail + "')"}
                                            };

                chatMembers.Add(chatOwner);

                foreach (var member in members)
                {
                    this.logger.LogDebug($"Addin member: <{member}>.");
                    var chatMember = new AadUserConversationMember();
                    chatMember.Roles = roles;
                    chatMember.AdditionalData = new Dictionary<string, object>()
                                            {
                                                {"user@odata.bind", "https://graph.microsoft.com/v1.0/users('" + member + "')"}
                                            };

                    chatMembers.Add(chatMember);
                }

                chat.Members = chatMembers;

                this.logger.LogDebug($"CreateChat request: {JsonConvert.SerializeObject(chat)}");
                //var result = await graphServiceClient.Chats.Request().AddAsync(chat);
                var result = await Policy.Handle<ServiceException>(ex => ex.StatusCode == 0)
                        .WaitAndRetryAsync(5, retryAttempt => TimeSpan.FromSeconds(Math.Pow(2, retryAttempt)),
                            (exception, retryCount) =>
                            {
                                this.logger.LogWarning($"Failed to executing CreateChat, error: {exception.Message}, retryCount: {retryCount}");
                            })
                        .ExecuteAsync(() => graphServiceClient.Chats.Request().AddAsync(chat));

                this.logger.LogDebug($"CreateChat success, topic: {topic}, chat.id: {result.Id}, result: {JsonConvert.SerializeObject(result)}.");

                return result.Id;
            }
            catch (ServiceException ex)
            {
                this.logger.LogError("Error in CreateChat, error: {0}", ex.ToString());
                throw;
            }
        }`

We had to implement Polly because of others varius random errors that some times we receive. But in this specific case we don't receive any error.

Following a real case of chat request that our customer sent few days ago. Maybe you can chat the specific case on your server side.

Below the JSON serialization of the "chat" object that we sent, I will just blank the emails for privacy reasons:
{
   "ChatType":1,
   "CreatedDateTime":null,
   "LastUpdatedDateTime":null,
   "OnlineMeetingInfo":null,
   "TenantId":null,
   "Topic":"Andon call - Máquina = L672; Tipo de problema = Supervisor; Fecha = 14/06/2023 07.33.49",
   "Viewpoint":null,
   "WebUrl":null,
   "InstalledApps":null,
   "InstalledAppsNextLink":null,
   "LastMessagePreview":null,
   "Members":[
      {
         "Email":null,
         "TenantId":null,
         "UserId":null,
         "User":null,
         "DisplayName":null,
         "Roles":[
            "owner"
         ],
         "VisibleHistoryStartDateTime":null,
         "Id":null,
         "ODataType":"microsoft.graph.aadUserConversationMember",
         "AdditionalData":{
            "[user@odata.bind](mailto:user@odata.bind)":"https://graph.microsoft.com/v1.0/users('JUxxxxxx-BOT@maxxxxx.com')"
         }
      },
      {
         "Email":null,
         "TenantId":null,
         "UserId":null,
         "User":null,
         "DisplayName":null,
         "Roles":[
            "owner"
         ],
         "VisibleHistoryStartDateTime":null,
         "Id":null,
         "ODataType":"microsoft.graph.aadUserConversationMember",
         "AdditionalData":{
            "[user@odata.bind](mailto:user@odata.bind)":"https://graph.microsoft.com/v1.0/users('thxxxx.xxxxxx@maxxxxx.com')"
         }
      },
      {
         "Email":null,
         "TenantId":null,
         "UserId":null,
         "User":null,
         "DisplayName":null,
         "Roles":[
            "owner"
         ],
         "VisibleHistoryStartDateTime":null,
         "Id":null,
         "ODataType":"microsoft.graph.aadUserConversationMember",
         "AdditionalData":{
            "[user@odata.bind](mailto:user@odata.bind)":"https://graph.microsoft.com/v1.0/users('luxx.xxxxxx@maxxxxx.com')"
         }
      },
      {
         "Email":null,
         "TenantId":null,
         "UserId":null,
         "User":null,
         "DisplayName":null,
        "Roles":[
            "owner"
         ],
         "VisibleHistoryStartDateTime":null,
         "Id":null,
         "ODataType":"microsoft.graph.aadUserConversationMember",
         "AdditionalData":{
            "[user@odata.bind](mailto:user@odata.bind)":"https://graph.microsoft.com/v1.0/users('maxxxxxxxxx.xxxxx@maxxxxx.com')"
         }
      },
      {
         "Email":null,
         "TenantId":null,
         "UserId":null,
         "User":null,
         "DisplayName":null,
         "Roles":[
            "owner"
         ],
         "VisibleHistoryStartDateTime":null,
         "Id":null,
         "ODataType":"microsoft.graph.aadUserConversationMember",
         "AdditionalData":{
            "[user@odata.bind](mailto:user@odata.bind)":"https://graph.microsoft.com/v1.0/users('fexxxx.xxxxx@marxxx.com')"
         }
      }
   ],
   "MembersNextLink":null,
   "Messages":null,
   "MessagesNextLink":null,
   "PinnedMessages":null,
   "PinnedMessagesNextLink":null,
   "Tabs":null,
   "TabsNextLink":null,
   "Id":null,
   "ODataType":null,
   "AdditionalData":null
}

In this specific case, the result, serialized in JSON, was the following one:

{
   "ChatType":1,
   "CreatedDateTime":"2023-06-14T13:33:55.915+00:00",
   "LastUpdatedDateTime":"2023-06-14T13:33:55.915+00:00",
   "OnlineMeetingInfo":null,
   "TenantId":"a6a681e0-1c24-46eb-a657-e25259ad9536",
   "Topic":"Andon call - Máquina = L672; Tipo de problema = Supervisor; Fecha = 14/06/2023 07.33.49",
   "Viewpoint":null,
   "WebUrl":"https://teams.microsoft.com/l/chat/19%3A3ffe12905ab345ce948ccdda1eb8ec46%40thread.v2/0?tenantId=a6a681e0-1c24-46eb-a657-e25259ad9536",
   "InstalledApps":null,
   "InstalledAppsNextLink":null,
   "LastMessagePreview":null,
   "Members":null,
   "MembersNextLink":null,
   "Messages":null,
   "MessagesNextLink":null,
   "PinnedMessages":null,
   "PinnedMessagesNextLink":null,
   "Tabs":null,
   "TabsNextLink":null,
   "Id":"19:3ffe12905ab345ce948ccdda1eb8ec46@thread.v2",
   "ODataType":null,
   "AdditionalData":{
      "@odata.context":{
         "ValueKind":3
      }
   }
}

so the chat was successfully created, but despite of there were 5 users in the request, only 4 users has been added to the chat.
The last user in the array: fexxxx.xxxxx@marxxx.com, don't appears in the chat.

As mentioned before, the same user have been added to many other chats successfully. And the problem happens very often and with any user.

Please give some priority to this ticket, and ask for any further detail that can be usefull for the problem resolution.
thank you and best regards.
