### ISSUE TITLE
Got "The server committed a protocol violation" when deleting/getting message via SDK

### ISSUE THREAD

**Issue by seedtyx** [microsoftgraph/msgraph-sdk-dotnet#1872]
**Describe the bug**
exception : Code: generalException\nMessage: An error occurred sending the request.\n --> An error occurred while sending the request. --> The server committed a protocol violation. Section=ResponseStatusLine

**To Reproduce**
The error happened in ```graphClient.Me.MailFolders.Inbox.Messages[messageId].Request().DeleteAsync()```.
And actually I can not reproduce this locally, but my client reported this.

Below is my local request for deleting.
```
DELETE https://graph.microsoft.com/v1.0/me/mailFolders/Inbox/messages/{messageId} HTTP/1.1
SdkVersion: Graph-dotnet-2.0.8
FeatureFlag: 0000004F
Cache-Control: no-store, no-cache
Authorization: bearer eyXXXX
Accept-Encoding: gzip
Host: graph.microsoft.com
Content-Length: 0
Connection: Keep-Alive
```

**Expected behavior**
I would appreciate any clue/potential cause of this error so I can check and find the real cause in my case.

**Client version**
 Microsoft.Graph (4.29.0)
 Microsoft.Graph.Core (2.0.8)

**Comment by andrueastman** [comment]
Thanks for raising this @seedtyx 

Just to confirm, is this happening for all delete requests to this endpoint? Are you by any chance able to log/trace the server response in this scenario?

**Comment by andrueastman** [comment]
Out of curiosity, are you sending a large number of message deletions sequentially at a time? 

We had a similar issue reported in [this issue](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1837) where the server was also returning invalid HTTP response when doing multiple deletes sequentially but the user switched to message batching to resolve. 

https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1837#issuecomment-1525056103

Otherwise, It would be great if we could get access to a trace of the same.

**Comment by seedtyx** [comment]
Thanks for your information.
Looks a little bit similar, but is deleting 5 emails per minute a little bit frequent?
I'm trying to collect the trace and will provide it once available.

**Comment by seedtyx** [comment]
> 

Thank you so much for your information. Yes, I'll try to do both. Add log on client side and ask my client to trace the HTTP requests/responses, but they are used to using wireshark. And will provide all the information once available.
