### ISSUE TITLE
Presence through user/{UserPrincipalName}/presence

### ISSUE THREAD

**Issue by codewerfer** [microsoftgraph/msgraph-sdk-dotnet#1942]
**Is your feature request related to a problem? Please describe.**
Most routes starting with `/users/{...}/...` allow _id_ or _UserPrincipalName_ to acces the response object.
Like `calendar`, `events`, `drive` and so on. Even `/users/{UserPrincipalName}/teamwork/installedApps` is allowed.

But `presence` must have _id_ and doesn't work with _UserPrincipalName_. This seams inconsistent to me.

**Describe the solution you'd like**
Get access through `/users/{id or UserPrincipalName}/presence`.

``` C#
var graphClient = new GraphServiceClient(requestAdapter);

var result = await graphClient.Users["{UserPrincipalName}"].Presence.GetAsync();
```

**Comment by andrueastman** [comment]
Thanks for raising this @codewerfer 

As this functionality is API related and this repo is intended for SDK issues, could you please create a feature request for the same at the link below for the API owners to follow up? 

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform

It would be great if you can post back a link for the same in the issues so that anyone who comes across this may also upvote the request as well.

**Comment by codewerfer** [comment]
As suggested, Feature Request:

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/graph-api-presence-through-user-userprincipalname-presence/idi-p/3839754#M1789

Please upvote, if you run also into this inconsistency.

**Comment by andrueastman** [comment]
We'll close this here for now as this is now raised to be implemented on the API end.
