### ISSUE TITLE
[Client bug]: Can not upload an application logo in AAD - Content-Type issue.

### ISSUE THREAD

**Issue by edouardpoitras** [microsoftgraph/msgraph-sdk-dotnet#1951]
**Describe the bug**
I can't seem to be able to get the upload application logo functionality working.

See the code in "Additional context" section.

No matter what I put in for the "Content-Type" header, I always get the following error:
`Content-Type was application/octet-stream, image/png. Image Content-Type header should be one of the following: [image/bmp, image/emf, image/wmf, image/jpg, image/jpeg, image/gif, image/ico, image/png, image/exif, image/tif, image/tiff, image/*, images/*]`

If I don't manipulate the lrb (LogoRequestBuilderPutRequestConfiguration) object at all, then I get the same error except that the `Content-Type was application/octet-stream, image/png.` bit just states `Content-Type was application/octet-stream.` instead (without the `image/png`). So it looks like no matter what I do to the lrb object, the `application/octet-stream` is always added to the `Content-Type` headers.

**To Reproduce**
1. Ensure you have an application in your AAD.
2. Run the code in the "Additional context" section (fill in valid values for id, imageData, and imageType.
3. Observe results.

**Expected behavior**
The request should succeed and the application in AAD should now have the uploaded logo as it's main image.

**Screenshots**
N/A

**Client version**
Microsoft.Graph 5.8.0

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: N/A
 - Version: N/A

**Additional context**
Here's the code I'm trying with:
```
var id = <application-id>;
Stream imageData = <get-logo.png-as-stream>;
var imageType = "image/png";
await _client.Applications[id].Logo.PutAsync(imageData, (lrb) =>
{
    lrb.Headers.Clear();
    lrb.Headers.Add("Content-Type", imageType);
});
```

**Comment by andrueastman** [comment]
> Does `requestInfo.SetStreamContent(body);` add the `application/octet-stream` header?

Yes it does. 

https://github.com/microsoft/kiota-abstractions-dotnet/blob/efd1326f98aa8cbeb2d9bf45cd377713add4dce9/src/RequestInformation.cs#L192

I believe we may need need an exclusion list in the so that whenever the Content-Type header is added, it replaces the value instead of keeping both. 

https://github.com/microsoft/kiota-abstractions-dotnet/blob/efd1326f98aa8cbeb2d9bf45cd377713add4dce9/src/RequestHeaders.cs#L23

Any chance that's something you could create a PR for @edouardpoitras ?

**Comment by edouardpoitras** [comment]
@andrueastman Not entirely sure this is what you meant, but here's my interpretation: https://github.com/microsoft/kiota-abstractions-dotnet/pull/93

**Comment by andrueastman** [comment]
Referring to the generated code, 
`requestInfo.SetStreamContent(body);` is called first before `lrb.Headers.Add("Content-Type", imageType);` is called. Due to the current implementation both headers will be added in a comma separated fashion and thus why the error log lists both.

Check your original issue, it has both headers as `application/octet-stream, image/png`.

`Content-Type was application/octet-stream, image/png.`

Therefore a replacement of the original is what we want to only have `image/png`

**Comment by edouardpoitras** [comment]
Gotcha, I was mistaken. Thanks.

**Comment by serverskyAS** [comment]
Just wanted to let you know that the same error is in the Microsoft.Graph powershell module.
