### ISSUE TITLE
Graph 5.x Download large file over 2GB have issue

### ISSUE THREAD

**Issue by dev-tony-hu** [microsoftgraph/msgraph-sdk-dotnet#1954]
**Describe the bug**
Graph 5.x Download large file over 2GB have issue
When I trying to use graph DriveItem/Content to download  large file content, I see the error below.

  System.Net.Http.HttpRequestException: Cannot write more bytes to the buffer than the configured maximum buffer size: 2147483647.
  Stack Trace: 
HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
HttpClientRequestAdapter.GetHttpResponseMessage(RequestInformation requestInfo, CancellationToken cancellationToken, Activity activityForAttributes, String claims)
HttpClientRequestAdapter.SendPrimitiveAsync[ModelType](RequestInformation requestInfo, Dictionary`2 errorMapping, CancellationToken cancellationToken)
ContentRequestBuilder.GetAsync(Action`1 requestConfiguration, CancellationToken cancellationToken)
GraphDriveService.DownloadFileByIdAsync(String driveId, String driveItemId, RangeHeaderValue range, String eTag, CancellationToken cancellationToken) line 59
GraphDriveService.DownloadFileByIdAsync(String driveId, String driveItemId, CancellationToken cancellationToken) line 31
GraphDriveServiceTests.DownloadFileTest3() line 87
ThreadOperations.ExecuteWithAbortSafety(Action action)

**To Reproduce**
Use Graph SDK to download  drive file over 2GB

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by NickDarvey** [comment]
@dev-tony-hu, I think the developers on this repo are going to say to use the ['download a large file from OneDrive' method](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/ccf3421574cf53c8f7282e3ee48ac4ea3bba993e/docs/readme.md#download-a-large-file-from-onedrive).

I'm guessing you're receiving this error because the underlying [HttpClient is sending the request](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.sendasync?view=net-7.0#system-net-http-httpclient-sendasync(system-net-http-httprequestmessage-system-threading-cancellationtoken)) with the default parameter of `HttpCompletionOptions.ResponseContentRead` meaning the entire response is buffered. I don't believe there is a way to override this so you'd need to drop back to using HttpClient directly.

See also:
- https://stackoverflow.com/a/18720862/1259408
- https://www.stevejgordon.co.uk/using-httpcompletionoption-responseheadersread-to-improve-httpclient-performance-dotnet

**Comment by Dethras** [comment]
@andrueastman - Do you have an estimate in which version will this fix be released in?

**Comment by 23W** [comment]
It seems the bug is fixed, right?
