### ISSUE TITLE
[Client bug]: Cannot create OrganizationalBrandingLocalization

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/msgraph-sdk-dotnet#1973]
**Describe the bug**
When creating a new `OrganizationalBrandingLocalization`

    var body = new OrganizationalBrandingLocalization
                {
                    Id = "en-us",
                    BackgroundColor = "..",
                    UsernameHintText = "..",
                    CustomForgotMyPasswordText = "..",
                    CustomTermsOfUseText = "..",
                    CustomTermsOfUseUrl = "..",
                    CustomPrivacyAndCookiesText = "..",
                    CustomPrivacyAndCookiesUrl = "..",
                    CustomCannotAccessYourAccountText = "..",
                    CustomCannotAccessYourAccountUrl = "..",
                    CustomResetItNowText = "..",
                    CustomAccountResetCredentialsUrl = ".."
                };
    await _client.Organization[organizationId].Branding.Localizations.PostAsync(body);

It throws the exception with the error message

> Expected property 'customAccountResetCredentialsUrl' is not present on resource of type 'OrganizationalBrandingLocalization'.

Looks like `custom*` properties are not available in v1.0.

Could you please confirm whether it is possible to set `custom*` properties in v1.0?

**To Reproduce**
1. See the code above

**Expected behavior**

**Screenshots**

**Client version**
5.14

**Desktop (please complete the following information):**

**Additional context**

**Comment by andrueastman** [comment]
Thanks for raising this @MartinM85 

As the property does indeed in the metadata, ideally, this should work out on posting the property. 
As this is specific to the API behavior, any chance you can post the question at the link below with the appropriate tag to get feedback from the API owners on whether this is working in V1.0? It would be great if you could post a link of the same back here as a comment so that anyone who comes across this may find it too.

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph

**Comment by MartinM85** [comment]
@andrueastman According [this](https://github.com/microsoftgraph/microsoft-graph-docs/issues/21692#issuecomment-1597259416), those properties are not yet available in v1.0.
