### ISSUE TITLE
Create calendar event location declined

### ISSUE THREAD

**Issue by davidhendrickmb** [microsoftgraph/msgraph-sdk-dotnet#2001]
Hi,

I am creating a calendar event with a location (room) defined and included as an attendee of type resource.
When there is no BookInPolicy on the room, the booking goes through fine. 
When there is a BookInPolicy, the event is created on the users calendar however the location (room) automatically rejects the event. I can't see anything in the response that would notify me to this.
Is there a way I can see this in the response or any data on the room that would tell me how to access this to know it can't be booked by the user in question?

Thanks,
David

**Comment by andrueastman** [comment]
Thanks for raising this @davidhendrickmb 

As this really is an API related question and this repo is mainly intended for SDK related issues, any chance you can post the question at the link below so that you may get feedback from the API owners? If you could also post back the link to the created issues as a comment, that would also help anyone in future who comes accross this and has a similar question .

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph

**Comment by davidhendrickmb** [comment]
Thanks @andrueastman 
I have raised the question here:
[(https://learn.microsoft.com/en-us/answers/questions/1326291/create-calendar-event-location-declined)]
