### ISSUE TITLE
Url length calc error when upload file by creating an upload session

### ISSUE THREAD

**Issue by lijingwei233** [microsoftgraph/msgraph-sdk-dotnet#2018]
**Describe the bug**
When uploading a file with an upload session, the session will create a temp file named ~tmp{two digits hash}_{originFileName}.{ext} .
And the path of length will contain the part of temp file name, so i can only upload a file with length or path max to 393.

**Screenshots**
![企业微信截图_16891510726928](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/28803983/e5549b92-be3b-4bcf-88fe-50fed1a03e98)

**Comment by andrueastman** [comment]
Thanks for raising this @lijingwei233,

To clarify, is the limitation described here due to the length of the URL or an error is returned from the API?
Any chance you can share examples of how the upload session is created? Is the path part of url?

**Comment by lijingwei233** [comment]
Sure,

The error is returned from the API.
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/28803983/014d8022-fd0f-431f-851f-537b3f34f703)

If I upload the same file without creating a session to the same location, will success.
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/28803983/3ef71d0f-1c55-4efa-a774-faf7c5503dcd)

**Comment by andrueastman** [comment]
Thanks for following up @lijingwei233 

As this is an API related issue, and this repo is mainly intended for SDK related issues,  any chance you could post the same question at the link below so that we may get relevant feedback from the specific API team? It would be great if you could also post the link to the created question here so that anyone else may also find this in future. 

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph

**Comment by lijingwei233** [comment]
There is the question link, thanks for your help.
