### ISSUE TITLE
Change of conversationthread post gives OData error

### ISSUE THREAD

**Issue by Illeris** [microsoftgraph/msgraph-sdk-dotnet#207]
Code:
`var res = await mGraphClient.Groups[groupId].Threads[threadId].Posts[p.Id].Request().Header("If-Match", p.GetEtag()).Header("Prefer", "return=representation").UpdateAsync(p);`

Exception:
---------------------------
Something went wrong
---------------------------
Code: ErrorInvalidRequest
Message: The OData request is not supported.
Inner error
---------------------------
OK   
---------------------------

How can an existing post be updated (fix error in text) ?

**Comment by MIchaelMainer** [comment]
I'm not seeing a PATCH operation in the [Graph documentation for posts](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/post). Along with the error response, this doesn't appear to be supported. The reason why you see this _update_ functionality in the client library is because this library is autogenerated and we don't have a reliable mechanism to determine which CRUD ops are supported. 

I'll close this issue. If you have more questions or issues with the Graph service API, please post to StackOverflow using the microsoftgraph tag.
