### ISSUE TITLE
Override Message property of ODataError to show error code and error message

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/msgraph-sdk-dotnet#2094]
Since SDK v5 has been released I see on StackOverflow and Microsoft Q&A that many developers are confused about `ODataError`.

When the Graph API service returns the `ODataError` error and the `Message` property displays text **Exception of type 'Microsoft.Graph.Models.ODataErrors.ODataError' was thrown**. This description is useless for the developers.

The message should show at least the error code and the error message.

**Describe the solution you'd like**
I would suggest to generate overriden `Message` property of the `ODataError`

```
public class ODataError : ApiException, IAdditionalDataHolder, IBackedModel, IParsable
{
    ...
    public override string Message => $"{Error?.Code}:{Error?.Message}";
    ...
}
```

**Describe alternatives you've considered**
Another alternative was to override `ToString` method

**Additional context**

**Comment by macwier** [comment]
How does the PR fix this issue? 

I still see e.g. `The server returned an unexpected status code and no error factory is registered for this code: 400` without seeing the body of the error in the exception. 
Or was this not supposed to fix  and i should create separate issue?

**Comment by andrueastman** [comment]
Any chance you can share the sample code when the error is thrown @macwier ?

**Comment by macwier** [comment]
```c#
            var users = new List<User>();

            var response = await GraphServiceClient.Groups[groupId].TransitiveMembers
                .GraphUser
                .GetAsync(x => x.QueryParameters.Select = new[]
                    { "id", "displayName", "mail", "otherMails", "userPrincipalName", "accountEnabled", "proxyAddresses", "officeLocation" });
            var pageIterator = PageIterator<User, UserCollectionResponse>.CreatePageIterator(
                GraphServiceClient, response, (user) => { users.Add(user); return true; });
            await pageIterator.IterateAsync();

            return users;
```

The problem is that this happens only for one particular group (we use that code on multiple AADs and all works ok, except one particular group within one AAD). I know that the group has members, but I don't actually have access to authorize as the service principal and debug the code (this happens in production). So the problem is, I'm getting an error, but I don't know what's it about, beside it being http status 400.

I was hoping that this would give me the body of the response in the logs (i.e. when doing `.ToString()` on the `ApiException`), but looking at the code, it doesn't seem like it.

**Comment by andrueastman** [comment]
This is a separate issue. Created https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/728 to track this.
