### ISSUE TITLE
Delete attachment (shared mailbox)

### ISSUE THREAD

**Issue by bartplay2499** [microsoftgraph/msgraph-sdk-dotnet#2116]
**Describe the bug**
When deleting an attachment from a draft (shared mailbox) via graph c#, the following error is returned - Mailbox move in progress. Try again later., Cross Server access is not allowed for mailbox. 

**To Reproduce**
graphServiceClient.Users[email].Messages[messageId].Attachments[attachmentId].DeleteAsync();

**Expected behavior**
The attachment has been deleted. Status code 200
 
**Screenshots** 
![202309051440](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/54477221/b7acf338-0377-4ec1-a91a-31982060d503)

**Comment by andrueastman** [comment]
Thanks for raising this @bartplay2499 

Any chance you can cross post the same question at the link below? As this repo is mainly intended for SDK related issues, the issue seems related to API side functionality that would be best answered there. It would be great if you could post a link to the created issue as well so that anyone who comes across this may also find this useful.

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph

**Comment by bartplay2499** [comment]
> 

Thank you, I asked a question on the link, I'm waiting for an answer.
Who also has problems with this here is a link to the question: [link](https://learn.microsoft.com/en-us/answers/questions/1360764/when-deleting-an-attachment-from-a-draft-(shared-m)
