### ISSUE TITLE
List calendarView not returning all events

### ISSUE THREAD

**Issue by yaurora** [microsoftgraph/msgraph-sdk-dotnet#2123]
**Describe the bug**
List calendarView not returning all events

**To Reproduce**
Steps to reproduce the behavior, tested with Postman
1. https://graph.microsoft.com/beta/users/organizer@somedomain.com/calendar/calendarView?startdatetime=2023-09-08T00:00:00.00Z&enddatetime=2023-10-10T23:59:59.00Z
2. returning only one of the two events
3.ttps://graph.microsoft.com/beta/users/attendee@somedomain.com/calendar/calendarView?startdatetime=2023-09-08T00:00:00.00Z&enddatetime=2023-10-10T23:59:59.00Z
4. returning all of the two events

**Expected behavior**
Query should return all events on user's calendar view
**Screenshots**
from organizer's calendar, there are 2 events
![271cfa8c5fa953dd69676171eb5b75b](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/42402727/6b7f91d3-3f20-401b-bf6d-03b70bb8101f)

but from API call, returned only one with that specific subject. plus, a request from attendee can see all these 2 events.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: N/A
 - Version

**Comment by andrueastman** [comment]
Thanks for raising this @yaurora 

As this is an API related question and this repo is mainly intended for SDK related issues, any chance you can post the same question at the link below to get feedback from the API owners? It would be great if you could post back the link to the question created as a comment so that anyone who needs this may find it as well.

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph
