### ISSUE TITLE
Failed to get user inbox message rules with internal server error

### ISSUE THREAD

**Issue by xpandax76** [microsoftgraph/msgraph-sdk-dotnet#2140]
Hi,

**Describe the bug**
I use Graph API to request user's inbox message rules and see that it failed for a few of the users with the response:
"An internal server error occurred. The operation failed., Index was outside the bounds of the array." with status code 500
This error seems to occur consistently with certain user. When I check user's data, there's nothing stand out that can help me troubleshoot this.

The request that I sent is https://graph.microsoft.com/v1.0/users/[user-id]/mailFolders/Inbox/messageRules?$top=999

**Expected behavior**
User's inbox message rules are returned

Thank you!

**Comment by andrueastman** [comment]
Thanks for raising this @xpandax76 

Any chance you can cross post this issue at the link below? As the issue seems to be API related and this repo is mainly intended for SDK related issues, the API owners may be best placed to answer what may be wrong. 

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph
