### ISSUE TITLE
[Client bug]: Graph client V5: SharePoint list driveitem permissions GrantedToV2 returns null

### ISSUE THREAD

**Issue by xinzhaozhang1985** [microsoftgraph/msgraph-sdk-dotnet#2149]
**Describe the bug**
We are upgrading from v4 to v5, when we request permissions for a site list driveitem, the GrantedToV2 object in permission is null.
It was working in the V4, but it is broken in V5. Also checked with graph explore, it is working as epected.

**To Reproduce**
1. Create a document in SharePoint
2. Install Nuget package v4 and construct request as below:
            var request = graphClient
                .Sites[<Your site id>]
                .Lists[<Your list id>]
                .Items[<Your item id>]
                .DriveItem
                .Permissions
                .Request();
          var permissions = await request.GetAsync();
Inspect the GrantedToV2 object in permissions and they are not empty
 
3. Upgrade the Nuget package to V5 and construct request as below:
            var item = await graphClient
                .Sites[<Your site id>]
                .Lists[<Your list id>]
                .Items[<Your item id>]
                .DriveItem
                .GetAsync(requestConfiguration =>
                {
                    requestConfiguration.QueryParameters.Expand = new string[] { "Permissions" };
                });
Inspect the GrantedToV2 object in permissions and they are empty

4. Validates the permissions returns correctly in Graph Explore

**Expected behavior**
GrantedToV2 and GrantedToIdentitiesV2 should be populated if they are not null. 

**Screenshots**
![V5](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/102950394/340462a0-be46-4e81-b975-bf7802ae7fd4)

![V4](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/102950394/b6ec5a73-4aa0-4fc4-ae92-175d1315e26c)

The first screenshot is using V5 and the second screenshot is using V4. You can see from the screenshot, the permission Id are the same to indicate I am requesting permissions for the same file
**Client version**
Nuget package version 5.28

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**

**Comment by MartinM85** [comment]
The issue is that there are two different queries

Query created from your code by SDK v4

`GET https://graph.microsoft.com/v1.0/sites/{site-id}/lists/{list-id}/items/{item-id}/driveItem/permissions`

Query created by SDK v5

`GET https://graph.microsoft.com/v1.0/sites/{site-id}/lists/{list-id}/items/{item-id}/driveItem?$expand=permissions`

The same behavior can be reproduced in Graph Explorer. The second query doesn't return `GrantedToV2`.

Another issue is that in SDK v5 you can't create this

```
var item = await graphClient
.Sites[]
.Lists[]
.Items[]
.DriveItem
.Permissions
.GetAsync();
```

Permissions navigation property is not exposed in this case

You need to make two calls, one call to get a `driveItem` and then the second call to get permissions through the ` /drives` endpoint

```
var driveItem = await graphClient
.Sites[""]
.Lists[""]
.Items[""]
.DriveItem
.GetAsync();

var permissions = await graphClient.Drives[driveItem.ParentReference.DriveId].Items[driveItem.Id].Permissions.GetAsync();
```

**Comment by xinzhaozhang1985** [comment]
Thanks. I can get the grantedToV2 permissions using two calls now.

You can close
