### ISSUE TITLE
Chat API permissions for Delegated (personal Microsoft Account)

### ISSUE THREAD

**Issue by Merichbier** [microsoftgraph/msgraph-sdk-dotnet#2153]
**Is your feature request related to a problem? Please describe.**
We are building a custom application, where we would like the user to be able to chat without changing application (because Teams app is not suitable in our use case)

**Describe the solution you'd like**
From documentation (https://learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&tabs=http) it seems that the Delegated (personal Microsoft account) permissions Chat.ReadBasic, Chat.Read and Chat.ReadWrite are not supported.

**Describe alternatives you've considered**
Use another platform, unfortunately none provide good API. We thought the Graph API was suitable until we saw it was not supported by the Graph API.

**Additional context**
I would like to understand why those permissions are not currently supported.

**Comment by andrueastman** [comment]
Thanks for raising this @Merichbier 

As this is an API related question, and this repository is mainly intended for SDK related issues, any chance you can post the same question at the link below to get feedback from the relevant API team? It would be great if you could post back the link to the created question so that anyone who comes across this may find it as well. 

https://learn.microsoft.com/en-us/answers/tags/282/microsoft-graph-teamwork-api
