### ISSUE TITLE
Graph API similar to Exchange API for controlling notifications regarding updated events

### ISSUE THREAD

**Issue by drweb86** [microsoftgraph/msgraph-sdk-dotnet#2172]
**We need to have a possibility to configure and prevent sending notifications when Event or Teams Online Meeting is created, modified or deleted using Graph API.**

**Why do we need it?**

Our app allows user to create course sessions for learners. When session is created, appointment is created as well. To reduce amount of email notifications being sent on the appointment creation, update, deletion application carefully (almost manually) controls in which cases users will receive notifications. Also, we have a mode inside application for managing appointments silently (create/update/delete) without sending e-mails.

Currently we’re using Exchange SDK. Here we specify different `SendInvitationsOrCancellationsMode`. We use `SendToChangedAndSaveCopy, SendToAllAndSaveCopy, SendToNone` when we manage appointments.

However, SDK is obsolete, didn’t receive updates for several years, can’t create Teams Online Meetings, does not allow to hide one attendee from another and in 3 years will be phased out.

That is why we’re switching to Graph API for appointment management. Also we will provide a possibility to optionally create Teams Online Meetings in the future. 

But Graph API does not have a possibility to configure and prevent sending notifications on Event and Teams Online Meeting creation, modification, deletion. That is why some learners of our existing customers will see more notifications, which we would like to avoid.

**Additional context**
We were asking for support in June 2021 and we were told that yes, its a gap between EWS and Graph API implementation and that it would be discussed internally with Mail + Calendar team. But yet we were rechecked 2 weeks ago and nothing seems to be added.

**Comment by andrueastman** [comment]
Thanks for raising this @drweb86 

As this repo is mainly intended for SDK related issues and your question is more along the lines of API side functionality, any chance you can post the same query at the link below to get feedback from the API owners on the possibility to configure and prevent sending notifications on Event and Teams Online Meeting creation, modification and deletion. It would be great if you could post back the link as a comment to the created question so that anyone who comes across this may also benefit from the information.

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph

**Comment by drweb86** [comment]
Hi. I created a question there
https://learn.microsoft.com/en-us/answers/questions/1403077/graph-api-similar-to-exchange-api-for-controlling

**Comment by andrueastman** [comment]
Closing this for now so that this may be followed up at the link above.
