### ISSUE TITLE
Graph SDK v5 referring to Microsoft.Kiota.Abstractions, Version=1.2.1.0

### ISSUE THREAD

**Issue by kyzhangZao** [microsoftgraph/msgraph-sdk-dotnet#2177]
I'm trying to upgrade our service to use graph sdk v5.
However, mock GraphServiceClinet using this new sdk causing:

> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Kiota.Abstractions, Version=1.2.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

per my understanding, graph sdk5 and graph.core sdk3, should be using Microsoft.Kiota.Abstractions, Version=1.3.1.0, not 1.2.1.0
I'm not sure why Microsoft.Kiota.Abstractions, Version=1.2.1.0 would be involved here. Also, this error is not occuring when using graph sdk4+graph.core sdk2.

Any idea why this happen and how to fix?

**Comment by andrueastman** [comment]
Thanks for raising this @kyzhangZao 

Any chance you can confirm the version of the SDK you are using as well as the dotnet runtime as well when you experience this?

**Comment by kyzhangZao** [comment]
We're using .NET Framework 4.7.2
sdk Microsoft.Graph 5.30.0 and Microsoft.Graph.Core 3.0.11

**Comment by baywet** [comment]
MSGraph 5.30.0 [depends on graph core 3.X](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/04c70b7eeaee243e316d3d14b6a9a610bf87d75d/src/Microsoft.Graph/Microsoft.Graph.csproj#L66) which at the time of the issue resolved to 3.0.11.
Graph Core 3.0.11 [depends on both abstractions 1.3.1 and serialization json 1.0.8](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/2ee0843c3190a62a31242dc3d5f110dcfae1c85a/src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj#L63)
Serialization JSON [depends on abstractions 1.2.1](https://github.com/microsoft/kiota-serialization-json-dotnet/blob/v1.0.8/src/Microsoft.Kiota.Serialization.Json.csproj)

We've just released graph 5.31.0 and graph core 3.1.0 which aligns all dependencies. Would you mind trying with those new versions?

Also do you have any other kiota client in your code base?

**Comment by kyzhangZao** [comment]
We do not have any explicit reference to kiota client. Per my understanding, we just introduced this when try to use newer version of graph sdk.
I just quickly tried to use graph 5.31.0 and graph core 3.1.0, however seems graph core 3.1.0 depends on Microsoft.Kiota.Abstractions 1.5.0, however the unit test is now trying to refer to Microsoft.Kiota.Abstractions 1.3.1.0

> Could not load file or assembly 'Microsoft.Kiota.Abstractions, Version=1.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.

While when I try to explicitly adding dependency of Microsoft.Kiota.Abstractions, Version=1.3.1.0 to our unit test (which I suppose we should not directly adding that dependency), gets the below error

> Install-Package : NU1605: Warning As Error: Detected package downgrade: Microsoft.Kiota.Abstractions from 1.5.0 to 1.3.1. Reference 
the package directly from the project to select a different version. 

And we do not have any other reference to koita client
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/148756322/9b8e2a2a-5cdc-4e40-8c80-14f07cb4cc5c)

**Comment by baywet** [comment]
Is it possible you have multiple references to graph or graph core in your project structure?

**Comment by kyzhangZao** [comment]
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/148756322/c64e3205-a812-412b-b155-fa92dc5e2f87)
The above are the only references we have to graph and graph core.

**Comment by baywet** [comment]
Can you run the dotnet list package command to try to understand which dependency is bringing the older version of abstractions?
https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-list-package

**Comment by kyzhangZao** [comment]
That's the two places we have graph sdk and graph core sdk
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/148756322/df594869-c731-49d2-99c2-087d3173e6ed)
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/148756322/dadb7b92-4e0d-422f-8baa-3f54f1451e25)
And that the project where unit tests fail:
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/148756322/7d883b76-de1e-4cf9-94ba-27255c8a207d)

**Comment by baywet** [comment]
Thanks for the additional information:
- which project does the test project have a dependency on? common? or cloud common?
- can you try removing the reference to graph core in cloud common? `dotnet remove <pathToCsProj> package microsoft.graph.core`
- does cloud common have a dependency on common? or the other way around?

**Comment by kyzhangZao** [comment]
- Test project has direct dependency on cloud common, and indirect dependency on common.

- Cloud common and common does not have dependency on each other. They have a common dependency on another project
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/148756322/dcc3afc0-c31c-4a09-8b07-149a549955af)

- I tried to remove dependency on graph.core and it gets back to error

> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Kiota.Abstractions, Version=1.2.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Meanwhile I'm not sure if removing this dependency would actually work because in our development, there is another use case explicitly stating we should use graph.core sdk

**Comment by A-Lynch** [comment]
I'm experiencing the same issue and have cleared nuget cache, the issue still exists

**Comment by A-Lynch** [comment]
Hi 4.8

**Comment by baywet** [comment]
thanks for the additional information. And are you using the dotnet cli to build or visual studio?

**Comment by A-Lynch** [comment]
Visual studio

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by andrueastman** [comment]
@A-Lynch @kyzhangZao Any chance you are able to replicate the issue with the latest release?https://www.nuget.org/packages/Microsoft.Graph/5.32.0

**Comment by A-Lynch** [comment]
Hi 

Ive updated, however I now have an issue with Azure Core

Tried the usual - Clean, Delete obj & bin folders 

TypeInitializationException: The type initializer for 'Azure.Core.ClientOptions' threw an exception.

FileNotFoundException: Could not load file or assembly 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.

**Comment by kyzhangZao** [comment]
I tried the same, also tried to use graph 5.32.0, still seeing

> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Kiota.Abstractions, Version=1.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by A-Lynch** [comment]
Sorry Further testing has reviled an issue with 


Microsoft.Identity.Client 4.57 is installed as part of adding package, yet it references Microsoft.Identity.Client 4.56
This is the same for the Microsoft.IdentityModel. libraries

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.Identity.Client, Version=4.56.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae
 (Fully-specified)
LOG: Initial PrivatePath = NULL
Calling assembly : Azure.Identity, Version=1.10.3.0, Culture=neutral, PublicKeyToken=92742159e12e44c8Version=1.10.3.0, Culture=neutral, PublicKeyToken=92742159e12e44c8.

**Comment by kyzhangZao** [comment]
@baywet I tried to ask my teammates to run on their end as you suggested offline, but they're getting the same exception as the ones on my end.

**Comment by baywet** [comment]
Thanks everyone for the additional information.
Can you confirm which version of Visual Studio you're using? I took the time to get a VM with VS 2022 version 17.7.6, which looks like it's the latest version for the mainline.
(and I'm still not getting the issue)
@kyzhangZao could you reach out internally with the setup instructions for the integration tests for your repo? I want to make sure this missing setup is not hiding the issue on my side.

**Comment by A-Lynch** [comment]
Hi 

Im using 

Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.6.4

**Comment by baywet** [comment]
Thanks for the additional information.
Since @kyzhangZao is also a Microsoft employee, we just spent some time troubleshooting the issue together.
Now that the dependencies alignment issue has been solved for kiota abstractions, my guess was that version ranges (like in kiota http for System.Diagnostics.DiagnosticSource) were confusing this older version.
We've tried a couple of combinations to understand why the dependency could not be loaded by net472.
Unfortunately our multiple tries, including locking the dependency to a specific version instead of a range, we unsuccessful.
The next step is for @kyzhangZao to engage with the dotnet team to understand this assembly loading issue better.

**Comment by baywet** [comment]
@A-Lynch as a recap from the internal discussions: the problem was solved for the internal service [by switching to CPM](https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management) which helps resolve any conflict.
Of course, if you can, it'd be preferrable to migrate to dotnet core. Not only the dependency resolution works better, but you'll benefit from huge performance improvements and much more.

**Comment by kyzhangZao** [comment]
Hi @baywet , just to provide an update there, using CPM tool as mentioned above actually removed some of our setup configs. Ans when I try to add back those config, new conflicts showed up. 
So I created a clean branch with changes that is able to build without error. UTs now fails with 

> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Kiota.Abstractions, Version=1.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Kiota.Abstractions, Version=1.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

I'm currently on sdk 5.34.0
I might need more help with simply focusing on resolve that specific dependency issue. Thanks.

**Comment by baywet** [comment]
For everybody else involved: we're working with the dotnet team to understand whether or not CPM can be used in combination with assembly binding redirection. Also to understand whether CPM can be used for some projects and not others.

**Comment by baywet** [comment]
Thanks for the nudge here.

The gist of the conversation was that CPM and assembly binding redirections can be used in combination, but it's easy to get things wrong.

To investigate which project pulls what (at dev time), make heavy use of the new `dotnet nuget why` command [documentation](https://learn.microsoft.com/en-ca/dotnet/core/tools/dotnet-nuget-why)

On our side we've taken a few steps to make this easier:

- Aligned all the kiota packages versioning, and release them at the same time.
- Introduced a new kiota bundle package to reduce the number of direct dependencies a project needs to take.
- Switched to version ranges in kiota packages for things like System.Text.Json, and in Graph packages for kiota packages.

Start by making sure you're on the latest version of the Graph SDK, and that you don't have any direct dependency on outdated graph core/kiota dependencies. And investigate further with dotnet nuget why if needed.

Let us know if you have any additional comments or questions.

**Comment by gallettoNL** [comment]
Thanks Vincent, I’ll have a look into this.

I sometimes feel like we are back in dll-hell from the nineties… 😉


Lievestro Software
Will de Haan

Van: Vincent Biret ***@***.***>
Verzonden: woensdag 13 november 2024 12:18
Aan: microsoftgraph/msgraph-sdk-dotnet ***@***.***>
CC: Will de Haan ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [microsoftgraph/msgraph-sdk-dotnet] Graph SDK v5 referring to Microsoft.Kiota.Abstractions, Version=1.2.1.0 (Issue #2177)


Thanks for the nudge here.

The gist of the conversation was that CPM and assembly binding redirections can be used in combination, but it's easy to get things wrong.

To investigate which project pulls what (at dev time), make heavy use of the new dotnet nuget why command documentation<https://learn.microsoft.com/en-ca/dotnet/core/tools/dotnet-nuget-why>

On our side we've taken a few steps to make this easier:

  *   Aligned all the kiota packages versioning, and release them at the same time.
  *   Introduced a new kiota bundle package to reduce the number of direct dependencies a project needs to take.
  *   Switched to version ranges in kiota packages for things like System.Text.Json, and in Graph packages for kiota packages.

Start by making sure you're on the latest version of the Graph SDK, and that you don't have any direct dependency on outdated graph core/kiota dependencies. And investigate further with dotnet nuget why if needed.

Let us know if you have any additional comments or questions.

**Comment by gallettoNL** [comment]
Hi Vincent,

I’m totally missing out on something here.

When I build a project (COMplanEF.vbroj) I get warnings about kiota packages:

41>------ Rebuild All started: Project: COMplanEF, Configuration: Debug x86 ------
41>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277: Found conflicts between different versions of "Microsoft.Kiota.Abstractions" that could not be resolved.
41>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277: There was a conflict between "Microsoft.Kiota.Abstractions, Version=1.13.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" and "Microsoft.Kiota.Abstractions, Version=1.14.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35".
41>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:     "Microsoft.Kiota.Abstractions, Version=1.13.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" was chosen because it was primary and "Microsoft.Kiota.Abstractions, Version=1.14.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" was not.
41>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:     References which depend on "Microsoft.Kiota.Abstractions, Version=1.13.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" [C:\Users\WilldeHaan\.nuget\packages\microsoft.kiota.abstractions\1.13.0\lib\netstandard2.0\Microsoft.Kiota.Abstractions.dll].
41>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         C:\Users\WilldeHaan\.nuget\packages\microsoft.kiota.abstractions\1.13.0\lib\netstandard2.0\Microsoft.Kiota.Abstractions.dll
41>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item includes which caused reference "C:\Users\WilldeHaan\.nuget\packages\microsoft.kiota.abstractions\1.13.0\lib\netstandard2.0\Microsoft.Kiota.Abstractions.dll".


So I run nuget why against the project’s assets file:

PS C:\Users\WilldeHaan\Source\Repos\PLANproducten501\COMplanEF\obj> dotnet nuget why project.assets.json Microsoft.Kiota.Abstractions
Project 'COMplanEF' does not have a dependency on 'Microsoft.Kiota.Abstractions'.
PS C:\Users\WilldeHaan\Source\Repos\PLANproducten501\COMplanEF\obj>

So, what’s the warning about?
What am I missing?

Thanks for any hints and tricks…

Lievestro Software
Will de Haan

Van: Vincent Biret ***@***.***>
Verzonden: woensdag 13 november 2024 12:18
Aan: microsoftgraph/msgraph-sdk-dotnet ***@***.***>
CC: Will de Haan ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [microsoftgraph/msgraph-sdk-dotnet] Graph SDK v5 referring to Microsoft.Kiota.Abstractions, Version=1.2.1.0 (Issue #2177)


Thanks for the nudge here.

The gist of the conversation was that CPM and assembly binding redirections can be used in combination, but it's easy to get things wrong.

To investigate which project pulls what (at dev time), make heavy use of the new dotnet nuget why command documentation<https://learn.microsoft.com/en-ca/dotnet/core/tools/dotnet-nuget-why>

On our side we've taken a few steps to make this easier:

  *   Aligned all the kiota packages versioning, and release them at the same time.
  *   Introduced a new kiota bundle package to reduce the number of direct dependencies a project needs to take.
  *   Switched to version ranges in kiota packages for things like System.Text.Json, and in Graph packages for kiota packages.

Start by making sure you're on the latest version of the Graph SDK, and that you don't have any direct dependency on outdated graph core/kiota dependencies. And investigate further with dotnet nuget why if needed.

Let us know if you have any additional comments or questions.

**Comment by gallettoNL** [comment]
To make the confusion complete:

When running the application I get

System.IO.FileLoadException: 'Kan bestand of assembly Microsoft.Kiota.Abstractions, Version=1.12.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 of een van de afhankelijkheden hiervan niet laden. De manifestdefinitie van de gevonden assembly komt niet overeen met de assembly-verwijzing. (Uitzondering van HRESULT: 0x80131040)'

This exception was originally thrown at this call stack:
    Microsoft.Graph.GraphServiceClient.GraphServiceClient(Azure.Core.TokenCredential, System.Collections.Generic.IEnumerable<string>, string)
    PLANemailSender.Sender.VerzendEmail(string, string, string, string, string) in Sender.cs<navigate-to-context:1>

I’m lost….


Lievestro Software
Will de Haan

Van: Will de Haan ***@***.***>
Verzonden: woensdag 13 november 2024 14:51
Aan: microsoftgraph/msgraph-sdk-dotnet ***@***.***>; microsoftgraph/msgraph-sdk-dotnet ***@***.***>
CC: Comment ***@***.***>; Plansupport ***@***.***>
Onderwerp: RE: [microsoftgraph/msgraph-sdk-dotnet] Graph SDK v5 referring to Microsoft.Kiota.Abstractions, Version=1.2.1.0 (Issue #2177)

Hi Vincent,

I’m totally missing out on something here.

When I build a project (COMplanEF.vbroj) I get warnings about kiota packages:

41>------ Rebuild All started: Project: COMplanEF, Configuration: Debug x86 ------
41>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277: Found conflicts between different versions of "Microsoft.Kiota.Abstractions" that could not be resolved.
41>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277: There was a conflict between "Microsoft.Kiota.Abstractions, Version=1.13.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" and "Microsoft.Kiota.Abstractions, Version=1.14.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35".
41>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:     "Microsoft.Kiota.Abstractions, Version=1.13.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" was chosen because it was primary and "Microsoft.Kiota.Abstractions, Version=1.14.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" was not.
41>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:     References which depend on "Microsoft.Kiota.Abstractions, Version=1.13.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" [C:\Users\WilldeHaan\.nuget\packages\microsoft.kiota.abstractions\1.13.0\lib\netstandard2.0\Microsoft.Kiota.Abstractions.dll].
41>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         C:\Users\WilldeHaan\.nuget\packages\microsoft.kiota.abstractions\1.13.0\lib\netstandard2.0\Microsoft.Kiota.Abstractions.dll
41>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item includes which caused reference "C:\Users\WilldeHaan\.nuget\packages\microsoft.kiota.abstractions\1.13.0\lib\netstandard2.0\Microsoft.Kiota.Abstractions.dll".


So I run nuget why against the project’s assets file:

PS C:\Users\WilldeHaan\Source\Repos\PLANproducten501\COMplanEF\obj> dotnet nuget why project.assets.json Microsoft.Kiota.Abstractions
Project 'COMplanEF' does not have a dependency on 'Microsoft.Kiota.Abstractions'.
PS C:\Users\WilldeHaan\Source\Repos\PLANproducten501\COMplanEF\obj>

So, what’s the warning about?
What am I missing?

Thanks for any hints and tricks…

Lievestro Software
Will de Haan

Van: Vincent Biret ***@***.******@***.***>>
Verzonden: woensdag 13 november 2024 12:18
Aan: microsoftgraph/msgraph-sdk-dotnet ***@***.******@***.***>>
CC: Will de Haan ***@***.******@***.***>>; Comment ***@***.******@***.***>>
Onderwerp: Re: [microsoftgraph/msgraph-sdk-dotnet] Graph SDK v5 referring to Microsoft.Kiota.Abstractions, Version=1.2.1.0 (Issue #2177)


Thanks for the nudge here.

The gist of the conversation was that CPM and assembly binding redirections can be used in combination, but it's easy to get things wrong.

To investigate which project pulls what (at dev time), make heavy use of the new dotnet nuget why command documentation<https://learn.microsoft.com/en-ca/dotnet/core/tools/dotnet-nuget-why>

On our side we've taken a few steps to make this easier:

  *   Aligned all the kiota packages versioning, and release them at the same time.
  *   Introduced a new kiota bundle package to reduce the number of direct dependencies a project needs to take.
  *   Switched to version ranges in kiota packages for things like System.Text.Json, and in Graph packages for kiota packages.

Start by making sure you're on the latest version of the Graph SDK, and that you don't have any direct dependency on outdated graph core/kiota dependencies. And investigate further with dotnet nuget why if needed.

Let us know if you have any additional comments or questions.

**Comment by baywet** [comment]
The error messages you've provided refer to 3 different versions: 1.12.3, 1.13.0, 1.14.0.
My guess is that one or more of your project refers to different versions of the Graph SDK, or kiota dependencies, or both.
I'd suggest you track dependencies in all csproj files, to better understand who is pulling what, and resolve any misalignment in your project configurations.
