### ISSUE TITLE
How to retrieve actual value of OmaSettingStringXml.Value?

### ISSUE THREAD

**Issue by RytisLT** [microsoftgraph/msgraph-sdk-dotnet#2188]
I'm using the following code to retrieve `OmaSettingStringXml`

```C#
var creds = new ClientSecretCredential(_config.TenantId, _config.ClientId, _config.ClientSecret);
var client = new GraphServiceClient(creds, new[] { "https://graph.microsoft.com/.default" }); 
var cfgReq = client.DeviceManagement.DeviceConfigurations[_config.DeviceConfigurationId];
var item = (Windows10CustomConfiguration)(await cfgReq.GetAsync())!;
var setting = item.OmaSettings?.OfType<OmaSettingStringXml>().First();
var valueString = Encoding.UTF8.GetString(setting?.Value!);
Console.WriteLine(valueString); // is always <a/>
```

The `OmaSettingStringXml.Value` always contains `<a/>` even though inspecting the value through [Azure UI](https://intune.microsoft.com/#view/Microsoft_Intune_DeviceSettings/DevicesWindowsMenu/~/configProfiles) shows a different value. How can I retrieve the actual XML?

**Comment by andrueastman** [comment]
Thanks for raising this @RytisLT 

To help us understand if this is SDK or API related? Any chance you get a similar issue when you make the same request using the [Graph Explorer](https://aka.ms/ge)?

**Comment by RytisLT** [comment]
@andrueastman It is API related, same result using simple HTTP requests, except that value is base64 encoded

**Comment by andrueastman** [comment]
@RytisLT As this is an API related question and this repo is mainly intended for SDK related issues, we may not be best placed to answer this question. 
Any chance you can post the question at the link below to get feedback from the API owners? It would be great if you could post back the link to the created query so that anyone who comes across this may also be able to get the information. 

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph
