### ISSUE TITLE
MailFolders returns different results than MailFolders["ROOT"].ChildFolders

### ISSUE THREAD

**Issue by kosa-gyula-77** [microsoftgraph/msgraph-sdk-dotnet#2194]
**Describe the bug**
`MailFolders` returns different results than `MailFolders["ROOT"].ChildFolders`.

**To Reproduce**
1. Case `MailFolders`
```
var folders = await graphClient
    .Users[MailboxConfiguration.EmailAddress]
    .MailFolders
    .GetAsync(requestConfig =>
    {
        requestConfig.Headers.Add(Constants.Headers.PreferHeaderName, Constants.Headers.PreferHeaderImmutableIdValue);
        requestConfig.QueryParameters.Select = new[] { "id", "displayName" };
        requestConfig.QueryParameters.IncludeHiddenFolders = "true";
        requestConfig.QueryParameters.Top = 100;
    });
```
2. Case `MailFolders["ROOT"].ChildFolders`
```
var folders = await graphClient
    .Users[MailboxConfiguration.EmailAddress]
    .MailFolders["ROOT"].ChildFolders
    .GetAsync(requestConfig =>
    {
        requestConfig.Headers.Add(Constants.Headers.PreferHeaderName, Constants.Headers.PreferHeaderImmutableIdValue);
        requestConfig.QueryParameters.Select = new[] { "id", "displayName" };
        requestConfig.QueryParameters.IncludeHiddenFolders = "true";
        requestConfig.QueryParameters.Top = 100;
    });
```

**Expected behavior**
They return the same collection of folders.

**Client version**
"Microsoft.Graph" Version="5.32.0".
Version 4.x might have the same issue.

**Comment by andrueastman** [comment]
Thanks for raising this @kosa-gyula-77 

As this question is about the behavior of the API returning different results based on the call, any chance you can post the question at the link below to get feedback from the API owners? As this repo is mainly intended for issues related to the SDK, we may not be best placed to answer. It would also be great if you could post back the link to the same so that anyone who has a similar question may also find it useful. 

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph
