### ISSUE TITLE
Calendar Event List instances should include the deleted occurrence too.

### ISSUE THREAD

**Issue by idiotsky** [microsoftgraph/msgraph-sdk-dotnet#2196]
I'm use the following code to retrieve the recurrence exception for sync to local calendar
`
EventCollectionResponse allOccurrences =
    await graphServiceClient.Me.Events[id].Instances.GetAsync(
        configuration =>
        {
            configuration.QueryParameters.StartDateTime = "2023-08-29T09:00:00.0000000";
            configuration.QueryParameters.EndDateTime = "2023-10-29T00:00:00.0000000";
            configuration.QueryParameters.Filter = "Type eq 'Exception'";
        }
    );
`
it only returns the change occurrence, the deleted occurrence should be return too.

**Comment by andrueastman** [comment]
Thanks for raising this @idiotsky 

As this is a question related to the functionality of the API response and this repo is mainly intended for the issues related with client SDK, we may not be best place to answer how to get the deleted occurrences from the API as well. 
Any chance you can post the same question at the link below so as to get feedback from the API owners if this is supported? It would be great if you could post back a link to the same as well so that anyone who comes across this may also find it as well. 

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph
