### ISSUE TITLE
SendMail with MIME content ignores custom MIME headers

### ISSUE THREAD

**Issue by obartelt** [microsoftgraph/msgraph-sdk-dotnet#2209]
When sending a mail with via Messages.ToPostRequestInformation and then adding the MIME message as content, any MIME headers contained in that message are ignored when sending (or at least they are not contained in the mail received by the recipient). In this case: Auto-Submitted (removed), Return-Path (replaced with the sender of the mail).

I know that only X-... headers can be added via the Message object (which is unfortunate enough), but at least that way, an error message is returned. When using MIME format, the mail is sent, but the headers are removed/replaced.

Expected behavior: let any MIME headers that do not need replacement in, or report back an error message about conflicting headers that actually need replacement (like recipient, date, etc.).
Version: Microsoft.Graph 5.34.0, .NET Standard 2.0 with .NET 6.0 test application

**Comment by andrueastman** [comment]
Thanks for raising this @obartelt 

As this this is a question related to the behaviour of the API and this repo is mainly intended for issued related to the function of SDK, any chance you can post a question at the link below to get guidance from the API owners on whether sending an email in mime format allows the addition of custom MIME headers as well? It would be great if you could post back the link as a comment so that anyone else with the question may also be able to discover it. 

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph
