### ISSUE TITLE
SendMail ignores extended MAPI properties specified as SingleValueExtendedProperties

### ISSUE THREAD

**Issue by obartelt** [microsoftgraph/msgraph-sdk-dotnet#2210]
When sending a mail with SendMail.PostAsync, extended MAPI properties specified in Message.SingleValueExtendedProperties are ignored or at least not appearing in the mail received by the recipient. In this case, the Return-Path header was added using the following snippet, because adding it as an InternetMessageHeader is not allowed, and sending the mail in MIME format with the header doesn't work either:

```
message.SingleValueExtendedProperties.Add(new Microsoft.Graph.Models.SingleValueLegacyExtendedProperty
{
    Id = "String 0x1046",  // PidTagInternetReturnPath
    Value = email.ReturnPath.EmailAddress
});
```

Expected behavior: set the Return-Path header in the sent mail to the specified address.
Version: Microsoft Graph 5.34.0, .NET Standard 2.0 with .NET 6.0 test application

**Comment by andrueastman** [comment]
Thanks for raising this @obartelt 

As this this is a question related to the behaviour of the API and this repo is mainly intended for issued related to the function of SDK, any chance you can post a question at the link below to get guidance from the API owners on whether sending an email in mime format allows the addition of `SingleValueExtendedProperties` as well? It would be great if you could post back the link as a comment so that anyone else with the question may also be able to discover it. 

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph
