### ISSUE TITLE
Paging works wrong  SDK V5 (Top returns one extra element)

### ISSUE THREAD

**Issue by salladorets** [microsoftgraph/msgraph-sdk-dotnet#2219]
SDK version 5.34.0

The following request returns one extra element
```
            var response = await graphServiceClient.Drives[folderInfo.DriveId].Items[folderInfo.FolderId].Delta.GetAsDeltaGetResponseAsync((requestConfiguration) =>
            {
                requestConfiguration.QueryParameters.Top = 10;
                requestConfiguration.QueryParameters.Select = propertiesToSelect;
            });
```

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/16153445/ede468bb-7300-489c-8650-197a6c60e2bd)

**Comment by andrueastman** [comment]
Thanks for raising this @salladorets 

I can replicate this on the [the graph explorer ](https://developer.microsoft.com/en-us/graph/graph-explorer?request=me%2Fdrive%2Froot%2Fdelta%3Ftop%3D1&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com) as well . As this seems to be an API related/documentation issue and not due to the SDK, we'll close this follow this up via https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/8829 for feedback from API documentation team.
