### ISSUE TITLE
Methods marked as obsolete

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/msgraph-sdk-dotnet#2244]
A lot of methods have `Obsolete` attribute with the message `This method is obsolete...`.

What's the reason behind this? When you check the documentation for the Graph API, examples for C# are using those obsolete methods. It can be confusing for some developers. 

Do you plan to remove those obsolete methods? Is there any deadline?

Thx

**Comment by andrueastman** [comment]
Thanks for raising this @MartinM85 

The methods are currently marked obsolete due to changes in generator (mainly due to possible collision of types and size optimizations in the generation) and will not be removed until the next major version change of both the SDK and the generator (Kiota). 
At the moment there is no specific date set yet but you can use this milestone to track progress on the generator. 
https://github.com/microsoft/kiota/milestone/10

**Comment by andrueastman** [comment]
Documentation will be updated on the resolution of https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1880. Closing this one for now.
