### ISSUE TITLE
[Client bug]: Publication property is not returned when searching for a driveitem in Graph API

### ISSUE THREAD

**Issue by Maheshyu1710** [microsoftgraph/msgraph-sdk-dotnet#2272]
**Describe the bug**
I am using the below C# graph client to search driveitem, however the result doesn't contain the publication property.
I have also tried to add the publication property in the select query, still the property is not returned.

**To Reproduce**
var result = await client.Shares[encodedUrl].Root
    .Search(filesInFolderSearchRequest.SearchText)
    .Request(queryOptions)
    .Select("file,id,name,Publication,sharepointids")
    .OrderBy(filesInFolderSearchRequest.OrderBy)
    .Top(top)
    .WithMaxRetry(5)
    .GetAsync();

**Expected behavior**
I expected the property to be returned as mentioned in the select query.

**Comment by andrueastman** [comment]
Thanks for raising this @Maheshyu1710 

Any chance you can confirm the version of the sdk you are using to make the request? Are you able to confirm that the property is present in the json payload when you make a similar request using [the Graph Explorer](https://aka.ms/ge)?

**Comment by Maheshyu1710** [comment]
Hello @andrueastman , the json response for the corresponding graph api endpoint in the Graph Explorer does not return the 'Publication' property as well when I add a search query to it .

This works - https://graph.microsoft.com/v1.0/shares/{shares-id}/root?$select=file,id,name,webUrl,lastModifiedDateTime,WebDavUrl,sharepointids,parentReference,lastModifiedBy,publication

This doesn't - https://graph.microsoft.com/v1.0/shares/{shares-id}/root/search(q='filename')?$select=file,id,name,webUrl,lastModifiedDateTime,WebDavUrl,sharepointids,parentReference,lastModifiedBy,publication

**Comment by andrueastman** [comment]
Thanks for following up @Maheshyu1710 

As this seems to be a limitation on the API side and this repo is mainly intended for SDK related issues, any chance you can create a request at the link below for the API owners to follow up on adding the functionality to the search action? It would be great if you could post back the link to the same here as a comment so that anyone in future with the same request may find it as well. 

https://feedbackportal.microsoft.com/feedback/forum/ebe2edae-97d1-ec11-a7b5-0022481f3c80
