### ISSUE TITLE
Update B2BManagementPolicy 

### ISSUE THREAD

**Issue by jdenka** [microsoftgraph/msgraph-sdk-dotnet#2273]
I have an issue with updating our B2BManagementPolicy, we are using Allow list for external domain and we are currently running a PowerShell script to get the list in Sharepoint that we have setup and maintaining, it then converts it to json and sets it with Set-AzureADPolicy and then also writes it to Teams collaboration settings.
We want to move from that solution since from what we can see it requires the use of Global Administrator rights.

I have tried with several Graph API permissions for a App registration but nothing seems to work to update the B2B policy as an application.

Since the AzureAD PowerShell module no longer is maintained we would like the feature updated for the Graph module instead.

I have tried to patch the list via PowerShell to the Graph Endpoint at https://graph.microsoft.com/beta/legacy/policies/d7ab3cf3-4bb2-491f-a29f-fa2030b0a873/definition but that does not seem to allow being patched either. 

Im currently out of options, the only thing that kind of works right now is an app registration that we probably have to give the Global Administrator role to for it to even work and that is probably not an option in the long run.

**Comment by andrueastman** [comment]
Thanks for raising this @jdenka 

As this seems to be an api related question and this repo is mainly intended for SDK related issues, any chance you can post the question at the link below to get feedback from the API owners on the state of the update B2BManagementPolicy API? 
It would be great if you could post back the link to the same here as a comment so that anyone who comes across this may find the information as well. 

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph

**Comment by jdenka** [comment]
Thank you @andrueastman for pointing me in the right direction, will go there and give them feedback instead.
