### ISSUE TITLE
While Fetching Teams Chat Message , MessageHistory is always NULL

### ISSUE THREAD

**Issue by TejasPatadiya10** [microsoftgraph/msgraph-sdk-dotnet#2284]
Hi,
According to documentation of teams api , it does support the MessageHistory 

https://learn.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-1.0&tabs=http

https://learn.microsoft.com/en-us/graph/api/resources/chatmessagehistoryitem?view=graph-rest-1.0

but while fetching the same using graph API we are always getting NULL in MessageHistory.

Please guide us on the same.

**Comment by andrueastman** [comment]
Thanks for raising this @TejasPatadiya10 

To help understand this better, any chance you can confirm if you are using the SDK to make requests for a chat message? Any chance you have also tried using[ the Graph Explorer](https://aka.ms/ge) to make a request as well?
I believe the property will be populated if the message is modified or reaction added to it. Any chance you can confirm if this is the case too?

**Comment by TejasPatadiya10** [comment]
Hi @andrueastman ,

I have also tried using the GRAPH Explorer but it not giving MessageHistory Node in response.

We already have edited the message multiple times and also edited the reactions multple times as well.

Its is documented but we ain't found any way to get this. please help us achieve the same.

**Comment by andrueastman** [comment]
Thanks for following up @TejasPatadiya10 

As this related to API side behaviour, we may not be the best placed to answer the question as this repo is mainly intended for SDK related issues. Any chance you can post the same query at the link below to get feedback from the API owners on what would be needed to get the property? It would be great if you could post back the link of the created question so that anyone who also needs the info may find it too. 

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph

**Comment by TejasPatadiya10** [comment]
Thanks @andrueastman for the guidance.

Posted the same. 

[https://learn.microsoft.com/en-us/answers/questions/1500529/while-fetching-teams-chat-message-messagehistory-i]

**Comment by andrueastman** [comment]
Thanks @TejasPatadiya10 

We'll close this for now so that this can be followed up there. Feel free to re-open/create new issue if something SDK related arises.
