### ISSUE TITLE
Unable to retrieve Active Directory Organization Units with Microsoft Graph APi

### ISSUE THREAD

**Issue by balukantu** [microsoftgraph/msgraph-sdk-dotnet#2297]
How can I retrieve the Active Directory organization units(OU) that have been synced to Azure using ADDS(Active Directory Domain Services)?

According to: [https://azure.microsoft.com/en-us/documentation/articles/active-directory-ds-admin-guide-create-ou/](https://azure.microsoft.com/en-us/documentation/articles/active-directory-ds-admin-guide-create-ou/) 

_User accounts, groups, service accounts and computer objects that you create under custom OUs will not be available in your Azure AD tenant. In other words, these objects will not show up using the Azure AD Graph API or in the Azure AD UI. These objects will only be available in your Azure AD Domain Services managed domain_  

So, is this just a "not possible" using Graph Api? Or is there another way? Is it possible using a different Microsoft api other than Graph?

**Comment by andrueastman** [comment]
Thanks for raising this @balukantu 

As this repo is intended mainly for SDK related issues, we may not be best placed to answer the API related question raised. Any chance you can post a question at the link below so as to get feedback from the relevant API owners. It would be great if you could post back the created question back here as a comment so that anyone who comes across this may also find the information as well. 

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph
