### ISSUE TITLE
Private Channel Members missing in SharePoint Site Collection 

### ISSUE THREAD

**Issue by Benny183** [microsoftgraph/msgraph-sdk-dotnet#2313]
**Describe the bug**
If private channel is created with members or members are added to private channel. The permission to SharePoint Site Collection are not synced. Private channel members list is correct in Teams admin portal. But the SharePoint member group ist empty. Graph request to add member is successfully. If user is defined as owner, then it works

**To Reproduce**
1. Add Member to existing private channel with graph 
2. Try to open SharePoint Site with added user

**Expected behavior**
Added channel member is in SharePoint members group

**Screenshots**
Graph Request Succeded:
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/37909390/10c66e6c-0f01-4381-a0f7-f4e0e64764c5)

Site Members Group Empty
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/37909390/05837f5f-54cf-4bb9-8531-8e3ea6dca322)

**Comment by andrueastman** [comment]
Thanks for raising this @Benny183 

As this question is API related, any chance you can post the question at the link below to get feedback from the API owners? As this repo is mainly intended for SDK related issues, we may not be best placed to answer this. It would be great if you could post back the link to the question here as a comment so that anyone who needs the info may find it too. 

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph
