### ISSUE TITLE
Bad Request: Failed to execute Skype backend request GetThreadS2SRequest when creating a new channel

### ISSUE THREAD

**Issue by magarma** [microsoftgraph/msgraph-sdk-dotnet#2317]
Hi,
we are trying to create a Teams channel and in the moment that we are setting the isFavoriteByDefault property, Graph is giving a Bad Request error. However the channel is created properly.
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/8925463/468b3610-321a-4d39-8089-81357963c795)

This was working properly before, so I guess that is something that has been changed on the API.
Do you know how to avoid this issue? Any special header or something?

Thanks

**Comment by andrueastman** [comment]
Thanks for raising this @magarma  

As this repo is mainly intended for SDK related issues, any chance you can post the question at the link below to get feedback from the API owners? It would be great if you could post back the link to the question as a comment so that anyone who comes across this may also find the information as well.

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph

**Comment by magarma** [comment]
Sure, 
posted here
https://learn.microsoft.com/en-us/answers/questions/1526652/bad-request-failed-to-execute-skype-backend-reques

**Comment by andrueastman** [comment]
Thanks @magarma.

We'll close this here so that it may be followed up at the link,
