### ISSUE TITLE
mailboxSettings language Patch not working

### ISSUE THREAD

**Issue by salahBouragba** [microsoftgraph/msgraph-sdk-dotnet#2319]
**Describe the bug**
I can't change the Mailbox settings language property with a Patch request.

**To Reproduce**
1. launch the http request: PATCH: https://graph.microsoft.com/v1.0/users/{USER_NAME}/mailboxSettings with the body: 
{
    "language": {
        "locale": "en-US"
    }
}
3. Verify that the language wasn't changed in the response (or call a GET request to get the mailboxSettings)

**Expected behavior**
The language should be updated

**Screenshots**
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/98818340/8ea78e61-2c5e-4a56-bd79-75037ab95fea)

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/98818340/e2fa8d9e-b2f8-47b1-a2ae-79a3703cf1ac)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Postman
 - Version 10.22.0

**Additional context**

**Comment by andrueastman** [comment]
Thanks for raising this @salahBouragba 

As this repo is mainly intended for SDK related issues, any chance you can post the question at the link below to get feedback from the API owners? It would be great if you could post back the link to the question as a comment so that anyone who comes across this may also find the information as well.

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph

**Comment by salahBouragba** [comment]
Thanks for your reply, I asked the question as you proposed in the Microsoft Q&A corner:
https://learn.microsoft.com/en-us/answers/questions/1526743/mailboxsettings-language-patch-not-working

**Comment by andrueastman** [comment]
Thanks @salahBouragba 

We'll close this so that it may be followed up there.
