### ISSUE TITLE
Save event should have options avoid send out meeting emails to attendees

### ISSUE THREAD

**Issue by idiotsky** [microsoftgraph/msgraph-sdk-dotnet#2323]
I try too sync events with my app, when I save an event with attendees, it automatically send out meeting emails to attendees, even if its a passed event, this cause my thousands of customer receive the my old meeting email another time and I have to explain and apology to them.

we expect when save/update event, there should be a options to determine if it should send meeting request or not.
and also, the passed event should avoid send out meeting email by default.

**Comment by andrueastman** [comment]
Thanks for raising this @idiotsky 

As this is API related behaviour, and this repo is mainly intended for SDK related issues, any chance you can create a request at the link below to get feedback from the API owners? IT would be great if you could post back the link here as a comment so that anyone who comes accross this may upvote it too. 

https://feedbackportal.microsoft.com/feedback/forum/ebe2edae-97d1-ec11-a7b5-0022481f3c80
