### ISSUE TITLE
Microsoft graph api list events returns internal server error.

### ISSUE THREAD

**Issue by yundatsai** [microsoftgraph/msgraph-sdk-dotnet#2348]
**Describe the bug**
Microsoft graph api list events returns internal server error.

Status Code: InternalServerError
Microsoft.Graph.ServiceException: Code: ErrorInternalServerError
Message: An internal server error occurred. The operation failed.
ClientRequestId: 8ca5f68d-1c1d-4b56-af7f-3791f4a24d30

**To Reproduce**
keyword = "123"
emailAddress = "test@example.com";
filterString = $"contains(Body/Content, '{keyword}')"
graphServiceClient.Users[emailAddress]
                    .Calendar
                    .Events
                    .Request()
                    .Filter(filterString)
                    .GetAsync();

**Expected behavior**
Return CalendarEventsCollectionPage filtered on the Body/Content fields.

**Screenshots**
![Screenshot 2024-02-21 065232](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/54813149/3e9151d6-c44b-4f60-ba99-101ae4bef9fd)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: chrome
 - Version: 4.45.0
same behavior in graph explorer

**Additional context**
ClientRequestId: 8ca5f68d-1c1d-4b56-af7f-3791f4a24d30

**Comment by andrueastman** [comment]
Thanks for raising this @yundatsai 

As this is an API related issue, and this repo is mainly intended for SDK related issues any chance you can post the same question at the link below so as to get feedback from the API owners on whether this is supported? It would be great if you posted a link to the created question so that anyone who comes accross this may benefit from it as well.

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph
