### ISSUE TITLE
Cannot Extract Text from One Drive Office Files due to assigned SensitivityLabels

### ISSUE THREAD

**Issue by RutvikaMahajan98** [microsoftgraph/msgraph-sdk-dotnet#2462]
Hi , 
I have one WebAPI which extracts Text from document  (using temporary File generated after downloading onedrive download Url). This document is uploaded from teams chat and is stored in one drive under ms chat files folder. So for  .docx file , it is returning as 400( Bad request) -file is corrupted or has invalid unsupported file format but for .pdf files , it is able to extract the text without any error  .This 400 error is due to the sensitivity labels assigned to files after uploading to teams .
Can someone guide me on how to remove those sensitivity labels after downloading the file to temporary location.
Any help is appreciated.
Thank You.

**Comment by andrueastman** [comment]
Thanks for raising this @RutvikaMahajan98 

As this is an API related question, we may not be best placed to answer this as this repo is mainly intended for SDK related issues. Any chance you can post the question at the link below to get feedback from the API owners? (It would be great if you could post back the link of the created issue here as a comment so that anyone who comes accross this may also find the info)

https://aka.ms/askgraph

**Comment by RutvikaMahajan98** [comment]
Thanks for the link but can you provide the link  of github repo for the same.

**Comment by andrueastman** [comment]
At the moment, the API teams will interact with questions at https://aka.ms/askgraph and feedback requests at https://aka.ms/graphfeedback and not via Github.
