### ISSUE TITLE
Malfunction on "Search for DriveItems within a drive" end-point

### ISSUE THREAD

**Issue by RuanAlesi** [microsoftgraph/msgraph-sdk-dotnet#2478]
### Describe the bug

I am trying to [search for files](https://learn.microsoft.com/en-us/graph/api/driveitem-search?view=graph-rest-1.0&tabs=csharp) created or deleted by my solution, but there's a huge delay to return the correct values, mainly after deleted, it keeps returning the file for a while, even for hours.

### Expected behavior

It shouldn't return deleted files (considering the [permanent delete end-point](https://learn.microsoft.com/en-us/graph/api/driveitem-permanentdelete?view=graph-rest-1.0))

### How to reproduce

Use the Graph Explorer (or Postman) to [delete a file](https://learn.microsoft.com/en-us/graph/api/driveitem-permanentdelete?view=graph-rest-1.0) in OneDrive, then [search](https://learn.microsoft.com/en-us/graph/api/driveitem-search?view=graph-rest-1.0&tabs=csharp) for the file metadata.

### SDK Version

5.48.0

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by andrueastman** [comment]
Thanks for raising this @RuanAlesi 

As this issue is related to the functionality of the API and this repo is mainly intended for SDK related issues we may not be best placed to help resolve this. Any chance you can create an issue at the link below to get feedback from the API owners? (It would be great if you could post back the link here a comment so that anyone who finds this may also find the info as well)

https://aka.ms/graphfeedback
