### ISSUE TITLE
POST /security/alerts_v2/{alertId}/comments returns 400 "Empty Payload. JSON content expected."

### ISSUE THREAD

**Issue by jcoliz** [microsoftgraph/msgraph-sdk-dotnet#2514]
### Describe the bug

Calling the following code, where `alertId` is an Id known to the service, and `commentText` is "New comment", leads to an `Microsoft.Graph.Models.ODataErrors.ODataError` exception being thrown.

```c#
    protected Task<List<Microsoft.Graph.Models.Security.AlertComment>?> SetComment(string alertId, string commentText)
    {
        Microsoft.Graph.Models.Security.AlertComment comment = new() { OdataType = "microsoft.graph.security.alertComment", Comment = commentText };
        List<Microsoft.Graph.Models.Security.AlertComment> body = [ comment ];

        return graphClient.Security.Alerts_v2[alertId].Comments.PostAsync(body);
    }
```

App does have necessary `SecurityAlert.ReadWrite.All` permission for this call. Looks like an SDK issue, because no obvious reason that body would be blank. See "Other information" below for my theory on the problem.

### Expected behavior

Call is expected to succeed

### How to reproduce

Please see above

### SDK Version

5.53.0

### Debug output

<details><summary>Click to expand log</summary>
Exception thrown: 'Microsoft.Graph.Models.ODataErrors.ODataError' in System.Private.CoreLib.dll
</details>

### Configuration

- OS: Windows 11 23H2
- Arch: x64

### Other information

I am wondering about this line at CommentsRequistBuilder.cs:134:

```c#
        requestInformation.SetContentFromParsable(base.RequestAdapter, "application/json", (IEnumerable<AlertComment>)body);
```

If I try to do this myself, I get an exception

```c#
        List<Microsoft.Graph.Models.Security.AlertComment> body = [ comment ];
        var ew = (IEnumerable<AlertComment>)body;
```

```
Unable to cast object of type 'System.Collections.Generic.List`1[Microsoft.Graph.Models.Security.AlertComment]' to type 'System.Collections.Generic.IEnumerable`1[MdeSamples.Models.AlertComment]'.
```

Why even make the cast? The compiler will match just fine without it.

**Comment by andrueastman** [comment]
Thanks for raising this @jcoliz 

Taking a look at the request builder below, there does not seem to be a cast bein performed by the SDK. Any chance you can confirm the location of the line you are speaking of?

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/d6387beb7dcd16968784d06a0b646998945c1301/src/Microsoft.Graph/Generated/Security/Alerts_v2/Item/Comments/CommentsRequestBuilder.cs#L87

Furthermore the error seems to suggest another type that exists in your code that is not `Microsoft.Graph.Models.Security.AlertComment` which seems to be `MdeSamples.Models.AlertComment` any chance you can confirm if the issue here is not an ambiguous reference due to multiple namespaces imported that have a type called `AlertComment`?

**Comment by scottzach1** [comment]
https://github.com/microsoftgraph/msgraph-sdk-java/issues/2131#issuecomment-2619712925
