### ISSUE TITLE
Cannot filter Azure B2C's applications by Description property

### ISSUE THREAD

**Issue by mateuszkumpf** [microsoftgraph/msgraph-sdk-dotnet#2552]
**Description of problem**
I am trying with Graph SDK but also GraphExplorer to filter applications by the "Description" property. Based on the documentation (https://learn.microsoft.com/en-us/graph/aad-advanced-queries?tabs=http#application-properties) this field is supported while trying to use this filter I get the error "Unsupported or invalid query filter clause specified for property 'description' of resource 'Application'.".

In both of the following cases, I receive the same error:
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/24723556/ad0268cc-5af3-4b6f-bd23-21f1e0f88de8)
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/24723556/dc1ac5fb-f983-4c33-96a6-7cbe55aeae7f)

**Expected behavior**
The field is supported as stated in the documentation.

**How to reproduce**
Use url in GraphExplorer:
https://graph.microsoft.com/v1.0/applications?$filter=(description+eq+'1234')&$count=true
with header ConsistencyLevel=eventual

or use code:
```c#
var applications = await GraphClient.Applications
    .GetAsync(
        (requestConfiguration) =>
        {
            requestConfiguration.QueryParameters.Filter = $"description eq '1234'";
            requestConfiguration.QueryParameters.Count = true;
            requestConfiguration.Headers.Add("ConsistencyLevel", "eventual");
        },
        cancellationToken);
```

**SDK Version**
5.56.0

**Comment by andrueastman** [comment]
Thanks for raising this @mateuszkumpf 

According to the documentation at https://learn.microsoft.com/en-us/graph/aad-advanced-queries?tabs=http#application-properties, advanced query capabilities are not supported for Azure AD B2C tenants. 
<img width="646" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/6464005/c3a2ca5d-f6b0-48f7-a41d-9ba575818ea2">

Please feel free to upvote/provide feedback with regards to this at https://aka.ms/graphFeedback so that the API owners can look into prioritizing this. 

We'll close this one for now as this is not actionable from the SDK side.
