### ISSUE TITLE
Graph exceptions are no longer ServiceExceptions, instead they are ODataError?

### ISSUE THREAD

**Issue by catmanjan** [microsoftgraph/msgraph-sdk-dotnet#2580]
### Describe the bug

We are trying to upgrade a code base from v4 to v5 and a large part of the code relies on parsing errors from Graph.

In v4 these errors came through as ServiceExceptions which had a handy IsMatch function so we could search for error strings.

Now in v5, if an error occurs we now get ODataError exceptions which do not have this function.

### Expected behavior

Should still be ServiceException as far as I can tell

### How to reproduce

```
try
{
     var  mailFolders = Graph.Users["doesnotexist"].MailFolders
                .Delta
                .GetAsDeltaGetResponseAsync().Result;
}
catch (AggregateException ae)
{
    // this was ServiceException in v4:
   Console.WriteLine(ae.InnerException.GetType().Name);
}
```

### SDK Version

5.56

### Latest version known to work for scenario above?

4.54

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by andrueastman** [comment]
Thanks for raising this @catmanjan 

To confirm, the ServiceException class is now replace with a model from the API (OdataError). Any chance the documentation at the link below is useful for you? 

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/errors.md

**Comment by catmanjanalt** [comment]
@andrueastman thanks that looks interesting, but it doesn't seem to work as described - the exceptions that are thrown are of type AggregateException, not OdataError...

![image](https://github.com/user-attachments/assets/245804b8-160d-45c3-b1bb-61c2cdd0da31)

**Comment by catmanjanalt** [comment]
BTW there is only one exception within AggregateException... 
![image](https://github.com/user-attachments/assets/21f649a5-d4b6-4831-a2ba-b4a808e76a94)

**Comment by catmanjan** [comment]
see feedback above

**Comment by andrueastman** [comment]
@catmanjan 

The real reason for the `AggregateException` is because you are using Task.Result. See best practices at the link below.

https://learn.microsoft.com/en-us/archive/msdn-magazine/2013/march/async-await-best-practices-in-asynchronous-programming

>  However, when you synchronously block on a Task using Task.Wait or Task.Result, all of the exceptions are wrapped in an AggregateException and thrown.

Is there any reason not to use async/await here? If you do, the documentation at the link earlier should work out for you. 

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/errors.md

**Comment by tjmoore** [comment]
> Thanks for raising this @catmanjan
> 
> To confirm, the ServiceException class is now replace with a model from the API (OdataError). Any chance the documentation at the link below is useful for you?
> 
> https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/errors.md

Dead link.

There doesn't seem to be any documentation that lists what the possible error codes are in ODataError ?

Can we still rely on the same codes that were in `ServiceException`, for example `ErrorAccessDenied`, `Authorization_RequestDenied` etc? (though the latter may be now generalised in `Azure.Identity.AuthenticationFailedException` that is thrown now directly instead of as an `InnerException` in `ServiceException`
