### ISSUE TITLE
Expand and Filter on User throws error

### ISSUE THREAD

**Issue by dk8sumka** [microsoftgraph/msgraph-sdk-dotnet#2586]
### Describe the bug

When trying to get the user profiles using the MS Graph SDK v5, it throws error.
It works fine when
- Only filter query is added
- Only Expand query is added
But as soon as both are added, it starts throwing error related to filter

### Code
 userCollection = await graphClient.Users.GetAsync(reqConfig =>
                    {
                        reqConfig.QueryParameters.Select = new string[] { "Id", "UserPrincipalName", "DisplayName", "Department", "JobTitle", "Mail", "MobilePhone", "EmployeeId", "Country", "BusinessPhones", "OnPremisesExtensionAttributes", "MailNickname", "Manager" };
                        reqConfig.QueryParameters.Filter = $"(onPremisesExtensionAttributes/extensionAttribute1 eq 'SomeValue' and onPremisesExtensionAttributes/extensionAttribute2 in ({entityTenantIDsQuery}))";
                        reqConfig.Headers.Add("ConsistencyLevel", "eventual");
                        reqConfig.QueryParameters.Count = true;
                        reqConfig.QueryParameters.Expand = new string[] { "manager" };
                    });

### Error
ex.Error.Message: Invalid filter clause: Syntax error: character '%' is not valid at position 22 in 'startswith(displayName%2C+'J')'.
ex.Error.Code: "BadRequest"

 **Note: I have also tried the example provided in the documentation over groups where both the filter and expand  is used is also throwing error** 

### Expected behavior

Should return the results as in the individual queries i.e.. When only filter or expand is added

### How to reproduce

userCollection = await graphClient.Users.GetAsync(reqConfig =>
                    {
                        reqConfig.QueryParameters.Select = new string[] { "Id", "UserPrincipalName", "DisplayName", "Department", "JobTitle", "Mail", "MobilePhone", "EmployeeId", "Country", "BusinessPhones", "OnPremisesExtensionAttributes", "MailNickname", "Manager" };
                        reqConfig.QueryParameters.Filter = "(employeeId ne null)";
                        reqConfig.Headers.Add("ConsistencyLevel", "eventual");
                        reqConfig.QueryParameters.Count = true;
                        reqConfig.QueryParameters.Expand = new string[] { "manager" };
                    });

### SDK Version

5.56.0

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by andrueastman** [comment]
Thanks for raising this @dk8sumka 

The code snippet constructed looks correct. However, it seems due to a current API limitation, it is currently not possible to use the $expand parameter combined with the advanced queries on Microsoft Entra ID objects. You can find more information in the documentation below. Removing the $expand should result in a successful response.

https://learn.microsoft.com/en-us/graph/aad-advanced-queries?view=graph-rest-1.0&tabs=http#query-scenarios-that-require-advanced-query-capabilities

If you wish, please provide feedback to the API owners to look into this so that this may supported from the API end. 

https://aka.ms/graphFeedback
