### ISSUE TITLE
Add support for using gRPC to query Graph

### ISSUE THREAD

**Issue by Eagle3386** [microsoftgraph/msgraph-sdk-dotnet#2675]
### Is your feature request related to a problem? Please describe the problem.

Microsoft heavily invested (BTW: still does invest, thanks so much!) in gRPC-dotnet as successor to WCF.

Therefore, it would be awesome, if newer web apps & of course APIs - built using only gRPC-dotnet for communication with clients & other services - could use the same to communicate with the Graph API.

### Describe the solution you'd like.

Allow for usage of gRPC(-Web) to communicate with the Graph API via its `GraphServiceClient`.

### Additional context?

For example, I'm in the process of building a gRPC-only micro-services architecture with a Blazor WASM standalone frontend & a BFF-pattern compliant public endpoint which will also function as the `GraphServiceClient`'s "home".
However, due to lack of gRPC-support, the Graph can't be queried using the same communication technology, but instead imposes further technologies to be added to the - already quite huge - tech stack.

**Comment by andrueastman** [comment]
Thanks for raising this @Eagle3386 

I believe at the moment the API doesn't support GRPC as a transport for making requests to it. Which would be the precursor for this to be supported from the SDK front. I'm not sure if there are immediate plans for this though.

As this would require API support first, would you be willing to create a request/feedback item at the link below to for this feedback to be looked into by the API owners? It would be great if you could post back a link of the created item here so that anyone who comes across this may find it an upvote it as well.

https:// aka.ms/graphFeedback

**Comment by Eagle3386** [comment]
@andrueastman sure, but what to select as "category" over there? TBH, I find the form quite confusing, given the purpose of providing feedback.

**Comment by andrueastman** [comment]
I believe the correct category would be "General" as it targets the API in general and not a specific api.

**Comment by Eagle3386** [comment]
Done: https://feedbackportal.microsoft.com/feedback/idea/bd61692a-6485-ef11-9442-002248546a2e

**Comment by andrueastman** [comment]
Thanks @Eagle3386 
I'll close this for now. This can be followed up/upvoted on that end by anyone who comes across this.
