### ISSUE TITLE
Any way to get list of available delegates from a mailbox using the graph API?

### ISSUE THREAD

**Issue by Nyoibouu** [microsoftgraph/msgraph-sdk-dotnet#286]
Hey,

The title pretty much sums up my question. I need to know if it's possible to get a list of the delegates who have permission to act on behalf of an account.

Thanks!

**Comment by MIchaelMainer** [comment]
@Nyoibouu In short, the answer is no. I've made sure that this is in the backlog for the folks responsible for this feature. I've linked to this issue from that backlog. Please go vote on this so that the PMs know how much you value this feature.
https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/30973693-add-and-remove-delegates-by-using-microsoft-graph
