### ISSUE TITLE
Add OnPremisesDistinguishedName to the User model

### ISSUE THREAD

**Issue by ryanspletzer** [microsoftgraph/msgraph-sdk-dotnet#339]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [x] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [x] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior

User model returns OnPremisesDistinguishedName.

### Actual behavior

User model does not have the OnPremisesDistinguishedName property

### Steps to reproduce the behavior

Query the graph with the SDK and inspect the User object, the OnPremisesDistinguishedName is not one of the available properties.

**Comment by MIchaelMainer** [comment]
Here's the easiest way to get this property assuming the scopes on your token gives you access to this property:

1. Set the base URL on GraphServiceClient to `https://graph.microsoft.com/beta`.
2. Include the OnPremisesDistinguishedName property in the .Select().
3. When the User object is returned, search the User.AdditionalData dictionary for OnPremisesDistinguishedName.

Otherwise, you'll need to wait until the OnPremisesDistinguishedName hits the v1.0 metadata, or we release a beta client library.

Please reopen this issue if these instructions don't help.

**Comment by ryanspletzer** [comment]
@MIchaelMainer Is it safe to use the beta endpoint in prod though?

**Comment by MIchaelMainer** [comment]
@ryanspletzer 

> Is it safe to use the beta endpoint in prod?

Absolutely not. Beta is often times not fully baked. We've seen big churn in API signatures over time within beta. In general, don't do it. But if you really must, here's an unadvisable option: if you like to defensively gamble with a not yet supported scenario, if the API is already well established in v1.0, and there is a new property/method on an object in that established API that you want to use that is only in beta, and your app can handle potential changes to the property/method, then maybe you could consider it. It still won't be safe.
