### ISSUE TITLE
UpdateAsync on OneNote notebook fails

### ISSUE THREAD

**Issue by arcadiogarcia** [microsoftgraph/msgraph-sdk-dotnet#377]
I ran the following code to change the name of a OneNote notebook:

```csharp
var notebooks = await (await client.Me.Onenote.Notebooks.Request().GetAsync());
var notebook = notebooks.First();
notebook.DisplayName = "something";
var result = await client.Me.Onenote.Notebooks[notebook.Id].Request().UpdateAsync(notebook);
```

But the update request fails, throwing this exception:

````
Code: UnknownError
Message: {
  "Message": "No HTTP resource was found that matches the request URI 'https://www.onenote.com/api/v1.0/users('myemail')/notes/notebooks('notebookid')'."
}

Inner error

````

As far as I can tell (I haven't found any example of updating a notebook in the documentation/tests) this seems the right way to do it. Am I forming the request incorrectly or is this a bug? 
[AB#7312](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7312)

**Comment by arcadiogarcia** [comment]
FWIW, I experimented a little in https://developer.microsoft.com/graph/graph-explorer/ and 
`GET https://www.onenote.com/api/v1.0/users('myemail')/notes/notebooks('notebookid')`
does not work, as far as I can't tell it doesn't even return an error message, but the seemingly equivalent
`GET https://graph.microsoft.com/v1.0/users('myemail')/onenote/notebooks('notebookid')`
returns the notebook at expected.

**Comment by MIchaelMainer** [comment]
I'm sorry @arcadiogarcia we aren't making this easy. First off, I took a look at the documentation for the REST API and [I don't see a way to update the name of a notebook.](https://docs.microsoft.com/en-us/graph/api/resources/notebook?view=graph-rest-1.0) We can create and list notebooks. I'm a bit surprised by this. To make matters worse, we generate the client from metadata (incomplete in this case) that resulted in us generating a method on the client, UpdateAsync(), that is not part of the service contract. Again, this is not the experience I want for you, and I'm sorry about that.

At a minimum, please sign up for the [Office 365 Developer Program](https://docs.microsoft.com/en-us/office/developer-program/office-365-developer-program) so that you can get access to a demo tenant so that you don't thrash your notebooks and other data.

**Comment by MIchaelMainer** [comment]
I would say copy and rename the notebook but there isn't a way to delete the old notebook. We need Update and Delete on notebooks. I'm going to communicate this to the service API team.

**Comment by arcadiogarcia** [comment]
Any updates on this? Looks like PATCHing notebooks is still not supported

**Comment by MIchaelMainer** [comment]
Related to #458 so that we don't generate non-existent functionality, and it appears that notebook update still doesn't exist according to documentation. Closing this as it duplicates the need for annotation support.

The service API still doesn't support updating notebooks. 
https://docs.microsoft.com/en-us/graph/api/resources/notebook?view=graph-rest-1.0
