### ISSUE TITLE
Error when creating education school

### ISSUE THREAD

**Issue by timvandesteeg** [microsoftgraph/msgraph-sdk-dotnet#408]
Getting the following error when trying to add a school.

```
Code: Request_BadRequest
Message: The following extension properties are not available: extension_fe2174665583431c953114ff7268b7b3_Education_ObjectType,
extension_fe2174665583431c953114ff7268b7b3_Education_CreatedByAppId,
extension_fe2174665583431c953114ff7268b7b3_Education_CreatedByUserId,
extension_fe2174665583431c953114ff7268b7b3_Education_SchoolNumber,
extension_fe2174665583431c953114ff7268b7b3_Education_SyncSource_SchoolId.
```

Is this related to this library since all education stuff is in preview or is a setting in AD?
Thank you :)

**Comment by MIchaelMainer** [comment]
This is probably not an issue with the client library. It is hard to say what the issue is since you haven't provided enough repro information. I highly suggest that you capture the request/response with Fiddler for both the calls that setup the extension and the call that accesses the extension. Post your question to StackOverflow with the Microsoft-Graph tag. Be sure to include request/responses and the client code used to generate the requests and responses. Post a link to your SO question in this issue.
