### ISSUE TITLE
calendar:getSchedule to show event information

### ISSUE THREAD

**Issue by aleybovich** [microsoftgraph/msgraph-sdk-dotnet#499]
[calendar:getSchedule](https://docs.microsoft.com/en-us/graph/api/calendar-getschedule?view=graph-rest-1.0)  returns busy slots for a resource but it only has event titles and times. Is there any way to add event ID's so that those events can be identified and further worked with?

Use case: my application pushes events to Office 365. If for a given event to push, the room is not available for the event timeframe, I need to generate an email to the existing event's creator that they should reschedule they manual event as the automatic events from my app have the priority.

Currently, when I get the availability for a given room using `calendar/getSchedule` API call, there is no easy way to get the actual events for each busy slot returned. If an event ID was included in each busy slot in the response, it would be easy to further retrieve event information, including event creator.

**Comment by peombwa** [comment]
Since this is a service feature request, you should post it on [Microsoft Graph Uservoice](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests). There's already an [open request](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/36476284-please-add-more-information-in-the-following-respo) related to the response returned by `calendar/getSchedule`; You can vote it up and add more info in the comments sections.
