### ISSUE TITLE
Microsoft.Graph 1.16.0 depends on Microsoft.Graph.Core 1.15.0 instead of 1.16.0

### ISSUE THREAD

**Issue by habex-ch** [microsoftgraph/msgraph-sdk-dotnet#513]
The NuGet-Package "Microsoft.Graph" 1.16.0 depends on the wrong version of Microsoft.Graph.Core. It depends on 1.15.0 but should depend on Microsoft.Graph.Core 1.16.0.

I had Microsoft.Graph 1.16.0 installed and was implementing a batch-request solution. After a while I run into the same issue as described in #470. It costs my a lot of time and nerves to find the "bug". After explicit installing Microsoft.Graph.Core 1.16.0 everything was fine.

Other user may have the same expires.

**Comment by darrelmiller** [comment]
Due to the similarity of version numbers it would appear that way.  However, Microsoft.Graph 1.16 was released when Microsoft.Graph.Core was 1.16 was still in preview.  Moving forward the versions of Microsoft.Graph and Microsoft.Graph.Core will diverge and be independent.  I am happy to hear that the now released 1.16 version of core resolves your issue.  Sorry for the confusion.
