### ISSUE TITLE
Beta NuGet Release Schedule

### ISSUE THREAD

**Issue by christophwille** [microsoftgraph/msgraph-sdk-dotnet#542]
https://www.nuget.org/packages/Microsoft.Graph.Beta/

Is there a schedule to releasing builds of the Beta Graph NuGet? Or is there a MyGet feed I can tap into before it actually lands on NuGet?

**Comment by MIchaelMainer** [comment]
Hello @christophwille 

The schedule is supposed to be every Tuesday upon a successful build. After 7AM PST, I will know if we can release today.

**Comment by christophwille** [comment]
Every Tuesday? The last release on nuget.org was two months ago. Did you mean a MyGet feed that I don't know of?

**Comment by darrelmiller** [comment]
@christophwille We get a PR every Tuesday, but we are not currently releasing at that cadence yet.  We have been blocked on releasing recently due to some invalid metadata in a beta API.  That was fixed yesterday so we were going to be able to release.  However, another update to the metadata yesterday caused us a new challenge.  We are working on getting a release out ASAP.

**Comment by christophwille** [comment]
Thanks, at least I didn't miss something obvious. Would it be possible to somehow "flag" that such an issue (invalid metadata) exists much like a build break?

**Comment by darrelmiller** [comment]
@christophwille Thank you for the suggestion.  Currently our automation process doesn't create the PR if it fails to build.  Michael and I were discussing if we should just create it anyway and have it show as a failed build.  Your suggestion validates that idea.
