### ISSUE TITLE
[Client bug]: batch request vs non-batch request - inconsistent DateTime results

### ISSUE THREAD

**Issue by arnederuwe** [microsoftgraph/msgraph-sdk-dotnet#587]
**Describe the bug**
When querying the graph API, there is a difference in how DateTimes are serialized when querying with or without batching.
With batching, the serialized DateTime isn't ISO 8601 compliant, therefore the `ToDateTime()` extension method inside this repository is throwing a FormatException.

When inspecting the graph response JSON, the date format is the same in both the batched and not-batched request, so this is most likely a client bug.

**To Reproduce**
Run the attached project, after filling in tenant/clientid/secret...
The console will first log the startdates of events queried without batching and then the same startdates queried with batching.

**Expected behavior**
Executing a query against graph with batching should yield exactly the same DTO response as without batching

**Screenshots**
![image](https://user-images.githubusercontent.com/3369747/68773489-f0b55f00-062b-11ea-8273-5b89e94ccd1d.png)

**Client version**
Packages used:
```
<PackageReference Include="Microsoft.Extensions.Configuration" Version="2.2.0" />
<PackageReference Include="Microsoft.Graph" Version="1.20.0" />
<PackageReference Include="Microsoft.Graph.Auth" Version="1.0.0-preview.0" />
<PackageReference Include="Microsoft.Graph.Core" Version="1.19.0-preview.3" />
<PackageReference Include="Microsoft.Identity.Client" Version="4.3.0" />
```

**Desktop (please complete the following information):**
 - OS: Win10
- Net Core 3 console app, the same behavior in a .NET Standard class lib

**Additional context**
[msgraph-batch-issue.zip](https://github.com/microsoftgraph/msgraph-sdk-dotnet/files/3841742/msgraph-batch-issue.zip)

**Comment by darrelmiller** [comment]
@andrueastman  Can you verify this sample and see if why the responses might be getting deserialized differently?  My understanding is that they are both using an instance of our standard Serializer so the JSON.NET settings should be identical.  If the JSON payloads are the same, I see no reason why this problem should be happening.

**Comment by andrueastman** [comment]
@darrelmiller I will look into this.

**Comment by andrueastman** [comment]
We do indeed use the same serializer when trying to deserialize to native objects.

However, it looks like the issue is caused by the `JsonTextReader` instance created [here ](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/3c24714576bc82950e6aa9ae24df67b0626a34dd/src/Microsoft.Graph.Core/Requests/Content/BatchResponseContent.cs#L190)in order for the batchResponseContent to be able to parse out the id, status, headers and body from the larger batch response message. 

This instance will need to be given the same settings as those used by the standard serializer to fix this.

Also, is there any reason why the  `JsonTextReader` instance in the standard serializer [here ](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/3c24714576bc82950e6aa9ae24df67b0626a34dd/src/Microsoft.Graph.Core/Serialization/Serializer.cs#L62)is not created with the same settings?

@darrelmiller @MIchaelMainer

**Comment by MIchaelMainer** [comment]
@andrueastman The reason is unknown for why that is the case.
