### ISSUE TITLE
Updating library from 1.17 to 1.20 introduce breaking change by making authentication provider mandatory

### ISSUE THREAD

**Issue by andrew-vdb** [microsoftgraph/msgraph-sdk-dotnet#605]
This is working on 1.17
```
var accessToken="xxxx";
var graphClient = new GraphServiceClient(null);

 var user = await graphClient.Me.Request(new List<HeaderOption>()
            {
                   new HeaderOption("Authorization", "Bearer " + accessToken)
            }).GetAsync();

```

Breaking change 1 on 1.20
```
var graphClient = new GraphServiceClient(null); // NullException being thrown
```

Breaking change 2 on 1.20
```
var accessToken="xxxx";
var graphClient = new GraphServiceClient(new HttpClient());

 var user = await graphClient.Me.Request(new List<HeaderOption>()
            {
                   new HeaderOption("Authorization", "Bearer " + accessToken)
            }).GetAsync();// Authentication provider is required before sending a request. 
```
First of all, why breaking change on minor update?

Why make authentication provider required? It was good, I put the access token to the request anyway but now i get this error
Status Code: 0
Microsoft.Graph.ServiceException: Code: invalidRequest
Message: Authentication provider is required before sending a request.

**Comment by MIchaelMainer** [comment]
We never intended that the first parameter in the GraphServiceClient cstor be nullable. We would have added a cstor with no parameters if we intended for a null authprovider. When we added a new overload to take a single parameter of type HttpClient, this broke your usage.

The authentication provider was required as it was a convenient way to set how the access token was managed and retrieved for all requests instead of having to have it set on each request like you have done. 

If you set access token management in the authentication provider, you never have to set the List<HeadOption> on every call to Microsoft Graph in your code. 

What value do you find in setting the token in each request? Perhaps there's a scenario we overlooked.

Why not set the access token like this:

```csharp
                    graphClient = new GraphServiceClient(
                        new DelegateAuthenticationProvider(
                            async (requestMessage) =>
                            {
                                var token = await GetAccessToken();
                                requestMessage.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("bearer", token);

                            }));
```

Then you don't need to set it in every request.

**Comment by andrew-vdb** [comment]
We already discussed this before here
https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/460

I have thousands of users which have different access token, since version 1.15, i can have **one** singleton instance of GraphServiceClient to serve all my users, now by the breaking change I have to go back to create new instance per request?

**Comment by MIchaelMainer** [comment]
We'll resurface that old API behavior. 

Note for bug in M.G.C: Update SimpleHttpProvider cstor to create an HttpClient using the GraphClientFactory with a default pipeline when HttpClient passed in is null. I'll update this issue when we have a fix published as a preview.

**Comment by peombwa** [comment]
@andrew-vdb, for now, you can use named parameter to explicitly set `authenticationProvider` to null.
``` cs
var graphClient = new GraphServiceClient(authenticationProvider: null);
```

**Comment by andrew-vdb** [comment]
Thanks, I will hold back updating the library till new version released...

**Comment by MIchaelMainer** [comment]
@andrew-vdb we'll publish a preview build with this fix for you to verify.

**Comment by andrew-vdb** [comment]
@MIchaelMainer thanks! I can test it tomorrow Monday.

**Comment by andrew-vdb** [comment]
Tested with graph 1.21 and graph core 1.20.0-preview.1, it seems to be working without any code change on my side, thanks!
