### ISSUE TITLE
Re-using authentication when developing

### ISSUE THREAD

**Issue by teradevel** [microsoftgraph/msgraph-sdk-dotnet#645]
Is it possible to re-use authentication? Right now I have to authenticate every time I run the program, which is pretty often because I am developing it. If so, how?

Ideally I could authenticate once, and keep using that authentication when I re-run the program after recompilation.

I have tried serializing the authentication provider, which only works when I do the serialization and de-serialization during one run of the program but fails if the serialization and de-serialization are done on different runs.

I use DeviceCodeAuthProvider.

**Comment by peombwa** [comment]
@teradevel DeviceCodeAuthProvider doesn't handle token caching. Instead, we do rely on MSAL to serialize tokens to a cache.

Please follow the instructions provided [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/token-cache-serialization#simple-token-cache-serialization-msal-only) to implement a token cache for a public client application.

Also, ensure the cache file is not in your bin folder since you are recompiling your app.
