### ISSUE TITLE
Workbook.CreateSession(false) does not work

### ISSUE THREAD

**Issue by stevehansen** [microsoftgraph/msgraph-sdk-dotnet#68]
As we can see in the https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/master/src/Microsoft.Graph/Models/Generated/WorkbookCreateSessionRequestBody.cs file the PersistChanges property has EmitDefaultValue  set to false:

```c#
        [DataMember(Name = "persistChanges", EmitDefaultValue = false, IsRequired = false)]
        public bool PersistChanges { get; set; }
```

This causes the value to not be send so that the Graph api uses the default option (true)

**Comment by cbales** [comment]
Hi Steve! This looks like it's a service error instead of an SDK issue. Directly calling `/workbook/createSession` with a body of `{ "persistChanges": false }` using REST still returns a SessionInfo object with persistChanges set to true.

Could you post a question on StackOverflow and tag it as [microsoftgraph] and [excel]? This will allow someone from the service team to respond to your inquiry.

Thanks!
