### ISSUE TITLE
IDriveItemRequestBuilder.Copy() not working

### ISSUE THREAD

**Issue by JogyBlack** [microsoftgraph/msgraph-sdk-dotnet#73]
When trying to use the Copy() method to copy a OneDrive file from one folder to another, an invalid request exception is thrown containing the message "Cannot call Copy without the respond-async preference"

Here is sample code:
```
        var client = AuthenticationHelper.GetAuthenticatedClient();
        var files = await client.Me.Drive.Root.Children.Request().GetAsync();
        DriveItem firstFolder = null, firstFile = null;

        foreach (var file in files)
        {
          if (file.Folder != null)
		  {
            if (firstFolder == null)
              firstFolder = file;
          }
          else if (file.File != null)
          {
            if (firstFile == null)
              firstFile = file;
          }
        }


        if (firstFolder != null && firstFile != null)
        {
          ItemReference destination = new ItemReference() { Id = firstFolder.Id };

          var copiedItem = await client.Me.Drive.Items[firstFile.Id].Copy(parentReference: destination).Request().PostAsync();  // Throws exception
        }

```

**Comment by JogyBlack** [comment]
A possible fix is to add the line 
`            this.Headers.Add(new HeaderOption("Prefer", "respond-async"));
`
in the constructor of **DriveItemCopyRequest**

and also to modify it to return void instead of DriveItem, since the request response will not return item information. See the documentation of [Copy Item](https://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/item_copy) : _The response from the API will only indicate that the copy operation was accepted or rejected, say due to the destination filename already being in use._

**Comment by cbales** [comment]
Hi Jogy, thanks for bringing this to our attention. Unfortunately, our team is heading out for the holidays. I wasn't able to verify this on a quick glance, but I'll look into this again in January and respond with an update.

**Comment by cbales** [comment]
I was able to repro your issue with OneDrive (it appears OneDrive for Business does not require this header). Because this file is auto-generated, the best course of action in this case would be to manually add the header in your custom application. I realize this isn't as ideal as having the library handle it, and we are looking into ways to override generated code elegantly in the future.

I will investigate the prefer header, since the fact that it is required seems strange to me. I also agree that the function should return null; the reason that it does not is due to a bug in the underlying metadata that the library is generated from. I will log this with the OneDrive team.
