### ISSUE TITLE
[Client bug]: Update Scheduling groups does not work properly

### ISSUE THREAD

**Issue by odinservely** [microsoftgraph/msgraph-sdk-dotnet#738]
Using graph sdk to update scheduling group, returns Unknown error. 
After a first contact with MS Support, we found that using PUT instead of PATCH works just fine. 
Knowing this should help you to resolve the issue.

You can reproduce this error when updating scheduling group using the graph sdk like on the following picture

<img width="587" alt="ms_support_error" src="https://user-images.githubusercontent.com/34368239/87556192-a6064e00-c6b6-11ea-8047-033613bac2b0.PNG">

It will return an error like this one
`{ "error": { "code": "UnknownError", "message": "", "innerError": { "date": "2020-07-15T12:56:26",
"request-id": "_" } } }`

 
[AB#7251](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7251)

**Comment by zengin** [comment]
This is due to the change I proposed on that a "replace" operation should be "PATCH". Snippet compilation was failing because we only had `UpdateAsync` in the SDK.

@darrelmiller, does this mean that the HTTP API should be fixed?

cc: @pixieofhugs 

Related PR: https://github.com/microsoftgraph/microsoft-graph-docs/pull/8552/files
Documentation: https://docs.microsoft.com/en-us/graph/api/schedulinggroup-put?view=graph-rest-1.0&tabs=http

**Comment by andrueastman** [comment]
Closing this as the latest preview versions of the 4.x.x versions of the sdk add `PutAsync` method functionality.
In this case, you can find the method [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/d2686728ff2bd91e4e1512aec2a391427c6bb37d/src/Microsoft.Graph/Generated/requests/SchedulingGroupRequest.cs#L148)
