### ISSUE TITLE
AzureAD app only permissions Group.ReadWrite.All is able to update user profile?

### ISSUE THREAD

**Issue by belaie** [microsoftgraph/msgraph-sdk-dotnet#74]
Not sure if this is correct place to introduce this issue, but this is what i am doing;

tool: postman

a) created azure ad app, granted app-only permissions Group.ReadWrite.All for **Microsoft Graph** app, the app has delegation permissions as "Sign-in and read user profile on" "Windows Azure Active Directory" app.
b) requested token for AzureAD graph api at  https://login.windows.net/ with resource parameter "https://graph.windows.net",  using client credential grant flows;
c) got token back
d) used the token and did a GET on a User OK
e) did a PATCH on a user  ( modification went successfully with http code 204 back);

**_this looks very strange to me_**, why an app was able to do "patch" on a user in azure ad when app is only granted "Group.ReadWrite.All" on Microsoft Graph API?

**Comment by cbales** [comment]
Hi belaie, 

This is a great question! Since this is an API-related question, and not an SDK question, the best place to ask this would be on StackOverflow. It also appears that you're using the Azure AD Graph API and not the Microsoft Graph API. You can read about the differences [here](https://blogs.msdn.microsoft.com/aadgraphteam/2016/07/08/microsoft-graph-or-azure-ad-graph/). Be sure to tag "azure-graph-api" or "microsoftgraph" as relevant so that we can get back to you with an answer correctly.
