### ISSUE TITLE
ExternalConnection can only be obtained by clientCredential if they also created it, despite having Graph API app permission

### ISSUE THREAD

**Issue by mhomol** [microsoftgraph/msgraph-sdk-dotnet#758]
**Describe the bug**
I noticed something interesting while testing the new external connections.  For some unit testing I decided to make a new client credential from what I had been using so far.  I had created 3 external connections in the API so far with the previous connection.  My test was to perform a GET of the connections.  It returned 0 connections.  As soon as I created a connection I was able to get 1.  

In Azure AD, with the registered app, I have given it the app permission ExternalItem.ReadWrite.All, so my expectation would be that all external connections would be returned.  Yes?

**To Reproduce**
1. Create 2 app registrations in Azure AD, both with the ExternalItem.ReadWrite.All app permission
2. Use the Graph SDK to add an external connection with one of the app id and secrets.
3. Use the Graph SDK to get all external connections with the other app id and secret.
4. Note that you won't get the item you created with the other app id and secret.

**Expected behavior**
My feeling is that because I have given it the app permission ExternalItem.ReadWrite.All and granted consent that I should be able to see everything that has been created, regardless of who created it.

**Desktop (please complete the following information):**
 - OS: MacOS
 - .Net Core latest graph Beta SDK

**Comment by MIchaelMainer** [comment]
Sent mail to connectors folks.

**Comment by mavarshn** [comment]
@mhomol  This behavior is by design. An app can manage only the connections it created or it is authorized to. This is done to protect the data leak across multiple apps with in a Tenant.
If you want to give your 2ndApp permissions to manage the connections created by 1st App, then you can update the connections' "authorizedApps"   section by doing a Patch request - https://docs.microsoft.com/en-us/graph/api/externalconnection-update?view=graph-rest-beta&tabs=http#request
{
  "id": "contosohr",
  "name": "Contoso HR",
  "description": "Connection to index Contoso HR system",
  "configuration": {
    "authorizedApps": [
      "<AAD App id  of 1st App>",
      "<AAD App id  of 2nd App>"
    ]
  }
}

**Comment by mhomol** [comment]
Thank you for the response.
