### ISSUE TITLE
List group members and expand "manager" if member is an user (all in one query)

### ISSUE THREAD

**Issue by mtosic** [microsoftgraph/msgraph-sdk-dotnet#77]
Hi, I wan't to list all members of a group, filter if odata.type = "#microsoft.graph.user" and then expand on property "manager". I don't want to send N queries to fetch "manager" property for every member in a group.

Is it possible to do it in one query with Graph .NET client? I've tried something like:
`var members = await (graphClient.Groups[group.Id].Members.Request() as IGraphServiceUsersCollectionRequest).Expand("manager").GetAsync();`
but it's not working.

Any help would be appreciated.

**Comment by MIchaelMainer** [comment]
@mtosic Can you post your question to StackOverflow with your question and tag it with MicrosoftGraph? Then provide the link in this issue. This way we can get more eyes on the answer. Also, can you use Fiddler and capture the request and response and share it in your SO post so that we can see what is going on?

**Comment by MIchaelMainer** [comment]
The manager property is a navigation property on a user so you'll have to request that property value for each user.
