### ISSUE TITLE
Return null or empty lists instead of throwing exceptions when returning associated data

### ISSUE THREAD

**Issue by petersgiles** [microsoftgraph/msgraph-sdk-dotnet#780]
I'm always frustrated when I query something and the response throws an exception instead of telling me there's nothing there.

Example Bad...I have to manage the exception on every call when a user id doesn't have a manager assigned
```
  public static async Task<DirectoryObject> GetDirectManagerForUser(GraphServiceClient _graphServiceClient, string userId)
        {
            // Because why wouldn't you return null 
            try
            {
                return await _graphServiceClient.Users[userId].Manager.Request().GetAsync();
            }
            catch (Exception)
            {
                return null;
            }
        }
```
Preferred
```
  public static async Task<DirectoryObject> GetDirectManagerForUser(GraphServiceClient _graphServiceClient, string userId)
        {
                return await _graphServiceClient.Users[userId].Manager.Request().GetAsync();
        }
```

**Comment by MIchaelMainer** [comment]
Unfortunately (or fortunately), 404 Not Found applies to both an incorrect URI to a non-existent resource, as well as when an entity doesn't exist at a correct resource URI. There isn't a standard response to state that the URI is correct but the resource wasn't found. The service returns an exception and since our client can't differentiate whether the URL is correct but the resource doesn't exist, we have to pass through the service exception.  

```
{
    "error": {
        "code": "Request_ResourceNotFound",
        "message": "Resource 'manager' does not exist or one of its queried reference-property objects are not present.",
        "innerError": {
            "date": "2020-09-03T16:32:14",
            "request-id": "7f0c1389-cd4b-4fdc-8dca-9b7d60dccd9a"
        }
    }
}
```
