### ISSUE TITLE
CancellationToken support on IAuthenticationProvider.AuthenticateRequestAsync

### ISSUE THREAD

**Issue by PedroLamas** [microsoftgraph/msgraph-sdk-dotnet#83]
Any reason why [IAuthenticationProvider.AuthenticateRequestAsync](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/master/src/Microsoft.Graph.Core/Authentication/IAuthenticationProvider.cs#L20) doesn't support passing a `CancellationToken`?

**Comment by MIchaelMainer** [comment]
There isn't a good reason for not providing a cancellation token for a task (AFAIK). Thank you for bringing this to our attention.

**Comment by MIchaelMainer** [comment]
Sorry for the very tardy reply. The reason why we don't support passing a cancellation token on AuthenticateRequestAsync is because of the interactive nature of auth where the user controls the duration of the interaction with the granting permissions, or the interaction is very quick (no long running operations here, you are either authenticated or not). We expect that most customers will use either ADAL or MSAL for authentication and they don't accept a cancellation token for the above reasons. 

In the case that you're using your own authentication code and you find that you need to cancel a authentication request, wrap your call in a task and pass in your cancellation token.

**Comment by PedroLamas** [comment]
Fair enough! For context (wich I should have put when I opened this issue), I mentioned this as we currently use it on the UWPCommunityToolkit!

https://github.com/Microsoft/UWPCommunityToolkit/search?utf8=%E2%9C%93&q=AuthenticateRequestAsync&type=
