### ISSUE TITLE
$search in url supports characters that the QueryOptions does not

### ISSUE THREAD

**Issue by Harkole** [microsoftgraph/msgraph-sdk-dotnet#883]
**Describe the bug**
A url of `https://graph.microsoft.com/v1.0/me/mailfolders/inbox/messages?$search="subject: [cubic: "&$select=subject, internetMessageId&$top=100` is accepted and returns results using the Graph Explorer. However building the same query using the SDK results in the Search complaining about certain characters in the string as shown below

![image](https://user-images.githubusercontent.com/3703699/105988389-725da500-6097-11eb-87c6-ec458c5e1716.png)

Removing the `subject` limiter, causes the request to error on the `[`

Removing the query options altogether executes the query without error, although the results are not as required

**To Reproduce**
Build the request in C#:
```csharp
            var searchQuery = $"subject: [cubic: ";

            // Build search query for the company prefix value
            var queryOptions = Enumerable
                .Empty<QueryOption>()
                .Append(new QueryOption("search", searchQuery));

            // Get the subject lines from all emails in the Gekko folder
            var emailCollection = await graphClient.Users[emailAddress].MailFolders[folderId].Messages
                .Request(queryOptions)
                .Select(e => new { e.Subject, e.Id, e.InternetMessageId })
                .Top(100)
                .GetAsync(cancellationToken)
                .ConfigureAwait(false);
```

**Expected behavior**
`emailCollection` should contain top 100 results of emails that contain the `[cubic: ` string in the email `Subject` line

**Screenshots**
https://graph.microsoft.com/v1.0/me/mailfolders/inbox/messages?$search="subject: [cubic: "&$select=subject, internetMessageId&$top=100

![image](https://user-images.githubusercontent.com/3703699/105989240-bdc48300-6098-11eb-8dd2-0b18abee0446.png)

*** Code Base
.Net5 Worker Service [SDK version 5.0.102]
Microsoft.Graph v3.22.0 [latest]
 
[AB#7813](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7813)

**Comment by Harkole** [comment]
@andrueastman  I realised that the Uri request that works was encapsulating the search query string in double quotes, adding these to the `searchQuery` string fixes the error and produces the expected results:

As such the resolution to this issue is as follows:
`var searchQuery = $"\"subject: [{prefix} \"";`

Either this is user error, or the SDK should wrap the search query in quotes to make it easier for developers to just focus on the actual string query rather than formatting

**Comment by andrueastman** [comment]
@Harkole I am glad that you sorted it out. That's great news 🎉 .

Since the value is being passed over as a `QueryOption`, it is expected that the second parameter to be everything coming after the `=` character in the resulting query. It would mean that the user is expected to pass the quotation marks or (any other characters) as needed.

In the event we introduced a request builder specifically for the search query param(something like shown below), I believe that would be the best time for the SDK to wrap the search query in quotes to make it easier for developers to just focus on the actual string query rather than formatting.

```cs
var emailCollection = await graphClient.Users[emailAddress].MailFolders[folderId].Messages
                .Request()
                .Search("subject: [{prefix} ")  //new imaginary request builder example
                .GetAsync();
```
I will be closing this issue for now. Please feel free to open an issue in the event something else comes up.
