### ISSUE TITLE
List users who have some role from the ServicePrincipal

### ISSUE THREAD

**Issue by CarlosArmiliato** [microsoftgraph/msgraph-sdk-dotnet#990]
Hi,

In short I need that:
Filter AppRoleId on AppRoleAssignedTo, like this:

``` CSharp
var appRoleAssignedTo = await graphClient.ServicePrincipals[servicePrincipalId]
    .AppRoleAssignedTo
    .Request()
    .Filter($"appRoleId eq {appRoleId}") //It's not able, because appRoleId isn't a filter
    .GetAsync();
```

Has an workaround, calling `appRoleAssignedTo.NextPageRequest` until the last page.
And after, filter this result in memory.
But it's **not ok**. That transfer so much useless data from Azure to my API.

I need this because I have an API that uses Azure AD application roles to grant access for endpoints by user roles.
And this is managed through GraphServices SDK in the same application.
Now I need to show which users have some role granted.

I think that allowing the filter AppRoleId is something that would bring value to SDK, since it is an administrative demand to identify the users who have a certain Role. 
[AB#9307](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9307)

**Comment by andrueastman** [comment]
Hey @CarlosArmiliato, Thanks for opening this issue.

According to [this](https://docs.microsoft.com/en-us/graph/api/resources/approleassignment?view=graph-rest-1.0#properties), it looks like that property isn't supported for filtering via the API.

I have created a feature request for the same at the link below. Please upvote it so that the relevant team may get around to it.

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/application-api-add-support-for-filtering-approleassignment-by/idi-p/2433822#M134

Closing this issue for now so that we may continue to follow it up from there.
